### ISSUE TITLE
Mismatching statements re. `rastertopclm` shell script

### ISSUE THREAD

**Issue by KurtPfeifle** [OpenPrinting/cups-filters#1]
The `COPYING` file states about `filter/rastertopclm`:
> Files: filter/rastertopclm
> Copyright: 2017 Sahil Arora <sahilarora.535@gmail.com>
> License: GPL-3+

However the `filter/rastertopclm` shell script itself says this:
> \# (C) 2017 Sahil Arora <sahilarora.535@gmail.com>
> \#
> \# Released under GPL 2 or later

**Comment by tillkamppeter** [comment]
Fixed in 5abc337472bc70fccfd780004a63e6cbd65d542b

Thank you for reporting.
