### ISSUE TITLE
cups-browsed doesn't automatically detect all printers in LAN without BrowsePoll

### ISSUE THREAD

**Issue by zdohnal** [OpenPrinting/cups-filters#10]
Hi Till,

I have rather question than maybe issue about cups-browsed functionality - should cups-browsed be able to discover and create local queues for all printers in LAN, without need of setting 'BrowsePoll' option? Like all network IPP printers, USB printers, CUPS remote queues will be discovered at the start of cups-browsed without changing cups-browsed.conf?
Because I can only get my remote cups queues when I set 'BrowsePoll' to my server. But it is written in cups-browsed.conf that when no 'Browse...' options are used, cups-browsed will create print queues for all printers in local network.
I have cups-2.2.4 installed and cups-filters-1.16.1.

**Comment by tillkamppeter** [comment]
For cups-browsed to discover the remote CUPS queues in the same local network, it is enough to have a line
```
BrowseRemoteProtocols dnssd
```
in `/etc/cups/cups-browsed.conf`.
For discovering IPP network printers you need to set one of the following:
```
CreateIPPPrinterQueues No
CreateIPPPrinterQueues LocalOnly
CreateIPPPrinterQueues Everywhere
CreateIPPPrinterQueues AppleRaster
CreateIPPPrinterQueues Everywhere AppleRaster
CreateIPPPrinterQueues Driverless
CreateIPPPrinterQueues All
```
Please check your `cups-browsed.conf`, or simply attach it.

**Comment by tillkamppeter** [comment]
And for USB printers: Conventional USB printers are not discovered and set up by cups-browsed. For IPP-over-USB printers you have to install ippusbxd and follow the instructions in its README.md file, especially apply the Avahi patch.

**Comment by zdohnal** [comment]
I have mostly default cups-browsed.conf for 1.16.1 version, I have only:

BrowseRemoteProtocols dnssd cups
LocalQueueNamingRemoteCUPS RemoteName

because remote cups is 1.4.3. But I cannot see printer created even by cups-2.2.5 with debug log:

cups-browsed[13107]: Thu Dec 14 17:09:49 2017 Avahi Resolver: Service 'test-pro-f27 @ linux-2' of type '_ipp._tcp' in domain 'local' skipped, not a local service

**Comment by tillkamppeter** [comment]
Please run the command
```
avahi-browse -v -t -r --all
```
and post its output here. Thanks.

**Comment by zdohnal** [comment]
Server version: avahi 0.7; Host name: linux.local
E Ifce Prot Name                                          Type                 Domain
+   ens3 IPv6 test-pro-f27 @ linux-2                        Internet Printer     local
+   ens3 IPv4 test-pro-f27 @ linux-2                        Internet Printer     local
+   ens3 IPv6 test-pro-f27 @ linux-2                        Secure Internet Printer local
+   ens3 IPv4 test-pro-f27 @ linux-2                        Secure Internet Printer local
+   ens3 IPv6 test-pro-f27 @ linux-2                        UNIX Printer         local
+   ens3 IPv4 test-pro-f27 @ linux-2                        UNIX Printer         local
=   ens3 IPv6 test-pro-f27 @ linux-2                        Internet Printer     local
   hostname = [linux-2.local]
   address = [fe80::5054:ff:fe61:b46b]
   port = [631]
   txt = ["printer-type=0x6" "printer-state=3" "TLS=1.2" "UUID=1ce4ccce-b1b9-3b65-6849-f7f22b2b1cfd" "pdl=application/postscript" "product=Unknown" "priority=0" "adminurl=https://linux-2.local.:631/printers/test-pro-f27" "ty=Unknown" "rp=printers/test-pro-f27" "qtotal=1" "txtvers=1"]
=   ens3 IPv6 test-pro-f27 @ linux-2                        UNIX Printer         local
   hostname = [linux-2.local]
   address = [fe80::5054:ff:fe61:b46b]
   port = [0]
   txt = []
=   ens3 IPv6 test-pro-f27 @ linux-2                        Secure Internet Printer local
   hostname = [linux-2.local]
   address = [fe80::5054:ff:fe61:b46b]
   port = [631]
   txt = ["printer-type=0x6" "printer-state=3" "TLS=1.2" "UUID=1ce4ccce-b1b9-3b65-6849-f7f22b2b1cfd" "pdl=application/postscript" "product=Unknown" "priority=0" "adminurl=https://linux-2.local.:631/printers/test-pro-f27" "ty=Unknown" "rp=printers/test-pro-f27" "qtotal=1" "txtvers=1"]
=   ens3 IPv4 test-pro-f27 @ linux-2                        Internet Printer     local
   hostname = [linux-2.local]
   address = [192.168.122.61]
   port = [631]
   txt = ["printer-type=0x6" "printer-state=3" "TLS=1.2" "UUID=1ce4ccce-b1b9-3b65-6849-f7f22b2b1cfd" "pdl=application/postscript" "product=Unknown" "priority=0" "adminurl=https://linux-2.local.:631/printers/test-pro-f27" "ty=Unknown" "rp=printers/test-pro-f27" "qtotal=1" "txtvers=1"]
=   ens3 IPv4 test-pro-f27 @ linux-2                        UNIX Printer         local
   hostname = [linux-2.local]
   address = [192.168.122.61]
   port = [0]
   txt = []
=   ens3 IPv4 test-pro-f27 @ linux-2                        Secure Internet Printer local
   hostname = [linux-2.local]
   address = [192.168.122.61]
   port = [631]
   txt = ["printer-type=0x6" "printer-state=3" "TLS=1.2" "UUID=1ce4ccce-b1b9-3b65-6849-f7f22b2b1cfd" "pdl=application/postscript" "product=Unknown" "priority=0" "adminurl=https://linux-2.local.:631/printers/test-pro-f27" "ty=Unknown" "rp=printers/test-pro-f27" "qtotal=1" "txtvers=1"]
: Cache exhausted
: All for now

**Comment by Ste74** [comment]
Not sure if also this report is related:
https://forum.manjaro.org/t/printer-quit-today-after-updating/36610

**Comment by tillkamppeter** [comment]
Try putting a line
```
CreateIPPPrinterQueues All
```
and make sure not having any of
```
CreateIPPPrinterQueues No
CreateIPPPrinterQueues LocalOnly
```

**Comment by tillkamppeter** [comment]
@zdohnal, @Ste74, anyone of you still suffers this problem? Could you please try with the newest version of cups-filters?
I am closing this now, please re-open if you still have this problem.

**Comment by zdohnal** [comment]
I'll check with others on the bugzilla ticket - if they still can reproduce the issue, I'll reopen this one.
