### ISSUE TITLE
NewBrowsePollQueuesShared option?

### ISSUE THREAD

**Issue by ivanbaldo** [OpenPrinting/cups-filters#101]
Hello.
It would be useful to be able to re-export printers discovered by BrowsePoll options.
Like for example in a CUPS server connected to various VPNs resharing their printers without specifying them one by one but instead relying on CUPS servers in each VPN having access and sharing the printers at that location automatically.
Maybe the more correct way would be to fiddle with Avahi though... but some BrowsePoll's and a NewBrowsePollQueuesShared Yes option seems much easier.
Thanks!!!

**Comment by tillkamppeter** [comment]
Thank you for your feature request. The functionality is now added via Pull Request #218.
