### ISSUE TITLE
[driverless] HP Color LaserJet M281 cannot print test page

### ISSUE THREAD

**Issue by zdohnal** [OpenPrinting/cups-filters#104]
Hi!

we have report in Fedora 29 (cups-2.2.10, cups-filters-1.20.3) https://bugzilla.redhat.com/show_bug.cgi?id=1694797 , which is about driverless HP printer (dnssd backend, ppd created by cups-filters generator based on IPP comm) cannot print test page from GNOME control center, but other files does not do any problems. 

Jan (the reporter) provided logs 
[cups_journal.txt](https://github.com/OpenPrinting/cups-filters/files/3039712/cups_journal.txt) , ppd 
[HP-ColorLaserJet-MFP-M278-M281.ppd.txt](https://github.com/OpenPrinting/cups-filters/files/3039716/HP-ColorLaserJet-MFP-M278-M281.ppd.txt) , file, which goes to CUPS 
[jvlug-app.txt](https://github.com/OpenPrinting/cups-filters/files/3039717/jvlug-app.txt) and file which goes to the printer 
[jvlug-printout.txt](https://github.com/OpenPrinting/cups-filters/files/3039719/jvlug-printout.txt) . Input file looks good to me, but output of filters is missing all text and evince spits out:

'some font thing failed'

According logs there were 2 used filters, bannertopdf and pdftopdf, both from cups-filters, but pdfinfo tells that creator of pdf is cairo... I'm not sure if those filters calls cairo (IMO they do not).
Would you mind looking into it?

**Comment by tillkamppeter** [comment]
For me it looks like that when your print job runs the bannertopdf filter that the filter is not finding the fonts for the text part of the test page.
Extracting text from your output PDF file one sees that all the text is actually contained in the file. Also evince complains about fonts when displaying it and displays it without text then.
Then mention of cairo in the PDF file can come from the template PDF file (`default-testpage.pdf`), perhaps this was created with cairo.
Please check whether for the filters called by CUPS all fonts are available.
Your journal of CUPS unfortunately shows only the irrelevant lines. It filters exactly the lines coming from the job. You need the lines of the CUPS error_log (or the journal) which start with "`[Job `" followed by a number (which is the job number). Perhaps you did the call of `journalctl` in a wrong way.
Please try to get these lines to find out whether perhaps `bannertopdf` gives a warning or an error and post this here.

**Comment by zdohnal** [comment]
I tried the newest cups-filters and it works there - probably when bannertopdf was rewritten it was fixed.
