### ISSUE TITLE
Switch from imagemagick to graphicksmagick (or another library)

### ISSUE THREAD

**Issue by flying-sheep** [OpenPrinting/cups-filters#106]
Imagemagick is problematic since it hijacks a lot of command names (convert, import, …) and has quite a few security problems. There’s more here: http://www.graphicsmagick.org/

**Comment by tillkamppeter** [comment]
@sthibaul, I think, ImageMagick is only used by your Braille support. Could you convert this to GrapicsMagick?

**Comment by tillkamppeter** [comment]
@sthibaul, could you test the pull request #107? Thanks.

**Comment by tillkamppeter** [comment]
Unfortunately, we cannot do this change due to the fact that GraphicsMagick does not support all formats needed for our Braille embosser support. As ImageMagick is only used for the Braille embosser support and for nothing else in cups-filters this is no disadvantage for most users.
