### ISSUE TITLE
Printer being repeatedly automatically added by cups-filters

### ISSUE THREAD

**Issue by Bujiraso** [OpenPrinting/cups-filters#109]
As described by myself and another user on https://gitlab.gnome.org/GNOME/gnome-settings-daemon/issues/104, a printer with a null address that doesn't work keeps showing up in my Gnome control center.

![image](https://user-images.githubusercontent.com/1975771/56421345-6f097880-6278-11e9-9ca6-7004a792bda6.png)

From looking at my printer settings, I"m guessing this comes from the Bonjour Name that it's broadcasting which is "HP ENVY 4520 series [FB1E32]"

Additionally, when I try to add this printer from within Gnome Settings, it fails searching for drivers and does not add the printer.
I can use HP Device Manager to add it *to Gnome*, though, so it's 100% an issue with Settings' driver search and adding logic. I use the "Manual Connection" and JetDirect port 1 to get it working there.

Another detail about the automatic printer is that it always shows on the print prompt as a printer named "print" and has a status of "rejecting jobs" for me (at least per my memory). See attached:
![image](https://user-images.githubusercontent.com/1975771/56421361-80528500-6278-11e9-82e5-fe1d22289790.png)

Could someone give some pointers, as this looks defective due to:
1. Null address
2. Rejecting jobs
3. The printer works if I add it in different ways

If there's further configuration required for this printer to work through cups-filter, which I have not done, it should not be auto-publishing an incomplete configuration.

**Comment by debiantriage** [comment]
>   Another detail about the automatic printer is that it always shows on the print prompt as a printer named "print" and has a status of "rejecting jobs" for me (at least per my memory). See attached:

This is neither a CUPS nor a cups-filters issue. Please see

[https://gitlab.gnome.org/GNOME/gtk/issues/1509](url)

Regards,

Brian.

**Comment by tillkamppeter** [comment]
Closing as it is a GTK bug ...
