### ISSUE TITLE
configure: error: conditional "ENABLE_DRIVERLESS" was never defined.

### ISSUE THREAD

**Issue by paulmenzel** [OpenPrinting/cups-filters#111]
With cups-filters 1.22.5, configuring the build with the command below results in the error below.

    $ PREFIX=/package/tonerlow/cups-2.1.4 PKG_CONFIG_PATH="${PREFIX}/lib/pkgconfig" ./configure \
        --prefix=$PREFIX \
        --without-rcdir \
        --disable-avahi \
        --without-php \
        --disable-dbus \
        --with-cups-config=${PREFIX}/bin/cups-config
    […]
    checking for pdftops... /usr/bin/pdftops
    checking whether pdftops supports -origpagesizes... yes
    checking whether pdftops supports -r... yes
    checking for liblouis... no
    checking that generated files are newer than configure... done
    configure: error: conditional "ENABLE_DRIVERLESS" was never defined.
    Usually this means the macro was only invoked conditionally.

**Comment by paulmenzel** [comment]
Is that because of the old CUPS 1.2.4 version?

https://github.com/OpenPrinting/cups-filters/blob/cf508346bf7141f6fa07cf6e916550203486e1ba/configure.ac#L121-L124

**Comment by dheeraj135** [comment]
@paulmenzel I think issue is because of cups-config. Please verify your path of cups-config.

**Comment by paulmenzel** [comment]
@dheeraj135, no I do not think it is . It is because my CUPS version is older. The the two nested if conditions. The if statements/conditions should probably be reversed. Currently, if the CUPS version is too low, the variable will never be set.

**Comment by tillkamppeter** [comment]
Fixed in commit ec8f9266.
Thanks for the bug report.
