### ISSUE TITLE
Allow to disable backends

### ISSUE THREAD

**Issue by paulmenzel** [OpenPrinting/cups-filters#113]
It would be nice if the wanted backend list could be specified during configure time. That would have helped with issue https://github.com/OpenPrinting/cups-filters/issues/112, so that the backends *parallel* and *ieee1284* could have been disabled.

**Comment by tillkamppeter** [comment]
In issue #112 the backends do not build do to the "`-lcups`" missing in the linker command line. libcups is also needed by the filters though, so disabling the build of the backends had not made cups-filters build in that case.
