### ISSUE TITLE
Graceful/Consistent handling of zero-page jobs

### ISSUE THREAD

**Issue by tillkamppeter** [OpenPrinting/cups-filters#117]
It does not make much sense to send a file in a printable format but consisting of zero pages to a printer, but such jobs can easily appear, for example using the "page-ranges" option to select certain pages but the input file does not contain enough pages so that not even one page gets selected (like `page-ranges=3-4` on a one-page input file). Also errors in handling a PDF file manipulation utility can produce a PDF file not containing a single page.
If you print such a job the most consistent behavior would be that nothing gets printed on the printer (it is zero pages, not one empty page) and the job is taken from the queue without error.
To achieve this, all filters of cups-filters must behave appropriately, meaning that if the input data has zero pages that the output data must be a valid zero-page file in the output format of the filter and no input data at all needs to be considered as zero pages of input, too. Also a filter which is capable of removing pages from the job, like `pdftopdf`, needs to output a valid zero-page file if it removes all pages.
I have especially observed that `pdftopdf` generates illegal/broken PDF if one eliminates all the input pages via the `page-ranges` option. `gstoraster` and `mupdftoraster` produce zero bytes of output on a zero-page input file while `pdftoraster` produces a single blank page, which is all wrong. The correct output would be a zero-page Raster file which is simply only the 4-byte "magic string" of Raster, like "RaS2".
Also none of the filters accepts a totally empty file as input. It should be considered a zero-page file.
This problem was discovered when sending a PDF file with probably less than 3 pages and `page-ranges=3-4` to a print queue using HPLIP (`pdftopdf` -> `gstoraster` -> `hpcups` filter sequence) and the job caused an error (Issue #67).
Here the `hpcups` filter errored on totally empty (zero-byte) input. `pdftopdf` eliminated all pages and passed on broken PDF. Then `gstoraster` issued a warning and did not pass on any byte of output.
@smilingthax, @jberkenbilt, could you have a look into `pdftopdf` to make it always produce valid output, also in the zero-pages case? Could you also make it accepting totally empty input?
@tanmayanand44, could you take this also into account when working on the `pdftoraster` filter?

**Comment by tanmayanand44** [comment]
@tillkamppeter Sure, I will do include this.

**Comment by jberkenbilt** [comment]
Please let me know if there's anything for me to do here, but it's unlikely that there will be. I'm quite certain that QPDF works with zero-page files since that's what --empty produces. There may be some library calls that might throw exceptions on zero-page files, but certainly it would be possible to make pdftopdf handle that case without any qpdf library changes. But if there were some changes that would help, let me know.

**Comment by smilingthax** [comment]
Well, what pdftopdf outputs when there are no pages left, is basically the same thing qpdf --empty produces (except for three `%...comment...` lines at the start). At least, that's what I got here with a simple test.

The thing is, **the pdf spec does not seem to allow pdf's with no pages.** I don't have an exact quote right now, but e.g.see here: https://forums.adobe.com/thread/2011170 , or the output of gs or xpdf on such a file.
So, either we find an other way to completely discard a job, or we make sure, that every component of the chain (after pdftopdf) is able to deal with such non-standard pdfs...

Actually, we could even pass pass a "pdf"-file with 0 bytes down the chain, as that might be easier to detect by the wrapper that would normally call ghostscript/poppler (which WILL reject a zero-page pdf as invalid. OTOH gs seems be ok with 0-byte file; poppler will also reject that) and switch to special handling, like generating a magical raster file without help from the rasterizer.

BTW: Apple's own cgpdftopdf (used on Mac OS) will output a pdf with a single empty page (i.e. completely white), instead of a zero-page pdf, when only non-existing pages are selected as page-range.

**Comment by tillkamppeter** [comment]
Thanks for your answers.
I have checked now, the output of `qpdf --empty` makes Ghostscript producing the same warnings as the zero-page output of `pdftopdf`. So it seems that the PDF specs actually do not support zero-page files.
I do not like Apple's idea of outputtting a single blank page, as this makes the printer spin out a piece of paper which is actually not needed.
I suggest that ALL filters of cups-filters (at least the ones accepting multi-page file formats) should accept zero-byte input as a zero-page job and special-case it, skipping the normal filter process. Zero-page PDF should be output as zero bytes, zero-page Raster as the magic string only (to make `hpcups` happy). Zero-page PCLm should also be zero bytes as it is a special case of PDF. Zero-page PostScript could be only "%!" (the magic string of PostScript).
We only need to take into account zero-page jobs for data formats which are multi-page (PDF, PCLm, PostScript, Raster, ...), not for single-page formats (JPG, PNG, ...).

**Comment by tillkamppeter** [comment]
Multi-page data formats handled by cups-filters:
- Apple/CUPS/PWG Raster (zero-page output: 4-byte magic string only)
- PDF (zero-page output: 0 bytes)
- PostScript (zero-page output: Only "%!" or 0 bytes)
- PCLm (zero-page output: 0 bytes, as PDF)
- Plain text (zero-page output: 0 bytes)

Filters affected (taking at least one of the above formats as input and/or removing pages):

- rastertopdf
- gstopdf
- texttopdf
- pdftopdf
- pdftops
- pdftoraster
- gstoraster
- mupdftoraster

They all should detect zero-page input or at least zero-byte input before starting the core conversion process, to be able to skip it and directly produce zero-page output.

**Comment by tillkamppeter** [comment]
pdftoraster is done now, as pull request #127 by @tanmayanand44.

**Comment by tillkamppeter** [comment]
rastertopdf also handles zero-page input now, done by pull request #189.

**Comment by tillkamppeter** [comment]
texttopdf is fixed now in commit 2db65a0c8.

**Comment by tillkamppeter** [comment]
Added an additional fix for pdftoraster, as, though the output was correct, it exited with error code 1 on empty or zero-page input. Commit 89fa9a96.

**Comment by tillkamppeter** [comment]
Fixed rastertopdf (commit e926ab81): Its zero-page output was a zero-page PDF and not zero bytes. It also used fstat() to determine whether the input file is a zero-page raster or totally empty, thisonly works with a file on disk, not with stdin.

**Comment by tillkamppeter** [comment]
Thank you very much to everyone who has contributed here, but to assure that the zero-page job handling works in all situations, remember the following:
- On filters which output PDF or PCLm, a zero-page output file is a totally empty (zero bytes) file, NOT a PDF structure without pages
- If PDF or PCLm is the input format, the filter has to interpret both a completely empty (zero bytes) and a zero-page PDF structure (example attached) as zero-page input
- The input for any filter can be both a file on disk or standard input, so always use method which work with both files and stdin and test with both files and stdin.

**Comment by tillkamppeter** [comment]
mupdftoraster and rastertops done in pull request #191.

**Comment by tillkamppeter** [comment]
pdftopdf done in pull request #195.

**Comment by tillkamppeter** [comment]
pdftops done in pull request #196.

**Comment by tillkamppeter** [comment]
rastertoescpx and rastertopclx done in pull request #197.

**Comment by tillkamppeter** [comment]
gstoraster, gstopdf, and gstopxl done in pull request #198.

**Comment by tillkamppeter** [comment]
foomatic-rip done in pull request #200.

**Comment by tillkamppeter** [comment]
Now all filters which needed fixing for this as far as I found are actually fixed, so I am closing this issue as solved. Please re-open if I have forgotten a filter.
@JaiLuthra1, thanks a lot for your great work.
