### ISSUE TITLE
lpr 命令，打印中文或日文，出现串位覆盖现象

### ISSUE THREAD

**Issue by Dapeng-W** [OpenPrinting/cups-filters#135]
```
[root@localhost ~]# file -i test-print.txt 
test-print.txt: text/plain; charset=utf-8
[root@localhost ~]# cat test-print.txt 
文档打印测试
wendangdayinceshi
WENDANGDAYINCESHI
مرحبا
مرحبا بالعالم
こんにちは世界
Привет, мир
[root@localhost ~]# lpr -P Generic-PCL-6-PCL-XL test-print.txt 

然后打印出的中文或日文的第n个字符，左边会和其它行第n个英文字符的左侧边对其，又因为中文或日文的每个字符宽度要大于单个英文字符的宽度，所以当真正打印到纸上之后就会发现文字相互覆盖。
```

**Comment by tillkamppeter** [comment]
Could you please report bugs in English, thanks.

**Comment by Dapeng-W** [comment]
The p-th Chinese or Japanese characters printed on paper, the left side will be aligned with the left side of the p-th English character of other lines, 
mabe the width of each character of Chinese or Japanese is greater than the width of a single English character, 
when actually printing to paper After that, you will find that the text covers each other.

**Comment by Dapeng-W** [comment]
1，Write a few Chinese or Japanese characters in test-print.txt
2，Add a printer by system-config-printer
3，Use command lpr to print test-print.txt
4，see your printed paper，the text covers each other.

**Comment by Dapeng-W** [comment]
I upload two pictures on:  https://github.com/Dapeng-W/issues/tree/master/cups-filters/
you can make a comparison.

thank you.

**Comment by tillkamppeter** [comment]
texttopdf should take into account that Japanese or Chinese characters have the width of 2 standard latin characters when fixed width fonts are used. In terminal windows for example this is taken into account.

@smilingthax, could you have a look into this? Thanks.

**Comment by smilingthax** [comment]
Well, I can probably improve this. But I need to understand how to best determine whether a character is double width? It this just true for any character in a certain unicode range (e.g.) `U+3000 `to `U+9FFF`? Or does this somehow depend on the font?
For the similar problem of right-to-left text, the corresponding ranges used by texttopdf are configured via `charset/pdf.utf8` -- do we have to extend this format, or can we simply hardcode a certain range for double width, or am I required to check every character width from the used font?

**Comment by tillkamppeter** [comment]
I am not absolutely sure what defines with fixed-width UTF characters are double width. Not sure whether it is defined in the font or somewhere else.

**Comment by tillkamppeter** [comment]
@Dapeng-W and anyone else affected, should be fixed with pull request #199 which I have merged now. Please test.

**Comment by tillkamppeter** [comment]
I will consider this issue as solved now and close it. Please test and report here if you think that it is not solved and needs more changes. Thanks.

**Comment by tillkamppeter** [comment]
Can someone tell me which Debian/Ubuntu font packages I need to install to be able to convert the text file of the initial posting into PDF with the texttopdf filter?

**Comment by smilingthax** [comment]
For uming.ttc (AR PL UMing) it's `fonts-arphic-uming`.

**Comment by tillkamppeter** [comment]
@smilingthax, thanks, I have this installed, but the text file of the initial posting does not come out correctly.
My /usr/share/cups/charsets/pdf.utf-8: 
[pdf.utf-8.txt](https://github.com/OpenPrinting/cups-filters/files/4616397/pdf.utf-8.txt)
The text file: 
[cjk.txt](https://github.com/OpenPrinting/cups-filters/files/4616404/cjk.txt)

**Comment by tillkamppeter** [comment]
@smilingthax, any idea how I get CJK fonts working?

**Comment by smilingthax** [comment]
Sambhav Dusad @dsam82 did the implementation and (presumably successful) testing, he might/should be able to help here...

**Comment by dsam82** [comment]
In my system, the CJK fonts are taking double widths only and no overlaps are there.
I used the same text file as @tillkamppeter.
PDF file: 
[cjk.pdf](https://github.com/OpenPrinting/cups-filters/files/4718837/cjk.pdf)

**Comment by tillkamppeter** [comment]
@dsam82, @smilingthax, my problem is not that CJK characters appear with the wrong width but they  do not appear at all. It seems that on my Ubuntu 20.04 (Focal)  system the CJK fonts are not found. See my pdf.utf-8.txt in an earlier post here.

**Comment by tillkamppeter** [comment]
This is the PDF file which I get:
[texttopdf-out.pdf](https://github.com/OpenPrinting/cups-filters/files/4719131/texttopdf-out.pdf)

**Comment by dsam82** [comment]
@tillkamppeter, for installation of the fonts I used the same instructions given in the official Debian package [here](https://packages.debian.org/source/sid/fonts-arphic-uming).
Can you please confirm that uming.ttc is installed in `/usr/share/truetype/arphic` or `/uming` and all the .conf files are in `/etc/fonts/conf.avail/`.

You could maybe try reinstalling the fonts.

**Comment by tillkamppeter** [comment]
Here is all relevean output, package version, contained files, ... `uming.ttc` is in `/usr/share/fonts/truetype/arphic/` though.
I have also tried to re-install the package but the problem remains.
```
till@till-x1yoga:~/ubuntu/hplip/groovy$ dpkg -l fonts-arphic-uming
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name               Version                  Architecture Description
+++-==================-========================-============-==================>
ii  fonts-arphic-uming 0.2.20080216.2-10ubuntu2 all          "AR PL UMing" Chin>
till@till-x1yoga:~/ubuntu/hplip/groovy$ dpkg -L fonts-arphic-uming
/.
/etc
/etc/fonts
/etc/fonts/conf.avail
/etc/fonts/conf.avail/25-arphic-uming-bitmaps.conf
/etc/fonts/conf.avail/25-arphic-uming-render.conf
/etc/fonts/conf.avail/35-arphic-uming-aliases.conf
/etc/fonts/conf.avail/41-arphic-uming.conf
/etc/fonts/conf.avail/64-arphic-uming.conf
/etc/fonts/conf.avail/65-fonts-arphic-uming.conf
/etc/fonts/conf.avail/90-arphic-uming-embolden.conf
/etc/fonts/conf.d
/usr
/usr/share
/usr/share/doc
/usr/share/doc/fonts-arphic-uming
/usr/share/doc/fonts-arphic-uming/CONTRIBUTERS
/usr/share/doc/fonts-arphic-uming/Font_Comparison_ShanHeiSun_UMing.odt
/usr/share/doc/fonts-arphic-uming/Font_Comparison_ShanHeiSun_UMing.pdf.gz
/usr/share/doc/fonts-arphic-uming/KNOWN_ISSUES
/usr/share/doc/fonts-arphic-uming/NEWS.gz
/usr/share/doc/fonts-arphic-uming/README
/usr/share/doc/fonts-arphic-uming/README.Bitmap
/usr/share/doc/fonts-arphic-uming/changelog.Debian.gz
/usr/share/doc/fonts-arphic-uming/copyright
/usr/share/doc/fonts-arphic-uming/license
/usr/share/doc/fonts-arphic-uming/license/big5
/usr/share/doc/fonts-arphic-uming/license/big5/ARPHICPL.TXT
/usr/share/doc/fonts-arphic-uming/license/english
/usr/share/doc/fonts-arphic-uming/license/english/ARPHICPL.TXT.gz
/usr/share/doc/fonts-arphic-uming/license/gb
/usr/share/doc/fonts-arphic-uming/license/gb/ARPHICPL.TXT
/usr/share/doc/fonts-arphic-uming/license/zh_CN.utf-8
/usr/share/doc/fonts-arphic-uming/license/zh_CN.utf-8/ARPHICPL.txt.gz
/usr/share/doc/fonts-arphic-uming/license/zh_TW.utf-8
/usr/share/doc/fonts-arphic-uming/license/zh_TW.utf-8/ARPHICPL.txt.gz
/usr/share/fonts
/usr/share/fonts/truetype
/usr/share/fonts/truetype/arphic
/usr/share/fonts/truetype/arphic/uming.ttc
/etc/fonts/conf.d/25-arphic-uming-render.conf
/etc/fonts/conf.d/35-arphic-uming-aliases.conf
/etc/fonts/conf.d/41-arphic-uming.conf
/etc/fonts/conf.d/65-fonts-arphic-uming.conf
/etc/fonts/conf.d/90-arphic-uming-embolden.conf
till@till-x1yoga:~/ubuntu/hplip/groovy$ dpkg -L fonts-arphic-uming | grep uming.ttc 
/usr/share/fonts/truetype/arphic/uming.ttc
till@till-x1yoga:~/ubuntu/hplip/groovy$ dpkg -L fonts-arphic-uming | grep /etc/fonts/conf.avail/
/etc/fonts/conf.avail/25-arphic-uming-bitmaps.conf
/etc/fonts/conf.avail/25-arphic-uming-render.conf
/etc/fonts/conf.avail/35-arphic-uming-aliases.conf
/etc/fonts/conf.avail/41-arphic-uming.conf
/etc/fonts/conf.avail/64-arphic-uming.conf
/etc/fonts/conf.avail/65-fonts-arphic-uming.conf
/etc/fonts/conf.avail/90-arphic-uming-embolden.conf
till@till-x1yoga:~/ubuntu/hplip/groovy$ 
```

**Comment by smilingthax** [comment]
texttopdf (just like the original texttops) has an ASCII-Mode and an UTF-8 mode... 
The CUPS printing chain usually sets up the environment to activate the UTF-8 mode. This does not seem to happen for Till's pdf... 
For manual testing (without cups) I have to use something like this line:

    (export CHARSET=utf-8; ./texttopdf 1 hi_user there_title 1 "" testin.txt > testout.pdf)

**Comment by tillkamppeter** [comment]
@smilingthax, great, thanks, now it works for me.
Should texttopdf not be in UTF-8 mode by default, to be more versatile? Should we perhaps modify texttopdf to do so?

**Comment by smilingthax** [comment]
Hmm, the CHARSET environment variable directly causes the cups-datadir `/charsets/pdf.$CHARSET` file to be loaded, and fails, if it is not there. ASCII mode always works and does not require a file there. I did not change the original logic from texttops except for prefixing the charset filename with `pdf.` ... I don't know if defaulting to 'utf-8' when CHARSET is not set could have unexpected effects on the normal use via CUPS.

I'm not sure where and how CUPS sets up the environment. Technically the filters are not meant to be called by hand. There are more environment variables, e.g. CONTENT_TYPE, that will/can influence the filter.

I vaguely remember the existence of a commandline tool for calling the cups filter chain e.g. for testing purposes, that will setup the environment as expected for filters (?).

**Comment by tillkamppeter** [comment]
@smilingthax, the test tool of CUPS is `cupsfilter`. In our case we call it with
```
cupsfilter -i text/plain -m application/pdf cjk.txt > out.pdf
```
and indeed it sets (probably like CUPS does, too) the environment variable `CHARSET=utf-8` leading to correct output in `out.pdf`.
What I did wrong is to call the filter directly by hand, via
```
./texttopdf 1 1 1 1 '' ../cjk.txt > out.pdf
```
not realizing that it needs the environment variable set.

**Comment by tillkamppeter** [comment]
Succeeded to print `cjk.txt` also with the [snapped CUPS](https://github.com/OpenPrinting/printing-stack-snap) after [adding fonts-arphic-uming to it](https://github.com/OpenPrinting/printing-stack-snap/commit/5fed323b79d87e57867cd8870db87245febd903c).
Thanks, @smilingthax and @dsam82.

**Comment by Dapeng-W** [comment]
> texttopdf (just like the original texttops) has an ASCII-Mode and an UTF-8 mode...
> ...

two problems:
(1) `lpr -P <Printer> [jck.txt](https://github.com/OpenPrinting/cups-filters/files/4616404/cjk.txt)` 
the CJK text still covers each other on paper.

(2) CJK text garbled in testout.pdf (via: `export CHARSET=utf-8; /usr/lib/cups/filter/texttopdf 1 hi_user there_title 1 "" cjk.txt > testout.pdf`).
see [pic](https://github.com/Dapeng-W/issues/blob/master/cups-filters/CJK-texttopdf.jpg)

what should I do...

**Comment by Dapeng-W** [comment]
> texttopdf (just like the original texttops) has an ASCII-Mode and an UTF-8 mode...
> The CUPS printing chain usually sets up the environment to activate the UTF-8 mode. This does not seem to happen for Till's pdf...
> For manual testing (without cups) I have to use something like this line:
> 
> ```
> (export CHARSET=utf-8; ./texttopdf 1 hi_user there_title 1 "" testin.txt > testout.pdf)
> ```



    texttopdf (just like the original texttops) has an ASCII-Mode and an UTF-8 mode...
    ...

two problems:
(1) `lpr -P <Printer> jck.txt`
the CJK text still covers each other on paper.

(2) CJK text garbled in testout.pdf (via: export CHARSET=utf-8; /usr/lib/cups/filter/texttopdf 1 hi_user there_title 1 "" cjk.txt > testout.pdf).
see [pic](https://github.com/Dapeng-W/issues/blob/master/cups-filters/CJK-texttopdf.jpg)

what should I do...

**Comment by Dapeng-W** [comment]
？？

**Comment by omihara** [comment]
I also have seen this problem. Printing Japanese plain text in utf-8 encoding produces garbled characters ("Tofu" character) on Ubuntu 24.04, and also on Fedora 40.  It can be eased by installing fonts-arphic-uming package, but some of Japanese characters are still garbled becaucse fonts-arphic-uming is Chinese font.
This issue should be addressed by font configuration by the OS distributers, not cups-filters, I guess.
