### ISSUE TITLE
newly installed HP inkjet PPD missing default page order line

### ISSUE THREAD

**Issue by archenemies** [OpenPrinting/cups-filters#142]
Hello Mr. Till Kamppeter,

I think you did some recent work to get Inkjet printers to print pages in the correct order. (#47)

I noticed that when I recently installed CUPS on a new Raspbian system, that the default PPD for my HP inkjet printer is still configured to print documents in reverse.

I had to install the latest version of cups-filters from GitHub to get printing to work at all. Please let me know if something else is also out of date on Raspbian, I'm not sure which package contains the PPDs. I would be happy to try installing a new version of some package.

I'm attaching the PPD I used, which contains the lines I added in order to get pages to come out in the correct order.

Also, I noticed that I had 3 PPDs to choose from, all with the same name (see image below). However, they all seem to have the same contents.

![t](https://user-images.githubusercontent.com/12960503/63218292-2ff71100-c10c-11e9-8470-55b66fedb935.png)

Thank you.

[HP_Photosmart_Plus_B210_series.ppd.txt](https://github.com/OpenPrinting/cups-filters/files/3512542/HP_Photosmart_Plus_B210_series.ppd.txt)

**Comment by tillkamppeter** [comment]
Your PPD file is from HPLIP, my work on cups-filters only affects PPD files which are generated by cups-filters itself (for driverless IPP printing).
Also the repeated listing of your PPD is a problem of HPLIP as the PPD(s) here come from HPLIP.
Please report a bug [on HPLIP](https://launchpad.net/hplip/).

**Comment by archenemies** [comment]
Thank you. I have reported it [here](https://bugs.launchpad.net/hplip/+bug/1840576).
