### ISSUE TITLE
[Question] about "Unable to create PPD file: Printer does not support required IPP attributes or document formats."

### ISSUE THREAD

**Issue by ChoiChoongHo94** [OpenPrinting/cups-filters#143]
Hi. 
(I am not a native speaker. I will try my best to make my question clear, but please understand if there are any grammatical errors.)

If I get "Unable to create PPD file: Printer does not support required IPP attributes or document formats." from entering `driverless cat <driver URI>`, does it mean that this printer discovered by `driverless` don't support IPP?
If then, to set this printer up to `cups`, I must have the printer specific PPD file? 

I attach the output of above command.
[output.txt](https://github.com/OpenPrinting/cups-filters/files/3519221/output.txt)

**Comment by tillkamppeter** [comment]
The printer supports IPP as it has an IPP URI and it answers IPP requests, but what does not work with it is driverless IPP printing. According to its "document-format-supported" IPP attribute the only data format it supports for driverless printing is Apple Raster ("image/urf") which is a standard format for Apple's AirPrint, to print on the printer from an iOS device.
Unfortunately, the printer has a bug in the Apple Raster supoort. For a client to know in which resolution and color depth to send files in Apple Raster format, the standard requires the printer also to have the "urf-supported" IPP attribute. This attribute your printer seems to miss, making its Apple Raster support useless.

**Comment by ChoiChoongHo94** [comment]
then, if I set this printer, I must have the printer specific PPD file or driver (gutenprint, vendor-specific driver, etc.). right?

**Comment by debiantriage** [comment]
Would I be correct in thinking that, in the case of this printer, the Bonjour text record would not contain the "URF = " key? Perhaps  ChoiChoongHo94 would provide the output of

`avahi-browse -rt _ipp._tcp` ?

(The Samsung ULD package appears to be his route to printing easily).

**Comment by tillkamppeter** [comment]
Could you also post the output of
```
ipptool -tv <printer URI> get-printer-attributes.test > attrs.txt
```
Please attach the `attrs.txt` file to this bug report.

**Comment by ChoiChoongHo94** [comment]
Thank you for fast replies.

Here are the attachments.
```
avahi-browse -rt _ipp._tcp > resolve.txt
ipptool -tv <printer URI> get-printer-attributes.test > attrs.txt
```
[resolve.txt](https://github.com/OpenPrinting/cups-filters/files/3523446/resolve.txt)
[attrs.txt](https://github.com/OpenPrinting/cups-filters/files/3523447/attrs.txt)

**Comment by ChoiChoongHo94** [comment]
I have more question.

If a printer support `AirPrint`, is it safe to say that the printer also support `IPP Everywhere`?

**Comment by tillkamppeter** [comment]
If a printer supports AirPrint it does not automatically also support IPP Everywhere, but AirPrint is also a form of driverless IPP printing, like IPP Everywhere is, and so AirPrint printers do also print on modern Linux systems without need of a driver.
Unfortunately, your printer has no working implementation of AirPrint or any other driverless IPP printing standard. It supports Apple Raster (`image/urf`) but it misses important information in its DNS-SD record and in its IPP printer attributes which are needed for AirPrint. This means that yoiu can use this printer only the classic way with a driver.
If Samsung promises that it does AirPrint the printer has a serious firmware bug, you should check whether there is already a firmware update available.

**Comment by debiantriage** [comment]
>  If a printer support `AirPrint`, is it safe to say that the printer also support `IPP Everywhere`?

No, not at all.

Your resolve.txt indeed does not have a key in the text record beginning _urf=_;  its Bonjour broadcasts do not advertise an AirPrint-capable device. The attrs.txt backs up what Till has said already about the _urf-supported_ IPP attribute. This printer does not support AirPrint. IPP cannot get what it needs from the printer, so you cannot set up a print queue with the everywhere or driverless model (-m).

However, if you want to avoid using Samsung's non-free rastertospl filter you could try what follows.

- I have attached Samsung's PPD for the C420 as PPD.txt. Rename it to PPP.gz and uncompress it.
 - Change the *cupsFilter: line to have `"application/vnd.cups-raster 0 rastertopwg"`
 - Set up a print queue:
`lpadmin c420 -v ipp://SEC30CDA7C3387E.local:631/ipp/printer -E -P <PPD>`
 - Print to c420.

Cheers,

Brian.

[PPD.txt](https://github.com/OpenPrinting/cups-filters/files/3524964/PPD.txt)
