### ISSUE TITLE
cups-browsed: Unable to connect to local printers.

### ISSUE THREAD

**Issue by dheeraj135** [OpenPrinting/cups-filters#144]
The current cups-browsed in cups-filters ```HEAD``` is unable to connect to local printers.
I created a local printer with the command: ```ippserver x2```.
From the log file:
```
Sun Aug 18 22:29:05 2019 Establishing dummy connection to make CUPS create the temporary queue.
Sun Aug 18 22:30:08 2019 Unable to connect to destination.
```
cups-browsed times out trying to connect to the printer. But it still creates a queue with ```implicitclass``` backend. I tried printing to this queue. The cups-browsed log shows that it has received the print job but nothing is printed on the printer.

Log file: [cups-browsed-logs.txt](https://github.com/OpenPrinting/cups-filters/files/3533742/cups-browsed-logs.txt)
@deepak0405

**Comment by dheeraj135** [comment]
@deepak0405 Can you please attach the log files when you tried the same thing?

**Comment by deepak0405** [comment]
@dheeraj135 
I created a printer on the same machine using `ippserver x2 -d ~/Desktop` and ran the command `./cups-browsed -d -o CreateIPPPrinterQueues=All` on the latest cups-filter `1.25.3`. I was able to create the queue and the printed file was generated at the desktop. Please see whether I am missing something.

Log file : [localhost_ipp_network_printer.txt](https://github.com/OpenPrinting/cups-filters/files/3537922/localhost_ipp_network_printer.txt)

**Comment by dheeraj135** [comment]
@deepak0405 Thanks for testing this. Can you please verify the same for ippeveprinter? 
Command: ```ippeveprinter x2```

**Comment by deepak0405** [comment]
@dheeraj135 For ippeveprinter I am not able to reproduce this error. I am able to generate the print queue without any error but the print job never gets completed on my system. I am facing some different error.

Output of `ippeveprinter x3`
```
Listening on port 8000.
Ignored Avahi state 2.
192.168.42.237 POST /ipp/print
192.168.42.237 Continue
192.168.42.237 Get-Printer-Attributes successful-ok
192.168.42.237 OK
localhost Starting HTTPS session.
localhost Unable to encrypt connection: Server credentials not set.
localhost Starting HTTPS session.
localhost Unable to encrypt connection: Server credentials not set.
localhost Starting HTTPS session.
localhost Unable to encrypt connection: Server credentials not set.
localhost Starting HTTPS session.
```

**Comment by dheeraj135** [comment]
Thanks @deepak0405 for investigating this. If you are not able to reproduce this error, then I guess my installation is broken. I am closing the issue. By the way, you can resolve this error by using the command ```ippeveprinter x3 -K /var/tmp -n "localhost" ```.
