### ISSUE TITLE
QPDF 9 breaks cups-filters

### ISSUE THREAD

**Issue by lovesegfault** [OpenPrinting/cups-filters#151]
We ran across an issue on Gentoo where the recent bump to QPDF 9 broke cups-filters compilation. The error is related to a missing include to `memcpy` and was fixed with a simple patch, c.f. *https://bugs.gentoo.org/693498*.

Figured I'd propagate it upstream, cheers!

**Comment by tillkamppeter** [comment]
Already fixed in commit 1c80dbe62e6 after a hint in issue #134, but thanks anyway.
