### ISSUE TITLE
Does the LP command support direct printing of doc-formatted documents?

### ISSUE THREAD

**Issue by dreamtale90** [OpenPrinting/cups-filters#160]
I'm a newbie. I saw from ”Text support“ in readme that LP supports doc/docx format. But when I used the LP command to print the doc document, I was prompted: 
`lp: Unsupported document-format "application/msword".`
If it's docx format:
`lp: Unsupported document-format "application/vnd.openxmlformats-officedocument.wordprocessingml.document".`
Why is that?

**Comment by tillkamppeter** [comment]
Direct doc/docx file printing support is only available for Braille embossers, not for standard printers.
Braille embossers are usually printing only text, so it makes sense for them to extract the pure text from formatted text/mixed formats lice doc/docx. Also this way it is easier for blind people to get a doc/docx file which they get by-mail readable.
On standard printers one wants to have doc/docx files with all its fonts, graphics, images, ... which is much more complex, therefore it makes more sense to open it with an app like LibreOffice and print it from there (no problem for a person with normal vision).

**Comment by dreamtale90** [comment]
Thanks a lot.
I want to develop a program with c++ that can print documents in doc/docx format directly, or convert them into formats that are easy to print, such as ps/pdf format, and then print them.
Libreoffice is being studied, but it relies on so many things that it seems very difficult.
