### ISSUE TITLE
Error: Filter \"brftopagedbrf\" not found. after update to 1.20

### ISSUE THREAD

**Issue by FedericoYundt** [OpenPrinting/cups-filters#17]
Hi!
After update to version 1.20 from 1.19. My cups error log is spammed with `Filter \"brftopagedbrf\" not found.` message.

**Comment by tillkamppeter** [comment]
In the transition from 1.19.0 to 1.20.0 neither the Braille support nor the build system got touched, so none of these files should have disappeared.
Did you use the same installation method (distro package vs. built from source) for both versions?

**Comment by tillkamppeter** [comment]
@sthibaul, can you have a look whether with the current cups-filters versions is still all OK concerning Braille support?

**Comment by FedericoYundt** [comment]
I'm using package from Archlinux official repos. I've seen more people reporting similar issues:
https://forum.manjaro.org/t/hp-envy-5640-filter-failed/37234/9
https://bbs.archlinux.org/viewtopic.php?id=234037
The first link is even from time before 1.20 update

Here are distros package changelog:
https://github.com/manjaro/packages-extra/commits/master/cups-filter/PKGBUILD
https://git.archlinux.org/svntogit/packages.git/log/trunk?h=packages/cups-filters

**Comment by sthibaul** [comment]
Hello,

It seems the installation of that script was missing indeed, sorry :/ Here is a pull request to fix it
https://github.com/OpenPrinting/cups-filters/pull/18

**Comment by tillkamppeter** [comment]
I merged the PR now. Thank you very much.
