### ISSUE TITLE
Attribute differences

### ISSUE THREAD

**Issue by debiantriage** [OpenPrinting/cups-filters#171]
This is report is  an observation about the difference between the CUPS and cups-filters PPD generators rather than one about a bug in cupsfilters.

I have been working with a user at
https://ubuntuforums.org/showthread.php?t=2429221.

 The most relevant recent post is at
https://ubuntuforums.org/showthread.php?t=2429221&page=2&p=13902908#post13902908

The wf1 queue was set up with the driverless model. The wf2 queue used the everywhere model.

I understand fully that the cupsfilters PPD generator is intended to be in sync with the CUPs one, while diverging from it when it sees it as necessary. However, why the differences in the cupsPrintQuality/Print Quality and PageSize/Media Size attributes (particularly in regard to borderless)?

Explaining this to a user is not the easiest of tasks.

-- 
Brian.

**Comment by debiantriage** [comment]
https://ubuntuforums.org/showthread.php?t=2429221&page=3&#23

Regards,

Brian.

**Comment by tillkamppeter** [comment]
This printer (EPSON WF-2630) seems to have the same problem as the Epson ET-7700 of Pull request #168, claiming to accept PWG Raster input but actually not printing it.
For some reason CUPS creates a PPD where the printer gets Apple Raster whereas the cups-filters PPD lets PWG Raster go to the printer.

**Comment by tillkamppeter** [comment]
The fact that some printers report to support PWG Raster but actually printing in this format does not work caused also the CUPS issue apple/cups#5238. Here a Canon Pixma Pro 10 showed this problem. So an actual fix for at least getting your printer working again is to modify the PPD generator to prioritize Apple Raster against PWG Raster if both are supported, as the fix of the CUPS issue does with the PPD generator in CUPS.
As a workaround until we have actually done this in cups-filters, you simply proceed as described in [this comment in the CUPS issue](https://github.com/apple/cups/issues/5238#issuecomment-372440413). This will at least get you back printing.
The differences in the choices of the options are an independent issue which we will look into later.

**Comment by tillkamppeter** [comment]
I have fixed the Apple Raster/PWG Raster problrm now, following CUPS in preferring Apple Raster if both are supported, commit 80f87b0a.

**Comment by tillkamppeter** [comment]
Discrepancies in the option choices:
- CUPS only gives standard page sizes, cups-filters has borderless sizes added.
- CUPS has "draft" quality added, cups-filters has only "normal"
- cups-filters gives "4" and not "normal" as print quality choice name.

**Comment by tillkamppeter** [comment]
The discrepancy in the page sizes is already solved. Current cups-filters is correct, listing also borderless sizes, CUPS has it correct at least from 2.3.x on, as I have tested with the 2.2.12 of Ubuntu 19.10 and also tested with an LD_PRELOAD of the libcups of 2.3.x from the CUPS GitHub. The latter also shows the borderless sizes, the former not.
You can easily see in the output of `ipptool` that a printer supports borderless printing, even if the "media-col-database" attribute is not listed. If you get margin info like
```
        media-left-margin-supported (1setOf integer) = 0,300
        media-right-margin-supported (1setOf integer) = 0,300
        media-top-margin-supported (1setOf integer) = 0,300
        media-bottom-margin-supported (1setOf integer) = 0,300
```
having zero and a non-zero value for each nargin, it means that the printer has a standard mode and a borderless mode and so at least for some page sizes borderless printing is supported. The actual page sizes which have a borderless version are found via the "media-col-database".

**Comment by tillkamppeter** [comment]
The fact that CUPS adds a "draft" print quality but cups-filters not is that CUPS not only adds "draft" if it is listed in the "print-quality-supported" attribute but also if the lowest resolution is even. in the latter case the "draft" mode is simply using half the lowest resolution. I am in doubt whether this always actually works and therefore I do not overtake it into cups-filters.

**Comment by tillkamppeter** [comment]
I have fixed the choice names of the "cupsPrintQuality" option now to be "Draft",  "Normal",  and "High", as CUPS also uses (commit 47b9adab6).
So now all differences should be fixed or explained and you should be able to print. So I am closing this issue.
