### ISSUE TITLE
cupsGetDests's behaviour is difference between CUPS2.2.10 & CUPS2.2.12

### ISSUE THREAD

**Issue by tangyanli** [OpenPrinting/cups-filters#174]
Assume the default printer name is set as below:
/etc/cups/printers.conf: PrinterA
~/.cups/lpoptions: PrinterB

When use the cupsGetDests to get the default printer name:
Ubuntu19.04 (CUPS2.2.10): The PrinterB's dest->is_default = 1
Ubuntu19.10 (CUPS2.2.12): The PrinterA's dest->is_default = 1

I tried to analyze the code, is the cups_enum_dests()'s logic changed?
(1) data.def_name stores the system default name ("PrinterA")
(2) Get the use default name from ~/.cups/lpoptions ("PrinterB")
(3) According the data.def_name ("PrinterA") to set the dest->is_default = 1

[getDefaultPrinter.txt](https://github.com/OpenPrinting/cups-filters/files/3840146/getDefaultPrinter.txt)

**Comment by tillkamppeter** [comment]
This has nothing to do with cups-filters. It is a problem of CUPS itself. Please post this issue [on the GitHub of CUPS](https://github.com/apple/cups/issues).

**Comment by tangyanli** [comment]
This issue is shift to https://github.com/apple/cups/issues/5683
