### ISSUE TITLE
HP Designjet T1100 Impossible to print landscape - always autorotate

### ISSUE THREAD

**Issue by NicoHood** [OpenPrinting/cups-filters#176]
Hi,
I've got a HP Designjet T1100 with a ~1m wide roll of paper. No matter what I select in the setting, it always prints the page as portait, no landscape is possible.

### Example:
```
Current situatuion:
+++++-------
+   +      |
+   +      |
+   +      |
+++++      |
|          |
|          |
|          |
~~~~~~~~~~~~ -> infinite roll of paper


What I want to do:
+++++++++---
+       +  |
+++++++++  |
|          |
|          |
|          |
|          |
|          |
~~~~~~~~~~~~ -> infinite roll of paper
```

I also tried to disable "Auto Rotate and Center" In the "Page Handling" Tab of the print setting.

The only partly related issue I could find was this one:
https://github.com/OpenPrinting/cups-filters/issues/52

I am also not sure if this is an issue of this repository, if I am wrong it would be nice to know where I need to report this bug. Thanks!

**Comment by tillkamppeter** [comment]
Could you please attach your PPD file (from /etc/cups/ppd/, rename the file adding a `.txt` file name extension for attaching here) and tell which settings, especially page size and also image printing settings (`fit-to-page`, `fitplot`, ...) you have used?
Could you also attach your input file (PDF, JPG, or whatever it was)? Did you print from the command line or out of an application? Which application and with which print dialog settings?

**Comment by NicoHood** [comment]
I used evince to print the pdf files. I am not allowed to share the files I wanted to print, but any normal a4 pdf will work as well (The paper is a 1m wide roll, but you can simply test with normal a4). I was not able to rotate it to landscape. I tried portrait and landscape setting.
![Screenshot from 2019-11-19 23-30-36](https://user-images.githubusercontent.com/6888294/69192349-aac53300-0b24-11ea-9c1c-3b5cc6f53421.png)
![Screenshot from 2019-11-19 23-30-45](https://user-images.githubusercontent.com/6888294/69192350-aac53300-0b24-11ea-8790-045bd2668838.png)


### PPD file:
[HP-DesignJet-T1100.ppd.txt](https://github.com/OpenPrinting/cups-filters/files/3866356/HP-DesignJet-T1100.ppd.txt)

**Comment by tillkamppeter** [comment]
Have you already tried to print with the paper size selection "A4.Transverse"/"A4 Long Edge"? Does this work for you?
Would be nicer if it works automatically, but this would be at least a workaround.

**Comment by debiantriage** [comment]
It seems you have, say, an A4 portrait PDF with text parallel to the short edge. You want to rotate the PDF 90 degrees and still have the text parallel to the short edge.

The Portrait and Landscape options in applications do not always do what you think they do and, furthermore, different applications attach different meanings to the two words. For example, evince produces a PDF with text parallel to the long edge when given the Landscape option. This is not what you want.

[https://wiki.debian.org/CUPSPdfToPdf#The_Landscape_and_Portrait_Options_in_Applications](url)

I would set up a queue with _landscape_ and _nopdfautorotate_ options and print to it with evince set to Portrait.

How do you go on?

Regards,

Brian.

**Comment by NicoHood** [comment]
There is no such option "A4.Transverse"/"A4 Long Edge" in my print setting.

**Comment by tillkamppeter** [comment]
@NicoHood, your PPD file which you attached on Nov 19 contains the "A4.Transverse"/"A4 Long Edge" for the page size. If it does not appear in print dialogs, try to print via the following command line
```
lp -d <YOUR PRINTER> -o PageSize=A4.Transverse <PDF FILE>
```
Replacw `<YOUR PRINTER>` by the print queue name and `<PDF FILE>` by the file name of one of your A4-sized PDF files.

**Comment by tillkamppeter** [comment]
I have checked further and if you print via command line as I described in the previous comment the file should come out landscape-oriented as desired. So there is no bug in cups-filters.
I have also created a CUPS queue using your PPD file and then opened the print dialog of evince, the GTK print dialog, and this dialog makes a complete mess from your PPD file. The list of paper sizes contains each standard size twice, not one with "Long Edge" added as one would expect. One could now try out whether one of the two is the landscape one (should be), but both behave the same, the page size preview at the bottom does not change. There are also even some completely strange entries in the list. So the bug is in the GTK dialog.
Please try whether it works better in LibreOffice or in Qt applications (like the PDF viewer Okular).
