### ISSUE TITLE
Problem with driver for Epson SX215 (SX210)

### ISSUE THREAD

**Issue by johcarsmi** [OpenPrinting/cups-filters#178]
When printing labels of Avery type J8163 (7x2) the print moves up the label about 1mm on each row of labels down the page. Can this be corrected please? 
Please advise if this is not the correct place to raise this issue.

Thanks John

**Comment by tillkamppeter** [comment]
This is probably a problem of the printer driver. Which printer driver are you using?

**Comment by johcarsmi** [comment]
Not a problem with the driver. The default configuration scaled page to fit rather than print designed size. The label document was shrunk when printed. Changed the setting to print actual size - problem cured.
