### ISSUE TITLE
cups-browsed remote queue no longer working

### ISSUE THREAD

**Issue by jroldroyd** [OpenPrinting/cups-filters#182]
Following system upgrades on both server and client systems, a "it just worked" setup no longer works!

Setup is a Canon MX922 printer connected via USB to a server now running FreeBSD-12.1 with cups-2.2.12 and gutenprint-5.3.3.  The printer works fine when printing from the server.  Previously, the server was FreeBSD-12.0 with cups-2.2.10 and gutenprint-5.2.10 which also worked fine.

Client systems are also now running FreeBSD-12.1.  Cups is cups-2.2.12 and cups-browsed is from cups-filters-1.25.12 and gutenprint-5.3.3.  Printing using the queue that was auto-installed by cups-browsed no longer works.  However, creating a local queue for the remote printer does work.  Previously, with cups-2.2.11, cups-filters-1.25.5_1 and gutenprint-5.2.14, printing using the cups-browsed queue just worked.

OK, so on the client systems, when I create a local queue for the remote printer, it gets a PPD from ippeve.ppd and the nickname "MX920 series - CUPS+Gutenprint v5.3.3 - IPP Everywhere".  As I said, this works.  Looking at the log, the jobs are sent from the clients to the server using the ipps backend.

But, when I delete that queue and run cups-browsed, it creates a queue with a PPD from drvless.ppd and gets a nick "Canon MX920 series - CUPS+Gutenprint v5.3.3, driverless, cups-filters 1.25.12".  Jobs sent to this queue stall in the client's /var/spool/cups/tmp and never make it to the server.  Looking at the logs, jobs are spooled using the implicitclass backend which says it will then run the IPP backend, but the log shows:

D [12/Dec/2019:13:15:22 -0500] [Job 428] Printer supports output formats: pdf
D [12/Dec/2019:13:15:22 -0500] [Job 428] Using following CUPS filter chain to convert input data to the PDF format: gziptoany
D [12/Dec/2019:13:15:22 -0500] [Job 428] argv[0]=\"implicitclass://mx922/\"
D [12/Dec/2019:13:15:22 -0500] [Job 428] argv[1]=\"428\"
D [12/Dec/2019:13:15:22 -0500] [Job 428] argv[2]=\"root\"
D [12/Dec/2019:13:15:22 -0500] [Job 428] argv[3]=\"(stdin)\"
D [12/Dec/2019:13:15:22 -0500] [Job 428] argv[4]=\"1\"
D [12/Dec/2019:13:15:22 -0500] [Job 428] argv[5]=\"job-originating-user-name=root finishings=3 job-cancel-after=10800 job-priority=50 job-sheets=none,none number-up=1 job-uuid=urn:uuid:baa3917e-fb5e-31c8-6fe6-7
31a8ee466c6 job-originating-host-name=localhost date-time-at-creation= date-time-at-processing= time-at-creation=1576174521 time-at-processing=1576174521 job-impressions-completed=0 output-format=pdf Resolution
=601x600dpi page-logging=on\"
D [12/Dec/2019:13:15:22 -0500] [Job 428] argv[6]=\"/var/spool/cups/tmp/08fe75df33662\"
D [12/Dec/2019:13:15:22 -0500] [Job 428] gziptoany (PID 36840) started.
D [12/Dec/2019:13:15:22 -0500] cupsdMarkDirty(---J-)
D [12/Dec/2019:13:15:22 -0500] cupsdSetBusyState: newbusy="Printing jobs and dirty files", busy="Printing jobs and dirty files"
D [12/Dec/2019:13:15:22 -0500] cupsdMarkDirty(---J-)
D [12/Dec/2019:13:15:22 -0500] cupsdSetBusyState: newbusy="Printing jobs and dirty files", busy="Printing jobs and dirty files"
D [12/Dec/2019:13:15:22 -0500] [Job 428] Set job-printer-state-message to "gziptoany (PID 36840) started.", current level=INFO
D [12/Dec/2019:13:15:22 -0500] cupsdMarkDirty(----S)
D [12/Dec/2019:13:15:22 -0500] cupsdSetBusyState: newbusy="Printing jobs and dirty files", busy="Printing jobs and dirty files"
D [12/Dec/2019:13:15:22 -0500] cupsdMarkDirty(----S)
D [12/Dec/2019:13:15:22 -0500] cupsdSetBusyState: newbusy="Printing jobs and dirty files", busy="Printing jobs and dirty files"
D [12/Dec/2019:13:15:22 -0500] [Notifier] state=3
D [12/Dec/2019:13:15:22 -0500] [Notifier] JobProgress
D [12/Dec/2019:13:15:22 -0500] [Notifier] state=3
D [12/Dec/2019:13:15:22 -0500] [Notifier] state=3
D [12/Dec/2019:13:15:22 -0500] [Notifier] state=3
D [12/Dec/2019:13:15:22 -0500] [Notifier] PrinterStateChanged
D [12/Dec/2019:13:15:22 -0500] [Job 428] gziptoany (PID 36840) exited with no errors.
D [12/Dec/2019:13:15:22 -0500] cupsdMarkDirty(---J-)
D [12/Dec/2019:13:15:22 -0500] cupsdSetBusyState: newbusy="Printing jobs and dirty files", busy="Printing jobs and dirty files"
D [12/Dec/2019:13:15:22 -0500] [Job 428] Set job-printer-state-message to "gziptoany (PID 36840) exited with no errors.", current level=INFO
D [12/Dec/2019:13:15:22 -0500] cupsdMarkDirty(----S)
D [12/Dec/2019:13:15:22 -0500] cupsdSetBusyState: newbusy="Printing jobs and dirty files", busy="Printing jobs and dirty files"
D [12/Dec/2019:13:15:22 -0500] cupsdMarkDirty(----S)
D [12/Dec/2019:13:15:22 -0500] cupsdSetBusyState: newbusy="Printing jobs and dirty files", busy="Printing jobs and dirty files"
D [12/Dec/2019:13:15:22 -0500] [Job 428] The filtered output of pdftoippprinter is written to file /var/spool/cups/tmp/08fe75df337e0
D [12/Dec/2019:13:15:22 -0500] [Job 428] Started IPP Backend with pid: 36841
D [12/Dec/2019:13:15:22 -0500] [Notifier] state=3
D [12/Dec/2019:13:15:22 -0500] [Notifier] JobProgress
D [12/Dec/2019:13:15:22 -0500] [Notifier] state=3
D [12/Dec/2019:13:15:22 -0500] [Notifier] state=3
D [12/Dec/2019:13:15:22 -0500] [Notifier] PrinterStateChanged
D [12/Dec/2019:13:15:22 -0500] [Notifier] state=3
D [12/Dec/2019:13:15:22 -0500] [Job 428] The IPP Backend exited with the status 0
D [12/Dec/2019:13:15:22 -0500] [Client 93] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
D [12/Dec/2019:13:15:22 -0500] [Client 93] Closing connection.
D [12/Dec/2019:13:15:22 -0500] cupsdSetBusyState: newbusy="Printing jobs and dirty files", busy="Printing jobs and dirty files"
D [12/Dec/2019:13:15:22 -0500] [Job 428] PID 36839 (/usr/local/libexec/cups/backend/implicitclass) exited with no errors.
D [12/Dec/2019:13:15:22 -0500] [Job 428] time-at-completed=1576174522

The "HTTP_STATE_WAITING Closing for error 32 (Broken pipe)" suggests something went wrong.  Nothing at all appears in the server's logs.

The full client log is [here](http://opal.com/jr/cups-browsed/20191212131552-debug.log).

**Comment by jroldroyd** [comment]
In addition, the log from cups-browsed is [here](http://opal.com/jr/cups-browsed/20191212133437-debug-browsed.log).

**Comment by jroldroyd** [comment]
OK, I have solved this.  In backend/implicitclass.c, there is a hard-coded path to the IPP progrram which is not valid on FreeBSD.  However, the code that performs the execv() has two additional errors: it does not NULL-terminate the argv_nt[] array and it also does not have an error exit() call after the execv() for the precise situation that the execv() fails.

A patch is [here](http://opal.com/jr/cups-browsed/implicitclass.c.diff).

The path change is presumably FreeBSD-specific and we can handle that in our port framework.  However, the remaining parts of this patch apply to all systems and should be incorporated here.

**Comment by tillkamppeter** [comment]
Thank you for the investigations and the patch, but with my work on fixing issue #163 I already have discovered this problem and fixed it with commit 547aa22a14, commit 893c5f81cc, and commit d14f353ec4. So I am closing this issue here.

**Comment by jroldroyd** [comment]
The commits applied for this do not include any fix for the argv_nt[] array size (should be 8, not 7) and setting of argv_nt[7] = NULL.

This still needs to be added.  As it is, execv() is being called with an argv_nt arg that is not null terminated, which is an error.

See my existing patch [here](http://opal.com/jr/cups-browsed/implicitclass.c.diff) for the needed changes.

**Comment by tillkamppeter** [comment]
Fixed in commit 6184b9856f. Thank you very much.

**Comment by hyegeek** [comment]
Thanks. Tested and submitted to the gentoo bug site.
