### ISSUE TITLE
ppdgenerator: test if default color models are available in ipp attribute

### ISSUE THREAD

**Issue by zdohnal** [OpenPrinting/cups-filters#186]
Hi,

I encountered the issue with ppdgenerator in CUPS https://github.com/apple/cups/issues/5713 and since cupsfilters ppdgenerator is nearly the same, I'm reporting this here too.

The issue is that ppdgenerator has a sequence of ipp attributes when it comes to generating color models. They seem to be sorted by preference. So when a printer answers to get-printer-attributes request with a response, which contains preferred attribute but it misses several default color models, ppdgenerator uses it.

In my case, my Canon printer returns pwg-raster-document-type-supported with only srgb_8, so final ppd does not have any gray color model. (get-printer-attributes result log and final ppd are in cups issue)

I think it could be solved by creating 'verify' function, which will be called as part of those 'if' statements:

```
  if ((attr = ippFindAttribute(response, "urf-supported", IPP_TAG_KEYWORD)) ==
      NULL)
    if ((attr = ippFindAttribute(response, "pwg-raster-document-type-supported",
                                 IPP_TAG_KEYWORD)) == NULL)
      if ((attr = ippFindAttribute(response, "print-color-mode-supported",
                                   IPP_TAG_KEYWORD)) == NULL)
```

Other approach would be to scan the attribute in separated function and return a structure of color models for ipp attribute which provided the most info.

@tillkamppeter what do you think about it?

**Comment by tillkamppeter** [comment]
It is possible that in different PDLs (AppleRaster/URF, PWG Raster, PDF, ...) the range of available choices for each option (Color Model, Resolution, ...) is different, for example the printer printe grayscale only in PDF but not in Apple Raster.
So I want to ask you to make a test:
Stop the CUPS daemon, then edit your printer's PPD file (in `/etc/cups/ppd/`), adding a new entry (line) to the "Color Model" option. Copy the one line for SRGB_8 and edit it for the desired mode, like Gray_8. You can add more than one line for more modes. Run the `cupstestppd` command to check whether you did not mis-type. Now start the CUPS daemon again. Try to print in your newly created modes. Do you get correct printouts?

**Comment by zdohnal** [comment]
@tillkamppeter I probably explained the issue in bad way. I already tested if the printer works in grayscale after adding gray color model - it works.
What I wanted to point out is the driverless binary does not create any gray color model (probably due printer firmware bug), because pwg-raster-document-type-supported ipp attribute only mentions srgb_8, which is IMO insufficient for user (users usually want grayscale printing, colored in some cases if it is available).
I'm willing to implement the fix, so I wanted your opinion how it should look like.

What came to my mind is to use the first ipp attribute which mentions support for at least one gray color model and (if device is a color printer) at least one colored model.

What do you think?

**Comment by tillkamppeter** [comment]
I understood what you mean, the generated PPDs do not show all available color mode, so I already thought about taking the color modes from the "richest" keyword or merging the results of all keywords.
My hesitation was that perhaps the printer supports in the Apple Raster PDL only the ones reported by "urf-supportef", in PWG Raster only the ones reported by "pwg-raster-document-type-supported", ... So with my question I wanted you to test whether all modes, reported by any keywords, can be used in all PDLs. If not, one would have to choose the "richest" PDL, the one whose keyword reports most color modes, or in each job choose the PDL by the user-requested color mode (would need a "pdftomultipdl" filter).
As you already have done this test and found out that you can actually print in a color mode which is only reported for another PDL than the one you are using we can probably go the way of merging all keyword's results and then print in any supported PDL. Please do further, systematic tests in this direction.
Note also that several printers report that they do PWG Raster but in reality PWG Raster does not work with them. Therefore I have put a priority order of PDF, Apple Raster, and after that PWG Raster, meaning PWG Raster is only used when the printer supports neither PDF nor Apple Raster. I did not select PDLs by the "richness" of their keywords.
Patches for the PPD generators of both cups-filters and CUPS with option choices from merged keyword results are welcome.

**Comment by zdohnal** [comment]
@tillkamppeter 
> My hesitation was that perhaps the printer supports in the Apple Raster PDL only the ones reported by "urf-supportef", in PWG Raster only the ones reported by "pwg-raster-document-type-supported", ... So with my question I wanted you to test whether all modes, reported by any keywords, can be used in all PDLs. 

If I understand the current code correctly, chosen PDL does not have any impact on final Color Model in ppd - f.e. definition of color model Gray:

```
*ColorModel Gray/%s: \"<</cupsColorSpace 18/cupsBitsPerColor 8/cupsColorOrder 0/cupsCompression 0>>setpagedevice\"\n
```
is the same for all keywords which represent 'Gray' among all PDLs (sgray_8 for pwg, w8 for urf, monochrome for print-color-mode-supported...).

In this case, I do not know why the print job has to be filtered to other PDL or multiPDL due color model (f.e. Gray), which is the same for all PDLs.

> As you already have done this test and found out that you can actually print in a color mode which is only reported for another PDL than the one you are using we can probably go the way of merging all keyword's results and then print in any supported PDL. Please do further, systematic tests in this direction.

I tested only ColorModel Gray since it was missing and it seems to be basic option in my opinion - I did not test it for different PDLs because of 2 reasons:

1) I do not know how to set it in ppd file
2) color models do not care about PDLs - means 'Gray' color model is the same regardless of PDL 

> Note also that several printers report that they do PWG Raster but in reality PWG Raster does not work with them. Therefore I have put a priority order of PDF, Apple Raster, and after that PWG Raster, meaning PWG Raster is only used when the printer supports neither PDF nor Apple Raster.

The priority order for creating color model entry according to ppdgenerator.c:

1. URF
2. PWG
3. print-color-mode-supported
4. output-mode-supported

It does not comply to mentioned sequence... maybe it was forgotten to change? Because if print-color-mode-supported is before PWG, the printing works correctly (all color models which the printer tells  are working).

> Patches for the PPD generators of both cups-filters and CUPS with option choices from merged keyword results are welcome.

Thank you! I wanted to coordinate with you about the correct fix before I implement anything.

**Comment by zdohnal** [comment]
If you want the solution with prioritizing print-color-mode-supported over pwg, here is the pull request #188

**Comment by tillkamppeter** [comment]
@zdohnal, I have merged the pull request. Thank you very much. It seems that manufacturers do not implement well the support for PWG Raster. Once there are printers claiming to accept PWG Raster and they do not print this format and there are also printers not listing all their color modes in the "pwg-raster-document-type-supported" attribute.
Note also that the lines in the ColorModel options (and also in most other options) doe not contain code for the PDL actually used. The filters read these lines and generate the PDL output according to the selection.
By the way, with which printer are you testing? I am wondering that it does not support AirPrint (no "urf-supported") but PWG Raster (has "pwg-raster-document-type-supported"). Could you attach the output of
```
ipptool -tv <URI> get-printer-attributes-2.0.test > attrs.txt
```

**Comment by zdohnal** [comment]
[get-printer-attributes-2.0.out.txt](https://github.com/OpenPrinting/cups-filters/files/4070920/get-printer-attributes-2.0.out.txt)
No image/urf in document-format-supported (available application/octet-stream,image/jpeg,application/pdf) or any urf-supported keyword at all, pwg-raster-document-type-supported has only srgb_8 value, which is insufficient (with previous ppdgenerator code) when you want to print grayscale (it is color device).
The model is Canon ImageRunner Advance C255/355. But similar issue has @bocekm in mentioned CUPS issue, which has different Canon model.

**Comment by tillkamppeter** [comment]
Thank you very much. This is somewhat strange, as there are PWG-Raster-specific keywords but no PWG-Raster under the supported document formats.

**Comment by debiantriage** [comment]
This was an interesting discussion; sorry to join it late. However, I am intrigued by _get-printer-attributes-2.0.out.txt_ not having any reference to image/urf. How does the printer get to advertise it is AirPrint capable (which Canon say it is)?

Cheers,

Brian.
