### ISSUE TITLE
EPSON XP-5100 Prints Blue Text as "Pink text"

### ISSUE THREAD

**Issue by HerrUntermoser** [OpenPrinting/cups-filters#192]
I use Linux Mint 19.3 but I had the same problem on Fedora and Manjaro. The CUPS Driver for Epson XP 5100 Series (WLAN Model) prints "Blue" Text as "Pink" Text from every Dokument regardless if it comes from the Browser or Office Suite or Texteditor.

**Comment by tillkamppeter** [comment]
Could you attach the PPD file of your print queue (from the `/etc/cups/ppd/` directory (rename the file to have a `.txt` extension when attaching it here).
Could you also run the command
```
driverless
```
to get the URIs (one per line) of all available driverless-capable printers. Find the one of your Epson. Then run
```
ipptool -tv URI get-printer-attributes-2.0.txt > attrs.txt
```
replacing `URI` by the URI of your Epson. Please also attach the `attrs.txt` file.

**Comment by HerrUntermoser** [comment]
[Epson-XP-5100.txt](https://github.com/OpenPrinting/cups-filters/files/4108359/Epson-XP-5100.txt)

Running
ipptool -tv ipp://EPSON3078C9.local:631/ipp/print get-printer-attributes-2.0.txt > attrs.txt
returns
ipptool: Unable to open test file get-printer-attributes-2.0.txt - File or Directory not found

**Comment by tillkamppeter** [comment]
Please run
```
ipptool -tv ipp://EPSON3078C9.local:631/ipp/print get-printer-attributes.txt > attrs.txt
```
instead.

**Comment by HerrUntermoser** [comment]
Same return. Both files doesn't exist on my Linux Mint

**Comment by tillkamppeter** [comment]
Do you have the package "cups-ipp-utils" installed?

**Comment by HerrUntermoser** [comment]
Apt says: YES
But the error was elsewhere.
The correct name is: "get-printer-attributes.test"
My mistake, I could've figured out earlier to just look for "get-printer-attribute" ...
[attrs.txt](https://github.com/OpenPrinting/cups-filters/files/4109459/attrs.txt)

**Comment by tillkamppeter** [comment]
Try the following:
Copy the PPD file of the printer into a new file:
```
cp /etc/cups/ppd/Epson-XP-5100.ppd new.ppd
```
Edit `new.ppd` removing the line
```
*cupsFilter2: "image/pwg-raster image/pwg-raster 0 -"
```
Now manually create a print queue
```
lpadmin -p epson-new -E -v ipp://EPSON3078C9.local:631/ipp/print -P new.ppd
```
Try to print to this queue. Does this solve your problem?
This queue makes Apple Raster being used as data input format for your printer. The automatically created queues let it use PWG Raster. Probably the printer has a firmware bug so thet the PWG Raster does not get printed with correct colors.

**Comment by HerrUntermoser** [comment]
Black ink is now empty, i must wait until tuesday....

**Comment by HerrUntermoser** [comment]
Okay. Found the bug. Pretty silly...
It was a tiny transparent rest of the adhesive strip that closes the vent of the cartridge during transport. You have to figure that out. Thank you for your help.
At least I learned how to use the terminal to get the UID and create an extra printer queue. Without the GUI.
