### ISSUE TITLE
Tray/InputSource setting is ignored

### ISSUE THREAD

**Issue by kristianlm** [OpenPrinting/cups-filters#193]
Hi, and thanks for making printing on Linux a pleasant experience. I have a fix for an issue with my HP printer, but I don't know if this is the right forum to report this. I have an HP Color LaserJet M750 that works well on my Arch Linux distro, with the exception of tray selection. I installed the drivers through the cups webadmin on port 631 and added my new printer.

I ran into a problem where the printer would ignore my Paper Source / Tray selection choice in the print dialog. The below changes seems to fix this problem.

```patch
klm@kth ~ ➤ sudo diff --color -U3 /etc/cups/ppd/Hewlett-Packard_HP_Color_LaserJet_M750.ppd  /etc/cups/ppd/Hewlett-Packard_HP_Color_LaserJet_M750.ppd.O~                                                                                      7s
--- /etc/cups/ppd/Hewlett-Packard_HP_Color_LaserJet_M750.ppd	2020-01-25 23:08:27.407984247 +0100
+++ /etc/cups/ppd/Hewlett-Packard_HP_Color_LaserJet_M750.ppd.O~	2020-01-24 20:59:21.839927979 +0100
@@ -205,9 +205,9 @@
 *OrderDependency: 10 AnySetup *InputSlot
 *DefaultInputSlot: Auto
 *InputSlot Auto/Automatic: "<</MediaPosition 0>>setpagedevice"
-*InputSlot Tray3/Tray 3: ""
-*InputSlot Tray2/Tray 2: ""
-*InputSlot Tray1/Tray 1: ""
+*InputSlot Tray-3/Tray 3: ""
+*InputSlot Tray-2/Tray 2: ""
+*InputSlot Tray-1/Tray 1: ""
 *CloseUI: *InputSlot
 *OpenUI *ColorModel/Print Color Mode: PickOne
 *OrderDependency: 10 AnySetup *ColorModel
```

I hope this can is the right place to report this and hope it can be integrated into this generated `driverless` cups-filters driver.

**Comment by tillkamppeter** [comment]
Reported CUPS upstream bug apple/cups#5740, applying the attached patch to CUPS should fix your problem. If your queue's PPD is generated by cups-filters, your problem should also get solved by commit cc1354c11.
See also issue #201.
