### ISSUE TITLE
driverless generates wrong InputSlots for a Xerox B215

### ISSUE THREAD

**Issue by debiantriage** [OpenPrinting/cups-filters#201]
In Debian Bug #949315 Martin Mares  reports a problem with name mangling rules in ppdgenerator.c of cups-filters and ppd-cache.c of CUPS. My knowledge in this area is zero, so I have asked him to monitor the issue here.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=949315

Regards,

Brian.

**Comment by tillkamppeter** [comment]
Reported CUPS upstream bug apple/cups#5740, applying the attached patch to CUPS should fix your problem. If your queue's PPD is generated by cups-filters, your problem should also get solved by commit cc1354c11.

**Comment by tillkamppeter** [comment]
See also issue #193.
