### ISSUE TITLE
Samsung CLX 6260FW does not print duplex

### ISSUE THREAD

**Issue by debiantriage** [OpenPrinting/cups-filters#202]
I am unsure whether this is a cups-filters or a printer issue.

I am helping a user at https://forums.linuxmint.com/viewtopic.php?f=51&t=311643 who was originally using the ULD software.

- I requested him to set up a driverless print queue. Duplex printing still does not happen.

- I then produced an Apple Raster file on my system using cupsfilter (with _sides=two-sided-long-edge_). This prints double-sided with _lp -d envy4500 -o raw -o sides=two-sided-long-edge out.urf_ on my system.

- On the user's system, with the same OS, he gets two single-sided pages.

I haven't much of an idea how duplex works within the printing system and what causes the printer to act on a duplex command. Some advice would be welcome.

Regards,

Brian.

**Comment by tillkamppeter** [comment]
For debugging driverless printing you should at first ask the user to poll the printer's capabilities. To do, at first run the command
```
driverless
```
when the printer is turned on. This will show the URIs of all available IPP printers with driverless printing capabilities. One of the URIs is of your printer. Now run
```
ipptool -tv URI get-printer-attributes-2.0.txt > attrs.txt
```
or, if you get an error
```
ipptool -tv URI get-printer-attributes.txt > attrs.txt
```
Replace `URI` by your printer's URI. `attrs.txt` is the list of the printer's IPP attributes and should get attached to the bug report or forum discussion.
In the attributes you can easily see whether the printer supports duplex (look for "sides-supported") and also what the printer supports in AirPrint (Apple Raster) mode (look for "urf-supported". If in the string followin it is a "DM" with a number, the printer should support duplex also in AirPrint mode.
When printing a job in duplex, the CUPS "ipp" backend sends the job with a "sides=two-sided-long-edge" IPP attribute, which should switch the printer into duplex mode for this job.

**Comment by tillkamppeter** [comment]
You can send arbitrary IPP requests to a printer with `ipptool` by using other templates than the `get-printer-attributes.test` ones of above. See the `/usr/share/cups/ipptool/` for examples. There are also some for printing a file. You could edit one of these to add the "sides=two-sided-long-edge" to see whether you get duplex printing.

**Comment by debiantriage** [comment]
>  You could edit one of these to add the "sides=two-sided-long-edge" to see whether you get duplex printing.

Thanks for the tip. We edited print-job.test and sent a two-page Apple Raster file. The user gets

> bruce@bruce-MS-7982:~$ ipptool -tv -f out.txt ipp://SEC8425190506AF.local:631/ipp/printer sides.test
"sides.test":
    Print-Job:
        attributes-charset (charset) = utf-8
        attributes-natural-language (naturalLanguage) = en
        printer-uri (uri) = ipp://SEC8425190506AF.local:631/ipp/printer
        requesting-user-name (nameWithoutLanguage) = bruce
        document-format (mimeMediaType) = image/urf
        copies (integer) = 1
        sides (keyword) = two-sided-long-edge
    Print file using Print-Job                                           [PASS]
        RECEIVED: 277 bytes in response
        status-code = successful-ok (successful-ok)
        attributes-charset (charset) = utf-8
        attributes-natural-language (naturalLanguage) = en-us
        printer-uri (uri) = ipp://SEC8425190506AF.local:631/ipp/printer
        job-id (integer) = 3315
        job-state (enum) = pending
        job-state-reasons (keyword) = resources-are-not-ready
        job-uri (uri) = ipp://SEC8425190506AF.local:631/ipp/printer/Job-3315

and two sheets of paper are ejected. Only one is printed on. We also tried a socket connection with the ULD; the result was the same.

I cannot imagine what _resources-are-not-ready_ means. Not unless it implies that there is some mismatch between what is sent and what the printer is set up to do.

Anyway, this is not a cups-filters bug. I have attached an attributes file for the printer.

[Samsung_CLX-6260FW.attrs.txt](https://github.com/OpenPrinting/cups-filters/files/4239354/Samsung_CLX-6260FW.attrs.txt)
