### ISSUE TITLE
Please consider tagging convention change

### ISSUE THREAD

**Issue by kloczek** [OpenPrinting/cups-filters#213]
Current tagging convention makes small obstacle on automated packaging as `-` needs to be replaced by `.` and additionally `release` is used in tag adds additional prefix in git auto generated tar balls 

Try to have look on https://github.com/OpenPrinting/cups-filters/archive/release-1-27-2.tar.gz which has as base directory `cups-filters-release-1-27-2/`.
Those tar balls are useful on some operations (not only released one).

If may I ask as tagging convention use just release (with dots) like it is usually it is done in most of the git projects.

Thx for understanding :)

**Comment by tillkamppeter** [comment]
Done.

After long time without releases I have started the new release tagging policy with the [1.28.0](https://github.com/OpenPrinting/cups-filters/releases/tag/1.28.0) release.

**Comment by kloczek** [comment]
Thank you very much :)
