### ISSUE TITLE
gs -dSAFER breaks printing

### ISSUE THREAD

**Issue by ajacoutot** [OpenPrinting/cups-filters#216]
Hi.

This commit prevents from printing on OpenBSD: https://github.com/OpenPrinting/cups-filters/commit/f1178bb5c97338c00393d77fb6f9f84a74d5d519

D [08/Mar/2020:15:02:34 +0100] [Job 98] GPL Ghostscript 9.07: Unrecoverable error, exit code 1
D [08/Mar/2020:15:02:34 +0100] [Job 98] PID 56561 (/usr/local/libexec/cups/backend/lpd) exited with no errors.
D [08/Mar/2020:15:02:34 +0100] [Job 98] PID 48518 (/usr/local/libexec/cups/filter/foomatic-rip) stopped with status 3.
D [08/Mar/2020:15:02:34 +0100] [Job 98] Hint: Try setting the LogLevel to "debug" to find out more.
D [08/Mar/2020:15:02:34 +0100] [Job 98] Process is dying with \"Unable to determine number of pages, page count: -1
D [08/Mar/2020:15:02:34 +0100] [Job 98] \", exit stat 3
D [08/Mar/2020:15:02:34 +0100] [Job 98] Cleaning up...
D [08/Mar/2020:15:02:34 +0100] [Job 98] End of messages

If I remove the -dSAFER option, then printing works again.

**Comment by tillkamppeter** [comment]
Fixed in commit 84d0b48a4f2. Thanks for the bug report.
