### ISSUE TITLE
A too small file will result in no print at all

### ISSUE THREAD

**Issue by cmvizitiu** [OpenPrinting/cups-filters#217]
Cups 2.2.12 with cups-filters 1.27.1 (Fedora 31 up to date x86_64). Socket printer HP 1606dn using Foomatic/foo2zjs-z2. 

The issue I am facing is trying to print just two rows of plain text from Leafpad (but it can be reproduced with Xed, Kate and even LibreOffice Write). Everything seems OK except nothing comes out of the printer which printer will work for "larger" files. Job appears as completed in CUPS web page and it also appears in system logs. For larger files foomatic logs calling foo2zjs-z2 while for the smaller files that type of entry doesn't show up. 

I replaced foomatic-rip with a simple shell so that I could capture the PDF output sent to foomatic. By enabling debug in foomatic I also got the logs for both correct and broken print attempts.

I'm attaching the following files:

- Printer PPD
- Foomatic broken page log
- Foomatic good page log
- Foomatic good page PS file 
- "Too small" PDF sent by CUPS to Foomatic

[fooerror.tar.gz](https://github.com/OpenPrinting/cups-filters/files/4313510/fooerror.tar.gz)

**Comment by tillkamppeter** [comment]
foo2zjs uses foomatic-rip.
There were several fixes and improvements on foomatic-rip in cups-filters 1.27.2, most probably also for your problem. Please update and check whether it helps.

**Comment by cmvizitiu** [comment]
> There were several fixes and improvements on foomatic-rip in cups-filters 1.27.2, most probably also for your problem. Please update and check whether it helps.

Oh... indeed manually forcing an upgrade of cups-filter/libs fixed the problem. Guess I'll have to wait for the distro to bring official packages then. Thanks for help!

**Comment by zdohnal** [comment]
@cmvizitiu Actually, cups-filters-1.27.2 is in testing repo nearly a week https://bodhi.fedoraproject.org/updates/FEDORA-2020-83519d93aa , waiting to get karma from users.
You can wait till it gets into stable repos, or install it from updates-testing repo (and leave a karma in bodhi if needed to speed up the process).
