### ISSUE TITLE
Printing speed degraded on pdf forms

### ISSUE THREAD

**Issue by OhGonneck** [OpenPrinting/cups-filters#23]
Note: I have technically not really an idea how cups-filter works. (Or why the potential bug could be related to it) but the developer of the cups project seems to think it could be so:
https://github.com/apple/cups/issues/5242#issuecomment-367021585
I am just sure that the "symptom" shows on several newer Linux distributions and it doesn't on older ones.

After updating the operating system (and therefore cups and cups-filters) on a test system i recognized that all printouts (of the specific document assembling) from that system are significantly slower than before. (Around 40% on the HP M608DN printer i am using, but the symptom also shows on a range of different network printers i have tested.)

Since this update needs to be done on the production system too this is pretty bad for me because that is the main purpose of that system (it basically prints the whole day through) and so the speed of the whole system will degrade if i do the update. (The printouts are usually done in batches of 3 to 33 document sheets (6 to 66 pages) and always have a combination of documents that show the symptom.)

I think i tracked it down to be related to printing pdf documents with and without form-elements alternating like the following two documents:

[test_PDFs_and_protocol.tar.gz](https://github.com/OpenPrinting/cups-filters/files/1748150/test_PDFs_and_protocol.tar.gz) 

One is a pdf form from /usr/share/cups/data on the newer systems, the other one is an anonymized document created by me (in case the document size or complexity somehow matters).
The exact print command used is contained in the results.txt file.

Here are the printing times of these files on four different Systems. The inner ones are the "new" ones with CUPS 2.x while the old ones use 1.5.x. I added the cups-filers versions too.
The Suse 13.2 system seems to be the only one that doesn't have a cups-filters package installed, but the following two:
cups-filters-foomatic-rip
cups-filters-ghostscript
Both have Versions 1.0.58.

```
       Ubuntu 12.04  Netrunner/Debian 9     SUSE 42.3        SUSE 13.2
M553:   40 Seconds      76 Seconds          54 Seconds      41 Seconds
M608:   27 Seconds      71 Seconds          41 Seconds      27 Seconds
c-f. vers.    1.0.18              1.16.4-1                  1.8.2               1.0.58 
```

All Printers tested are network printers, all tests were done multiple times with the same results and the "Ubuntu 12.04" is a live-dvd tested on the same Hardware as the SUSE 42.3 system. (Using the same network, the same printer and the same printer driver ppd.) The viewable problem with the "slow" prints is that the printers always seem to stop and make one ore more little pauses in between while using the old systems it prints the whole bunch through.

**Comment by tillkamppeter** [comment]
It seems that the problem appeared with some change between 1.8.2 and 1.16.4.

As this is a long time with a lot of changes, it is difficult to see which change caused the problem, or even which filter. To find this out you need to go onto the machine with the new cups-filters and put several jobs of the problematic file into the print queue. While the jobs get printed, run "top" and see which process uses most CPU. Please tell which filter this is.

**Comment by OhGonneck** [comment]
On the openSUSE Leap 42.3 i can see pdf2ps running while printing, but the workload is not really high (maybe 12 percent at maximum).

On the Netrunner system the CPU usage actually is 100% between the pages (when the printer stalls and waits) . But the process is "lp". 
How do i find out which filter it is?

I don't know if the following Information is useful:
When i start a printjob with 12 pdf pages on Leap 42.3 i alswys see pdf2ps coming up in top - even 20 seconds after the start of the lp command.
If i do the same on the 13.2 system the cpu load is actually higher (around 35%) but it is gone after about 12 seconds.
(Both systems have the same processor.)

I don't know if the command line tool "pdf2ps" is or uses the filter (or if pdf2ps is a filter at all :-)), but time gives more or less the same results on both systems when converting a pdf file:
```
42.3:
time pdf2ps form_english.pdf

real    0m4.717s
user    0m4.640s
sys     0m0.047s

13.2:
time pdf2ps form_english.pdf

real    0m4.680s
user    0m4.634s
sys     0m0.047s
```

**Comment by OhGonneck** [comment]
Gosh i'm an idiot.
The test pdf file i created is not even necessary. It can be easily observed by printing "form_english.pdf" from the cups data directory several times.

On the old systems the printer prints steadily while it stalls after every single page on the new ones.

**Comment by OhGonneck** [comment]
I changed the topic to better reflect the problem. I think it is justified to assume that this happens on all PDF form documents.

**Comment by OhGonneck** [comment]
Is there any way i can assist with this? 
I'm slowly getting bored of laying lazily in the sun all the time ;-)

**Comment by tillkamppeter** [comment]
From version 1.17.4 on `pdftopdf` calls additional filters (`pdftocairo` or Ghostscript) to flatten PDF forms so that the filled in text will not get lost when doing manipulations like N-up or scale-to-fit on the pages. This can slow down the printing.
In a future version of cups-filters pdftopdf will do this directly (using QPDF), which is probably faster as there are less sub processes and pipes.

**Comment by OhGonneck** [comment]
Interesting. But the tested "slow" Systems have versions 1.16.4-1 and 1.8.2 which are both beneath 1.17.4.

To flatten the PDF before use is my current workaround. 
(The same Document is used multiple Times .)

**Comment by renne** [comment]
Postscript printers have been very slow for years. This seems to be related to the filters used. In 2006 my Dell 3110cn easily printed 20 pages per minute. A 300 pages script with images and double-sided printing was done in 30-45 minutes (~10 pages/minute). A few years later pdftops became very slow and produced huge Postscript output (up to 500 MBytes). Today pdftops runs 30 seconds for the printer test page on an Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz. Same situation with a Dell 3115cn MFP.

I've read somewhere Ghostscript does not support transparencies in Postscript 3 which could be an explanation for the huge pdftops output size:

```
[renne@Aspire test]$ time pdftops -level3 -origpagesizes -nocenter -r 600 ./APDS-9960_General_Application_Guide.pdf ./APDS-9960_General_Application_Guide.ps

real	0m15,630s
user	0m15,490s
sys	0m0,140s
[renne@Aspire test]$ ls -ahl
insgesamt 25M
drwxr-xr-x  2 renne renne 4,0K  4. Sep 14:28 .
drwxr-xr-x 11 renne renne 4,0K  4. Sep 14:28 ..
-rw-r--r--  1 renne renne 1,5M  4. Sep 12:10 APDS-9960_General_Application_Guide.pdf
-rw-r--r--  1 renne renne  23M  4. Sep 14:28 APDS-9960_General_Application_Guide.ps

```
