### ISSUE TITLE
texttopaps (soft link to the paps) fails when invoking by cupsfilter

### ISSUE THREAD

**Issue by tangyanli** [OpenPrinting/cups-filters#231]
Hi,
I print text file on fedora31. The cups invokes "texttopaps" as a filter to convert file from text to postscript. And the printing successes.

But when I use "cupsfilter" command to invoke the "texttopaps", it always fails.
$cupsfilter -m application/postscript -d [printername] text.txt

    INFO: texttopaps (PID 124239) started.
    Failed to open 1!
    ERROR: texttopaps (PID 124239) stopped with status 1
It seems texttopaps uses the [job-id] as [file], so it fails to open the [file].

Does cups do some special action towards the "texttopaps" during printing?
I also submit a issue on paps https://github.com/dov/paps/issues/34#issue-614508721.

**Comment by tillkamppeter** [comment]
Neither texttopaps nor cupsfilter are part of cups-filters. The former is a project on its own AFAIR and the latter is part of CUPS. Please report a bug there.
