### ISSUE TITLE
Label Writer 280 prints empty by LibreOffice

### ISSUE THREAD

**Issue by joni73** [OpenPrinting/cups-filters#232]
hi, tried to print Libre Office -> Dymo-driver -> Cups -> Lable Writer 280 but it dose
not work.

I was selected device Lable Writer.

There was not model 280 !

It writes empty or nothifng !!!

joni

**Comment by tillkamppeter** [comment]
The label printer drivers are part of [CUPS](https://github.com/apple/cups), please report an issue there.
See also [LPrint](https://github.com/michaelrsweet/lprint/) for a newer label printer driver package.
