### ISSUE TITLE
Wrong tray with Canon printer PIXMA MG5350

### ISSUE THREAD

**Issue by PaoloPelloni** [OpenPrinting/cups-filters#233]
Issue: From most of the applications when I print it goes on the rear tray regardless of the settings in the applications and the default options of the printer (both automatic and main) checked from setting and localhost:631. LibreOffice is one of the few where the paper is correctly sources from the cassette tray. 

Environment: Ubuntu 20.04 / Canon PIXMA MG5350 / Driver: Canon MG5300 series, driverless, cups-filters 1.27.4 - Cups 2.3.1

Note: With the previous version of Ubuntu, 18.04, I could install the Canon driver and it was working fine. With this version the old legacy driver does not install and there is this issue.

**Comment by tillkamppeter** [comment]
Could you please attach the PPD file of your print queue (from `/etc/cups/ppd/`).
Please also run the command
```
driverless
```
This will output the URI of your printer in one line. If there are more lines of output, look for the one which is of your printer (should contain manufacturer and model names).
Then run
```
ipptool -tv URI get-printer-attributes.test > log.txt
ipptool -tv URI get-printer-attributes-2.0.test > log2.txt
```
with URI replaced by your printer's URI which you got with the first command. Attach the two output files.
Please also print a job where the wrong paper tray is used. Before printing switch CUPS into debug logging mode as described [here](https://wiki.ubuntu.com/DebuggingPrintingProblems#CUPS_error_log). Attach the `error_log` file after the job is printed.
Please attach the individual files, without compressing them and without packaging them together. Rename the files to have a `.txt` file name extension, so that they get accepted by GitHub.
Thanks in advance.

**Comment by PaoloPelloni** [comment]
> Could you please attach the PPD file of your print queue (from `/etc/cups/ppd/`).

I uploaded as a tar.gz because PPD want' allowed.


> Please also run the command
> 
> ```
> driverless
> ```
> 
> This will output the URI of your printer in one line. If there are more lines of output, look for the one which is of your printer (should contain manufacturer and model names).
> Then run
> 
> ```
> ipptool -tv URI get-printer-attributes.test > log.txt
> ipptool -tv URI get-printer-attributes-2.0.test > log2.txt
> ```
> 
> with URI replaced by your printer's URI which you got with the first command. Attach the two output files.

Unfortunately the driverless works, but then the ipptool fails:

`$ driverless
ipp://Canon%20MG5300%20series._ipp._tcp.local/

$ ipptool -tv ipp://Canon%20MG5300%20series._ipp._tcp.local/ get-printer-attributes.text > log.txt
ipptool: Unable to connect to "Canon MG5300 series._ipp._tcp.local" on port 631 - Name or service not known
`
and even if

`ipptool -tv "ipp://Canon_MG5300_series._ipp._tcp.local/" get-printer-attributes.text > log.txt`

fives the same error.

> Please also print a job where the wrong paper tray is used. Before printing switch CUPS into debug logging mode as described [here](https://wiki.ubuntu.com/DebuggingPrintingProblems#CUPS_error_log). Attach the `error_log` file after the job is printed.
> Please attach the individual files, without compressing them and without packaging them together. Rename the files to have a `.txt` file name extension, so that they get accepted by GitHub.
> Thanks in advance.

I have uploaded the error_log from cups of a job sent to the main tray, that is hanging on the printer because it is waiting for paper on rear tray. 

Hope it helps. 
Thanks!


[Canon_MG5300_series.ppd.tar.gz](https://github.com/OpenPrinting/cups-filters/files/4633048/Canon_MG5300_series.ppd.tar.gz)

[error_log.txt](https://github.com/OpenPrinting/cups-filters/files/4633312/error_log.txt)

**Comment by tillkamppeter** [comment]
The problem here is that `ipptool` does not support DNS-SD-service-name-based URIs.
For `ipptool` one needs a URI of the format
```
ipp://{IP or host name]:[PORT]/ipp/print
```
So you need to find out your printer's IPP address (you could use `avahi-discover` for that and then the printer's URI is
```
ipp://[IP address]:631/ipp/print
```
Use this URI with `ipptool`.

**Comment by zdohnal** [comment]
@tillkamppeter  @PaoloPelloni  FYI support for DNS-SD-service-name-based URIs in ipptool is in this pull request in CUPS project https://github.com/apple/cups/pull/5793 .
With the current state of CUPS project, your distro may reconsider to add it as a downstream patch.

**Comment by tillkamppeter** [comment]
Another hint:
If you run the command
```
ippfind
```
you get URIs in the standard IPP format. Uses these URIs with `ipptool`. Note that `ippfind` also lists remote CUPS printers and network printers which do not support driverless IPP (older IPP 1.x printers).

**Comment by tillkamppeter** [comment]
@PaoloPelloni did not answer any of our further questions for several weeks. Closing ...

**Comment by tillkamppeter** [comment]
See follow-up #278.
