### ISSUE TITLE
pdftopdf with print-scaling option produces broken PDF

### ISSUE THREAD

**Issue by mattenklicker** [OpenPrinting/cups-filters#238]
When printing through Avahi/Airprint my printer produces blank pages. Only ghostscript is complaining in debug log: `**** Error reading a content stream. The page may be incomplete.`

Somewhere in the process something like `/usr/libexec/cups/daemon/cups-exec -g 7 -n 0 -u 4 none /usr/libexec/cups/filter/pdftopdf "Samsung_SCX-4x21_Series" "45" "mobile" "Test-PDF-Title" "1" "print-scaling=auto-fit print-quality=4 sides=one-sided job-uuid=urn:uuid:f73a1c18-5355-3783-6295-b26d66f8f7df job-originating-host-name=192.168.1.48 date-time-at-completed= date-time-at-creation= date-time-at-processing= time-at-completed=1590296050 time-at-creation=1590296048 time-at-processing=1590296542 cupsPrintQuality=Normal media=A4 PageSize=A4" test.pdf` is called and handed over to gs. This produces broken PDF files.
The reason is the "print-scaling=" option. 
To reproduce it, run `/usr/libexec/cups/filter/pdftopdf 1 user title 1 "print-scaling=auto-fit" /usr/share/cups/data/default-testpage.pdf | gs -dNOPAUSE -dBATCH -f -`
```
   **** Error reading a content stream. The page may be incomplete.
               Output may be incorrect.
   **** Error: File did not complete the page properly and may be damaged.
               Output may be incorrect.
```
My current workaroud it to downgrade cups-filters to <1.23.0 because it didn't support the `print-scaling` option before (#118).

**Comment by zdohnal** [comment]
Hi @mattenklicker ,

you don't need to run the filter via cups-exec - the way:
```
/usr/libexec/cups/filter/pdftopdf "Samsung_SCX-4x21_Series" "45" "mobile" "Test-PDF-Title" "1" "print-scaling=auto-fit print-quality=4 sides=one-sided job-uuid=urn:uuid:f73a1c18-5355-3783-6295-b26d66f8f7df job-originating-host-name=192.168.1.48 date-time-at-completed= date-time-at-creation= date-time-at-processing= time-at-completed=1590296050 time-at-creation=1590296048 time-at-processing=1590296542 cupsPrintQuality=Normal media=A4 PageSize=A4" test.pdf
```
works the same way.

Would you mind attaching your ppd file from /etc/cups/ppd and PDF file you experience the issue with?

**Comment by mattenklicker** [comment]
[Samsung_SCX-4x21_Series.ppd.gz](https://github.com/OpenPrinting/cups-filters/files/4682846/Samsung_SCX-4x21_Series.ppd.gz)

Can't get an PDF right now, but it happens with every PDF coming from an ios device via AirPrint. Can test it with default-testpage.pdf later. But I don't think it has something to do with the PPD or PDF. Simplest way to reproduce:
  * Working: `/usr/libexec/cups/filter/pdftopdf 1 user title 1 "nothing" /usr/share/cups/data/default-testpage.pdf | pdftotext - -` -> `Printer Test Page`
  * Broken: `/usr/libexec/cups/filter/pdftopdf 1 user title 1 "print-scaling=auto-fit" /usr/share/cups/data/default-testpage.pdf | pdftotext - -` -> 
```
Syntax Error (570): Unknown operator 'nan'
Syntax Error (573): Unknown operator 'nan'
Syntax Error (577): Unknown operator 'nan'
Syntax Error (582): Unknown operator 'nan'
Syntax Error (585): Too few (0) args to 'cm' operator
```

Or is this kind of expected behavior?

**Comment by tillkamppeter** [comment]
I have tested with the most current version of cups-filters, 1.27.4 now and cannot reproduce the bug. I do not get the shown errors with "print-scaling=auto-fit", exactly using the command line
```
PPD=Samsung_SCX-4x21_Series.ppd /usr/lib/cups/filter/pdftopdf 1 user title 1 "print-scaling=auto-fit" /usr/share/cups/data/default-testpage.pdf | pdftotext - -
```
I can also can add any `PageSize=...` setting and it also works.

**Comment by mattenklicker** [comment]
Strange. Then it's probably gentoo related. I'll open a bug downstream. I'll keep you informed.

**Comment by mattenklicker** [comment]
I found it.
`print-scaling=auto-fit` adds an additional stream to the resulting PDF.
Under normal conditions the stream looks like:
```
stream
q
q
  0.855219 0.000000 0.000000 0.855219 51.454559 36.000000 cm
  /X1 Do
Q
Q
endstream
```
When compiled with `-ffast-math` the stream is:
```
stream
q
q
  nan 0.000000 0.000000 nan nan nan cm
  /X1 Do
Q
Q
endstream
```

**Comment by dipanshu231099** [comment]
i tried running the following 2 commands:
```PPD=Samsung_SCX-4x21_Series.ppd /usr/lib/cups/filter/pdftopdf 1 user title 1 "print-scaling=auto-fit" /usr/share/cups/data/default-testpage.pdf > sample1.pdf``
```PPD=Samsung_SCX-4x21_Series.ppd /usr/lib/cups/filter/pdftopdf 1 user title 1 "nothing" /usr/share/cups/data/default-testpage.pdf > sample2.pdf``
produce identical outputs. i guess @mattenklicker @tillkamppeter this is some system specific issue.

**Comment by mattenklicker** [comment]
I see two options here:
Either change the calculation so that it produces correct results even with -ffast-math.
Or break the build if -ffast-math is switched on.

**Comment by dipanshu231099** [comment]
@mattenklicker have you show outputs obtained using different flag such as ```-fno-fast-math```

**Comment by mattenklicker** [comment]
@dipanshu231099 You mean you can't reproduce it?

Nice, I tried the git version and it seems to be fixed in git!

It was broken until 1.27.5:
`PPD=Samsung_SCX-4x21_Series.ppd /usr/libexec/cups/filter/pdftopdf 1 user title 1 "print-scaling=auto-fit" /usr/share/cups/data/default-testpage.pdf > sample.pdf && qpdf --qdf sample.pdf -|grep stream -A5 -m1`
```
stream
q
q
  nan 0.000000 0.000000 nan nan nan cm
  /X1 Do
Q
```

**Comment by dipanshu231099** [comment]
@mattenklicker yes i was unable to reproduce the error till now. So i guess it had been an issue of updating to the latest commits then. I am glad the lattest commits sorted the problem for you.
