### ISSUE TITLE
rastertopclm: Incorrect PCLM output when input raster resolution is not the same as pclm default resolution.

### ISSUE THREAD

**Issue by sahilarora535** [OpenPrinting/cups-filters#24]
Sometimes it may happen that the default resolution for PCLM is different from what the input `raster` has. In that case, the PCLM file generated from the `rastertopclm` filter is incorrect. For instance, if the input raster has a resolution of `600dpi`, and the default PCLM resolution in the PPD file is `1200dpi`, this is how the resultant PCLM file looks like:

![image](https://user-images.githubusercontent.com/12633577/36608991-8c4d2774-18f1-11e8-8074-574417449f52.png)

when ideally, it should span full page and look like this:

![image](https://user-images.githubusercontent.com/12633577/36609070-bc14dd94-18f1-11e8-9315-c0f30f1d5790.png)

The solution to this would be to check what is the resolution of the input `raster` file, and if that resolution is present in the `*cupsPclmSourceResolutionSupported` key in the PPD, use that resolution to convert the PCLm file.

**Comment by tillkamppeter** [comment]
If the input file is a PDF then pdftoraster should already produce raster in the desired resolution (the one which was selected by the user, a supported one). So in most cases the problem should not occur. But a filter chain going through imagetoraster could cause this problem when the input resolution is wrong. In this case we would need a resolution transformation, like 300 dpi -> 600 dpi or 600 dpi -> 300 dpi (or even 720 dpi -> 600 dpi). This transformation could be done by imagetoraster.
Was my assumption right? Or did you observe the problem also with a pdftoraster -> rastertopclm filter chain?

**Comment by sahilarora535** [comment]
> If the input file is a PDF then pdftoraster should already produce raster in the desired resolution (the one which was selected by the user, a supported one). So in most cases the problem should not occur. But a filter chain going through imagetoraster could cause this problem when the input resolution is wrong. In this case we would need a resolution transformation, like 300 dpi -> 600 dpi or 600 dpi -> 300 dpi (or even 720 dpi -> 600 dpi). This transformation could be done by imagetoraster.

The problem does not occur in most of the cases, and even while testing on a range of PDFs with an HP Printer, the results were good all the time.

However, sometimes if the default resolution in the PPD is say `300dpi`, the default PCLM resolution is `600dpi`, or something different from the default resolution, and the input is a PDF file, then the chain followed is:
```
pdftopdf
gstoraster
rastertopclm
```

and in this case, the `gstoraster` produces a `raster` of `300dpi`, and then the `rastertopclm` filter converts it to `600dpi`, causing the error.

About the `imagetoraster` filter, this error may appear there as well if the case is similar. Ideally, for a printer, the `printer-resolution-default` and the `pclm-source-resolution-default` IPP attributes should be same, and hence this error should not occur. Only if we provide a custom PPD which has these two resolutions different or a printer has different values for these we may get erreneous results.

**Comment by tillkamppeter** [comment]
As for all filters of cups-filters also the rastertopclm (rastertopdf) filter needs to follow the rule of first checking the command line (5th argument) for a "Resolution" option (all filters in the chain receive the same command line) and if there is no "Resolution" option, take the "*DefaultResolution:" entry of the PPD and only if this is missing take anything else. This way all filters use the same resolution. Assuming that the PPDs contain only valid resolutions this resolution should be suitable for a PCLm file for this printer. imagetoraster should also follow this rule (needs to be checked).

**Comment by tillkamppeter** [comment]
@sahilarora535, do you still have this problem or is it already solved?

**Comment by sahilarora535** [comment]
@tillkamppeter Apologies, I could not follow up on this issue. I will have a look into it and get back. Thank you.

**Comment by tillkamppeter** [comment]
Any progress on this?

**Comment by sahilarora535** [comment]
> As for all filters of cups-filters also the rastertopclm (rastertopdf) filter needs to follow the rule of first checking the command line (5th argument) for a "Resolution" option (all filters in the chain receive the same command line) and if there is no "Resolution" option, take the "*DefaultResolution:" entry of the PPD and only if this is missing take anything else. This way all filters use the same resolution. Assuming that the PPDs contain only valid resolutions this resolution should be suitable for a PCLm file for this printer. imagetoraster should also follow this rule (needs to be checked).

Let's assume the resolution of input raster is 100dpi. So according to your comment, here is how the flow for getting the resolution should work:
1. Check if the argument `Resolution` is passed in command line, If yes, then this should be the resolution of the output file and this is to be used. If this is different from 100dpi, what should be done?
2. If the command line resolution is not there, then use the `*DefaultResolution` from the PPD. Again, what is to be done if this is not equal to 100dpi?
3. If default resolution is not present, then use the PCLm default resolution using the PPD attribute `cupsPclmSourceResolutionDefault`. Again,this can be anything.
4. If PCLm default resolution is also not present, the last is `cupsPclmSourceResolutionSupported` which is an array of resolutions supported by the printer. Which of the resolutions should we be using?

**Comment by tillkamppeter** [comment]
In a normal filter chain there is always pdf/gs/mupdf/imagetoraster before rastertopclm. As both are taking the selected resolution from the "Resolution" option or the default resolution from `*DefaultResolution` from the same PPD file (and for driverless printing PPD auto-generation this keyword is always present) the mentioned situation cannot happen. The incoming raster data always has a suitable resolution (or the pdf/gs/mupdf/imagetoraster in use has a bug). So all the cases 1-4 you mentioned should never happen.

**Comment by sahilarora535** [comment]
So should we safely close this? At the time when I raised this issue, I was playing around with the PPD files and made the `DefaultResolution` different from `cupsPclmSourceResolutionDefault`. However, with the printer which I was provided with to test, both the values were same. So if the cases 1-4 do not occur, then this bug should not occur in real-world scenarios.

**Comment by tillkamppeter** [comment]
Yes, the scenario which you created does actually not occur. If you find a PPD with such discrepancy, or without `*DefaultResolution` entry at all, we can report a bug on the PPD file. It would be a bug in cups-filters if one of the pdf/gs/mupdf/imagetoraster filters does not respect the "Resolution" option or the default resolution from "*DefaultResolution".
So I am closing this bug report.
