### ISSUE TITLE
'KeepGeneratedQueuesOnShutdown' concerns     

### ISSUE THREAD

**Issue by zdohnal** [OpenPrinting/cups-filters#241]
Hi,

I saw the latest cups-filters version has 'KeepGeneratedQueuesOnShutdown' functionality and I would like to express my concerns about implementing the feature and possible problems.

1) turning off cups-browsed will not clean the queues which are created by cups-browsed - IMO cleaning print queues is the same behavior as cupsd has - when you stop cupsd, there are no queues available, so cups-browsed should behave the same
2) the feature would make sense if cups-browsed was doing only device discovery and print queue creation, but IIUC it handles dbus notifications too - if cups-browsed is not started because of whatever reason, implicitclass backend will not work if the default destination uri will not work or when there is no default destination uri at all (e.g. cups-browsed ended before it was able to set destination).

What do you think about it? IMO the feature can bring up more serious issues than it solves (duplicate notifications don't seem as a serious issue comparing to non-functional queue).

**Comment by zdohnal** [comment]
And 'BrowsePoll' directive is affected too - if you run cups-browsed with BrowsePoll set, cups-browsed will populate the print queue list. Then remove BrowsePoll and restart cups-browsed -> print queues from BrowsePoll should disappear, but they are still around.

**Comment by tillkamppeter** [comment]
First, the new behavior of keeping the queues on shutdown is optionsl, one can get back to the old behavior by setting `KeepGeneratedQueuesOnShutdown No` in `cups-browsed.conf`.

The queues stay conserved as long as cups-browsed is not running. When restarting cups-browsed the queues are recognized by cups-browsed as coming from cups-browsed and considered unconfirmed. If the corresponding printer is not re-discovered within a timeout, the queue is removed.

The idea is that short interruptions of cups-browsed, for example for a log rotate, will not require a re-creation of the queues which produces annoying notification pop-ups. Also if you shut down your machine in the evening and restart it the next morning queues will not get re-created with notifications.

If queues of printers which do not get re-discovered after the restart of cups-browsed do not get removed after a timeout, this is an independent bug which was already there before (but before only got visible after a crash or a hard kill (`kill -9 ...`) of cups-browsed).

The queues are marked as coming from cups-browsed. If you shut down cups-browsed and after that cups, you can see this in `/etc/cups/printers.conf`. The option is `cups-browsed`.

The timeout for DNS-SD-discovered print queues to disappear when not re-discovered is 10 seconds, it is possible that classic CUPS queues (both via CUPS broadcasting or BrowsePoll) use the BrowseTimeout of 300 seconds or 5 minutes.

Please check, if something is going wrong, attach `/etc/cups/printers.conf` (after first cups-browsed and after that cupsd being stopped) and `/var/log/cups/cups-browsed_log` (the latter needs `DebugLogging file` set in `cups-browsed.conf`. Please attach also your `cups-browsed.conf`.

Do not compress the files or package them together. Rename to have a `.txt` file name extension to attach the files.

**Comment by zdohnal** [comment]
> First, the new behavior of keeping the queues on shutdown is optionsl, one can get back to the old behavior by setting `KeepGeneratedQueuesOnShutdown No` in `cups-browsed.conf`.
> 

Unfortunately, in my opinion making optional feature, which causes problems and has such impact on previous behavior, enabled by default, is problematic.

Will you be okay with configure option for it? Patching configuration file during package build is a redundant downstream patch, so I would create a configure option for it + for 'LocalQueueNaminRemoteCUPS'.

> The queues stay conserved as long as cups-browsed is not running. When restarting cups-browsed the queues are recognized by cups-browsed as coming from cups-browsed and considered unconfirmed. If the corresponding printer is not re-discovered within a timeout, the queue is removed.
> 

The key here is 'when restarting cups-browsed'. The problem is in scenario when you don't want to start cups-browsed again - f.e. you found out your printer is working with temporary queues, you want to use a temp queue now, but you were using cups-browsed till now - so you stop cups-browsed and disable it, but you are left with dangling print queue from cups-browsed.

> The idea is that short interruptions of cups-browsed, for example for a log rotate, will not require a re-creation of the queues which produces annoying notification pop-ups. Also if you shut down your machine in the evening and restart it the next morning queues will not get re-created with notifications.
>

In my opinion the problem is you are not able to detect the reason why cups-browsed needs to be restarted from cups-browsed itself - is it for a simple restart or a complete shutdown of service for good? It makes sense for use case you introduced it for, but in my humble opinion dangling print queues  present more annoyance for user than duplicated notifications. Normal user doesn't see a difference between cups-browsed created queues and others, can print to the dangled queue and nothing is printed.

> If queues of printers which do not get re-discovered after the restart of cups-browsed do not get removed after a timeout, this is an independent bug which was already there before (but before only got visible after a crash or a hard kill (`kill -9 ...`) of cups-browsed).
>
> The queues are marked as coming from cups-browsed. If you shut down cups-browsed and after that cups, you can see this in `/etc/cups/printers.conf`. The option is `cups-browsed`.
> 
> The timeout for DNS-SD-discovered print queues to disappear when not re-discovered is 10 seconds, it is possible that classic CUPS queues (both via CUPS broadcasting or BrowsePoll) use the BrowseTimeout of 300 seconds or 5 minutes.
> 

I'll debug the issue with queues staying after BrowsePoll removal and post my findings.

Please reevaluate pros (removes duplicated dbus notifications) and cons (either temporary one - bug with dangling 'browsepoll' queues, or permanent - dangling queues after stopping the service, removable only manually) of the added feature in its current state.
In my humble opinion duplicated notifications cannot be solved with the current feature without notable regressions in cups-browsed behavior, but I don't have any idea how it can be solved other way (maybe don't generate created-printer notification for cups-browsed created print queues in CUPS?). I would say having duplicate notifications is okay comparing the possible regressions, so I would be okay with feature removal.

If the feature would stay in cups-browsed, would you mind disabling the feature by default?

**Comment by zdohnal** [comment]
I talked with Marek Kasik, one of Gnome upstream devs, and it could be possible to filter out create-printer notification for cups-browsed. It could solve the problem what the feature was introduced for.

**Comment by tillkamppeter** [comment]
This would be great. Then I will make the leeping of the queues optional and keep the old behavior (removing) as the default.
For notifications one could easily recognize queues as from cups-browsed by
- they have a "cups-browsed=true" attribute set
- They usually (depends on cups-browsed configuration) have an `implicitclass:...` URI

**Comment by tillkamppeter** [comment]
The idea of a configure option for the defaults of LocalQueueNamingRemoteCUPS and KeepGeneratedQueuesOnShutdown is great. We should use the old default behavior when the configure option is not used. Could you post a PR for that?

**Comment by zdohnal** [comment]
@tillkamppeter Sure, no problem, I'll look into it after I finish gnome-settings-daemon PR from previous comment.

**Comment by zdohnal** [comment]
I would say #285 fixes this concerns.
