### ISSUE TITLE
CUPS filled my drive with giant error_log file

### ISSUE THREAD

**Issue by pauljurczak** [OpenPrinting/cups-filters#249]
CUPS stopped working on my Ubuntu 18.04 due to my tinkering with file permissions in `/usr/lib` folder. My fault. Unfortunately, in less than 24 hours, it produced 0.25TB of error log files with text like this:
```
E [21/Jun/2020:14:13:06 -0600] File \"/usr/lib/cups/notifier/dbus\" has insecure permissions (0100775/uid=0/gid=0).
W [21/Jun/2020:14:13:06 -0600] Notifier for subscription 88 (dbus://) went away, retrying!
```
Does this message have to be repeated millions of times?

**Comment by tillkamppeter** [comment]
I do not see any relation to cups-filters here, is probably a problem of CUPS itself. Please report [there](https://github.com/apple/cups/issues). Closing ...
