### ISSUE TITLE
Can't print plain text file from Linux command-line

### ISSUE THREAD

**Issue by jarviswyatt** [OpenPrinting/cups-filters#254]
I am running Ubuntu 20.04. `cups` has been installed from aptitude an it is up-to-date.
When trying to print from a command line a plain text file, the cups texttopdf filter crashes.
I am using a network printer, Brother MFC-L2710DN. The print attempt was: `lpr -P Brother_MFC_L2710DN_series testprintfile`.

I write here as suggested [in this reply](https://lists.cups.org/pipermail/cups/2020-June/074916.html) from the cups Mailing List.

Here are:
- the file I would like to print, [testprintfile.txt](https://github.com/OpenPrinting/cups-filters/files/4820614/testprintfile.txt);
- the latest file from /var/spool/cups which starts with 'd', [d00022-001.txt](https://github.com/OpenPrinting/cups-filters/files/4820630/d00022-001.txt);
- the ppd file of my print queue, [Brother_MFC_L2710DN_series.ppd.txt](https://github.com/OpenPrinting/cups-filters/files/4820642/Brother_MFC_L2710DN_series.ppd.txt).

Note that all the above files originally didn't have the `.txt` extension: I added it just to let Github upload them (files with no extension are not supported).

**Comment by jarviswyatt** [comment]
I would also like to highlight (from [another reply](https://lists.cups.org/pipermail/cups/2020-June/074918.html) to the same thread in the Mailing List) that:

> the PDF generating filters should revert to embedding full fonts if subsetting is not supported

In fact, it seems that 

> texttopdf filter forces subsetting when embedding fonts

but the

> font embed part of the sources states that subsetting with OTF fonts is not yet supported.

**Comment by debiantriage** [comment]
Also see Message 11 at the link given in https://github.com/OpenPrinting/cups-filters/issues/248 and https://github.com/apple/cups/issues/5787. The later link gives a workaround.

**Comment by jarviswyatt** [comment]
I checked them out, thank you. Trying the first workaround (the quicker one, moving the font away from `/usr/share/fonts/truetype`), I successfully printed a text file from terminal.

However, this is just a temporary solution. I wish the code can be modified to fix this in a permanent way.

**Comment by tillkamppeter** [comment]
@smilingthax, it seems that certain fonts make `texttopdf` crash, simply by their presence, even if they are not actually used by the filter. See the issues/threads linked by @debiantriage. There is an emoji font triggering an assert() in fontembed. assert() should never be used in production code, it is only for development and debugging. Also a font not needed for the filtering process should not stop the filter from working. Could you have a look.

**Comment by tillkamppeter** [comment]
Fixed by pull request #276.

**Comment by tillkamppeter** [comment]
@jarviswyatt, could you test this fix and report here? Thanks in advance.
