### ISSUE TITLE
Commit messages have unwanted characters.

### ISSUE THREAD

**Issue by sahilarora535** [OpenPrinting/cups-filters#26]
The commits from aa35e2cea8bbb4f982f6658031bd386978ae539f to bad2494746d1adef0840c17dcfae832e641bb4cf have unwanted characters which may have come mistakenly while committing. 

![image](https://user-images.githubusercontent.com/12633577/36739401-ce66bea6-1c05-11e8-8de1-22c047908c17.png)

**Comment by tillkamppeter** [comment]
The way of writing this way is intended by the contributor. And I do not see any offending characters. They all are standard- ASCII even. What is wrong with these entries? Did you have any problems to handle them caused by their commit messages?

**Comment by sahilarora535** [comment]
Oh, I thought this was not intentional and thought it had been done mistakenly. I saw the commit diffs and now it makes sense. Closing the issue.
