### ISSUE TITLE
gstoraster reducing quality of Postscript documents with raster image content.

### ISSUE THREAD

**Issue by NJRoadfan** [OpenPrinting/cups-filters#272]
This may be an edge case, but I have run into issues with gstoraster causing poor distilling of Postscript output that uses raster images embedded in the file. The program in question is a dot-matrix printer emulator that rasterizes output into a bitmap and optionally saves to a Postscript file to ease printing for *NIX platforms (it can also output to the Windows print manager direct on that platform). After some debugging with cups-filter, I determined it was gstoraster using the -dPDFSETTINGS=/printer command line switch with Ghostscript. Changing it to -dPDFSETTINGS=/default or removing it fixes the output problem. It should be noted that converting this very same Postscript file to PDF using Apple's Preview application and then submitting it cupsfilters results in no degradation (pdftopdf doesn't use any PDFSETTINGS). Yes, this degradation in image quality is visible on actual printer output. Attached are the following samples:

-The original Postscript file (zipped).
[Original Output.zip](https://github.com/OpenPrinting/cups-filters/files/5019350/Original.Output.zip)
-PDF output with -dPDFSETTINGS=/printer
[gstoraster with dPDFSETTINGS Printer.pdf](https://github.com/OpenPrinting/cups-filters/files/5019351/gstoraster.with.dPDFSETTINGS.Printer.pdf)
-PDF output with -dPDFSETTINGS=/default
[gstoraster with dPDFSETTINGS default.pdf](https://github.com/OpenPrinting/cups-filters/files/5019352/gstoraster.with.dPDFSETTINGS.default.pdf)
-PDF output of above Postscript from Apple Preview's distiller (reference/"how it should look"/raw uncropped margins).
[Distilled with Apple Preview.pdf](https://github.com/OpenPrinting/cups-filters/files/5019353/Distilled.with.Apple.Preview.pdf)

I don't know if it would cause a problem anywhere else in the filter chain, but I recommend changing gstoraster's distilling to using the 'default' setting. It doesn't appear to create PDFs much larger then the 'printer' setting and results in better output for Postscript files containing large (and blocky in this case!) raster images.

**Comment by tillkamppeter** [comment]
Could you also try `-dPDFSETTINGS=/prepress`? Please tell how this setting compares.

**Comment by tillkamppeter** [comment]
See also:
https://tex.stackexchange.com/questions/6121/presentation-option-screen-or-prepress-in-ps2pdf
https://tbrink.science/blog/2018/05/13/lossy-compression-for-pdfs/
https://tiborstanko.sk/compress-paper-pdf.html
Discovered this one and it seems that `/default` tries to conserve the original image quality, so being the best:
https://stackoverflow.com/questions/46938058/ghostscript-and-pdfscale-image-quality-loss-when-resizing-pdfs
Especially we have to keep in mind that we do not want to compress, as we stream the data on to further filters or to a printer.

**Comment by tillkamppeter** [comment]
Switched to `-dPDFSETTINGS=/default` in commit 91aaae14e.

Thank you for the report.
