### ISSUE TITLE
RFE: make debug mode configurable from cups-browsed.conf

### ISSUE THREAD

**Issue by zdohnal** [OpenPrinting/cups-filters#28]
Hi Till,

I think it would be good to have a way to set cups-browsed debug log in cups-browsed.conf, like cupsd has with 'LogLevel'. (IMO we can use something like DebugLog on/off)
I can look into it and create a patch, if you have other matters to attend to.

**Comment by tillkamppeter** [comment]
cups-browsed has such a functionality. It is the DebugLogging directive. Currently it only allows to log or not to log and whether to log on stderr and/or a file.
If you like to have more functionality here a patch via a Pull Request is welcome.

**Comment by zdohnal** [comment]
Sorry, I totally overlooked it. That directive suits the need. But maybe it would be good to mention that when you use cups-browsed as service in systemd then 'stderr' means 'journal', or like 'syslog' in cupsd. 
Actually, I don't know if there are use cases when cups-browsed isn't running as daemon - if it's only use case is to run as daemon, then IMHO 'stderr' is misleading - because all logs are sent into syslog/journal either way.

**Comment by tillkamppeter** [comment]
Added appropriate hint to man page of `cups-browsed.conf` and `cups-browsed.conf` itself, commit a32dfc38ba6b.

**Comment by zdohnal** [comment]
Thank you, Till!
