### ISSUE TITLE
cups-browsed segfaults

### ISSUE THREAD

**Issue by oglueck** [OpenPrinting/cups-filters#29]
cups-browsed segfauls shortly after startup:
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff64a1666 in strlen () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff64a1666 in strlen () from /lib64/libc.so.6
#1  0x00007ffff64a12ee in strdup () from /lib64/libc.so.6
#2  0x000055555555f84d in new_local_printer (cups_browsed_controlled=0, device_uri=0x0) at utils/cups-browsed.c:764
#3  get_local_printers () at utils/cups-browsed.c:907
#4  update_local_printers () at utils/cups-browsed.c:1156
#5  0x000055555555c8ad in main (argc=1, argv=0x7fffffffdb98) at utils/cups-browsed.c:7949

Looks to me like device-uri is null. I have no local printer and it should add the remote printer from the print server with BrowseRemoteProtocols CUPS.

cups-filters-1.17.9 on Gentoo

**Comment by tillkamppeter** [comment]
This seems to be Issue #16 to me, which was fixed in cups-filters 1.20.1.

**Comment by oglueck** [comment]
confirming, fixed in 1.20.1
