### ISSUE TITLE
printer works normally for all except plain text files, which print as blank

### ISSUE THREAD

**Issue by msbrader** [OpenPrinting/cups-filters#291]
My system currently runs Fedora 32 Linux and was fully updated yesterday
as I write this.  I have a monochrome laser printer, a Brother model
HL-L2360DW.

Although CUPS knows about many Brother models, this is not one of them,
but I was able to make it work by selecting the make/manufacturer as
"Generic" and the model as either of these:

    Generic PCL 6/PCL XL Printer - CUPS+Gutenprint v5.3.3 (en)
    Generic PCL 6/PCL XL Printer Foomatic/pxlmono

I set up two print queues, one using each of these drivers, and found
that the Gutenprint one was faster but the Foomatic one produced better
images.  So I named the queues accordingly, and if I go into
http://localhost:631 and select "Printers", I get this display:

    Queue Name  | Description               | Location       | Make and model                                         | Status
    pixel       | Brother HL-L2360D series  | Local printer  | Generic PCL 6/PCL XL Printer Foomatic/pxlmono          | Idle
    text        | Brother HL-L2360D series  | Local Printer  | Generic PCL 6/PCL XL Printer - CUPS+Gutenprint v5.3.3  | Idle

For years, from time to time, I have been routinely printing image,
PDF, and plain text, files using commands like "lpr -P pixel foo.jpg",
"lpr foo.pdf", and "ls -l | lpr".  (I have lpr defaulting to the "text"
queue.)

I believe these all worked properly when I tested them after updating
from Fedora 30 to Fedora 32.  But the next time I tried to print a
text file, a couple of months later, it printed as blank.  Meanwhile,
printing image or PDF files continues to work normally.  This is true
no matter which of the two drivers (two print queues) I use.

I repeat, this is a monochrome printer, so the situation where it has
color toner but is out of black toner is impossible.

I have the following RPMS with "cups", "gutenprint" or "foomatic" in
their names:

bluez-cups-5.54-1.fc32.x86_64
cups-2.3.3-13.fc32.x86_64
cups-client-2.3.3-13.fc32.x86_64
cups-filesystem-2.3.3-13.fc32.noarch
cups-filters-1.27.5-4.fc32.x86_64
cups-filters-libs-1.27.5-4.fc32.x86_64
cups-ipptool-2.3.3-13.fc32.x86_64
cups-libs-2.3.3-13.fc32.i686
cups-libs-2.3.3-13.fc32.x86_64
cups-pk-helper-0.2.6-9.fc32.x86_64
foomatic-4.0.13-11.fc32.x86_64
foomatic-db-4.0-66.20200526.fc32.noarch
foomatic-db-filesystem-4.0-66.20200526.fc32.noarch
foomatic-db-ppds-4.0-66.20200526.fc32.noarch
gutenprint-5.3.3-2.fc32.x86_64
gutenprint-cups-5.3.3-2.fc32.x86_64
gutenprint-libs-5.3.3-2.fc32.x86_64
python3-cups-2.0.1-1.fc32.x86_64

If I can provide further information to help diagnose this, please
indicate what I should do.  Thanks!

**Comment by zdohnal** [comment]
Hi @msbrader ,

thank you for reporting the issue!

I quickly tried to reproduce with the current info. I created file device print queue with ```foomatic:Generic-PCL_6_PCL_XL_Printer-pxlmono.ppd``` ppd and tried to print a random text file - a PCL file was created after printing. I examined it with [ghostpcl](https://www.ghostscript.com/download/gpcldnld.html) and got following:

```
%%BoundingBox: 18 707 118 755
%%HiResBoundingBox: 18.575999 707.507978 117.845996 754.433977
End of page 1, press <enter> to continue.
```

but I'm not sure whether it is correct or incorrect (never viewed PCL file with ghostpcl before). Do you have the same result in your case (like the same tags, values will be different)?

Either way, please follow [the steps](https://fedoraproject.org/wiki/How_to_debug_printing_problems#My_printer_doesn.27t_print_correctly_or_at_all.2C_but_I_can_see_the_printer_in_print_dialog) and attach the requested files here or file a ticket in bugzilla.redhat.com and attach it there.

**Comment by tillkamppeter** [comment]
Note that recently a text-printing-related bug got fixed, issue #254, by pull request #276. So please try with the newest snapshot of cups-filters. Note also that this fix is also available in the 1.x branch if a distro release is intended before cups-filters 2.0.

**Comment by zdohnal** [comment]
@msbrader  if Till is right, then this scratch build should fix your issue (I backported the patch from #276 in it):

https://koji.fedoraproject.org/koji/taskinfo?taskID=50035788

Please let me know if it fixes the issue.

**Comment by msbrader** [comment]
Thanks, folks.

I followed the steps indicated in zdohnal's first posting and as soon as
I see how to do so, I'll be attaching the files

   text-to-print.txt
   joblog.txt
   text.ppd

The first one being what I tried to print (actually the output of an
ls command), the second one being from output from journalctl, and the
third being the PPD file for the relevant print queue.

I notice that the job log contains this error message:

   Pango-CRITICAL **: 16:37:26.818: pango_font_description_set_size: assertion \'size >= 0\' failed

which seems suggestive to say the least.

As to looking at the PCL file, I would not know where to find that.
Sorry.


Turning to zdohnal's second suggestion, I normally maintain my system only
installing or updating files from Fedora's and other repositories using
dnf.  If this bug has been fixed, presumably this new version of the
cups-filters RPM will show up in the Fedora repository fairly soon and
that will suffice for me, since I'm not in a hurry for this fix.

But I am willing to try installing the "scratch build" experimentally
to see if we can resolve this issue rport.  But I'm not familiar with
that installation process and would have to be told exactly what link
to click on, what files to move or change on my system, how to go back
to the repository version of the RPM afterwards if it doesn't work, etc.

**Comment by msbrader** [comment]
[text-to-print.txt](https://github.com/OpenPrinting/cups-filters/files/5120240/text-to-print.txt)

**Comment by msbrader** [comment]
[joblog.txt](https://github.com/OpenPrinting/cups-filters/files/5120242/joblog.txt)

**Comment by msbrader** [comment]
[text.ppd.txt](https://github.com/OpenPrinting/cups-filters/files/5120251/text.ppd.txt)

**Comment by zdohnal** [comment]
@msbrader From logs:

```
Aug 24 16:37:26 b cupsd[28428]: 5 filters for job:
Aug 24 16:37:26 b cupsd[28428]: texttopaps (text/plain to application/postscript, cost 30)
Aug 24 16:37:26 b cupsd[28428]: gstopdf (application/postscript to application/pdf, cost 0)
Aug 24 16:37:26 b cupsd[28428]: pdftopdf (application/pdf to application/vnd.cups-pdf, cost 66)
Aug 24 16:37:26 b cupsd[28428]: gstoraster (application/vnd.cups-pdf to application/vnd.cups-raster, cost 99)
Aug 24 16:37:26 b cupsd[28428]: rastertogutenprint.5.3 (application/vnd.cups-raster to printer/text, cost 100)
```

The print job goes via ```texttopaps``` filter from ```paps``` package. Would you mind trying to print without ```paps``` package, so that we can find out if the error is in ```cups-filters``` package?

You can just run:
```
$ sudo dnf remove paps
```
and try to print again. If the problem remains or other problem showed up, please send a job log for this printing. If the problem goes away, then the issue is in ```paps``` - then please report the issue to ```paps``` project.
Then you can revert back to ```paps``` if you want by installing it again (```$ sudo dnf install paps```) or by undoing dnf history. If you didn't do any other dnf action in the time frame after uninstalling paps, you can use the ```last``` keyword, otherwise you need to look into ```$ sudo dnf history list``` and find the transaction ID:

 ```sudo dnf history undo last```
or
```sudo dnf history undo <transaction_ID>```

but please keep in mind that paps needs to be uninstalled if we are supposed to investigate the issue under ```cups-filters```.

Ad installing scratch build (try it if you find out uninstalling ```paps``` doesn't help):

If you open the link, you will see a link starting with 'BuildArch' word on the page - click on it - and you will get to the task page and links to binary rpms (ones with x86_64 in their names) are at the end of the page.
Then take links to rpms (right-click on the link - choose 'Copy link location'. cups-filters and cups-filters-libs should suffice) and give them as arguments of ```dnf install``` and run it.
Again, you can revert the previous transaction via ```dnf history undo``` described above, or by ```dnf downgrade cups-filters```.

**Comment by msbrader** [comment]
Aha!  With paps uninstalled, I can now print plain text files.  (I don't like the font I'm now getting
as well as the one I had with paps, but that's a relatively trivial complaint.  Is there a way to
configure CUPS to select another one?)  Thanks very much for spotting this.

I am attaching the job log for my test with paps uninstalled.

**Comment by msbrader** [comment]
[newjoblog.txt](https://github.com/OpenPrinting/cups-filters/files/5121999/newjoblog.txt)

**Comment by zdohnal** [comment]
@msbrader 

> If the problem remains or other problem showed up, please send a job log for this printing. 

Then there is no need for new job log. Would you mind closing the issue?

**Comment by msbrader** [comment]
Done.

**Comment by zdohnal** [comment]
Thank you!
