### ISSUE TITLE
`driverless cat` now requires `driverless:`/`driverless-fax:` prefix to device uri

### ISSUE THREAD

**Issue by zdohnal** [OpenPrinting/cups-filters#295]
Hi,

with 1.28.0, the device uri which is used with ```driverless cat``` is expected to have one of two prefixes:

```
driverless:
driverless-fax
```

and it doesn't take clean ```ipp:``` uri - if the clean ipp uri is supplied, ```driverless``` fall backs to ```list_printers()```.

Is it expected? IMO ```driverless cat``` can be able to work with simple ```ipp``` uri. The fix is simple, I can provide it if it is really a bug.

**Comment by tillkamppeter** [comment]
Have seen this one, too. I will fix it soon.
