### ISSUE TITLE
cups-browsed segfaults with recent glibc 2.32

### ISSUE THREAD

**Issue by andyrtr** [OpenPrinting/cups-filters#297]
Some Arch linux users are faced with broken driverless printing probably since our toolchain update with cups-filters 1.27.x and 1.28.0. I'm affected on one of my system where gtk based applications print "pdf-1.5" and  wild characters. I couldn't catch some useful info from debug log but get a repeatable segmentation fault when invoking like this:

/usr/bin/cups-browsed -v
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Wed Aug 26 15:07:17 2020 Reading command line option -v, turning on debug mode (Log on standard error).
Wed Aug 26 15:07:17 2020 cups-browsed of cups-filters version 1.28.0 starting.
Wed Aug 26 15:07:17 2020 Reading config: BrowseRemoteProtocols DNSSD,CUPS
Wed Aug 26 15:07:17 2020 Reading config: CreateIPPPrinterQueues Driverless
Wed Aug 26 15:07:17 2020 No "Browse..." line at all, accept all servers ("BrowseOrder Deny,Allow").
Wed Aug 26 15:07:17 2020 main() in THREAD 140737326924800

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7950edb in fclose@@GLIBC_2.2.5 () from /usr/lib/libc.so.6
(gdb) set logging file /tmp/trace.log
(gdb) set logging on
Copying output to /tmp/trace.log.
Copying debug output to /tmp/trace.log.
(gdb) thread apply all bt full

Thread 1 (Thread 0x7ffff660c400 (LWP 73791)):
#0  0x00007ffff7950edb in fclose@@GLIBC_2.2.5 () at /usr/lib/libc.so.6
#1  0x000055555555f82a in debug_printf (format=0x55555557dc86 "main() in THREAD %ld\n") at utils/cups-browsed.c:766
        fp1 = 0x1
        fp2 = 0x90
        curtime = 1598447237
        buf = "Wed Aug 26 15:07:17 2020\000\000\000\000\000\000\000\000\016", '\000' <repeats 15 times>, "\060\000\000\000\000\000\000\000\003\000\000\000\000\000\000"
        arglist = {{gp_offset = 16, fp_offset = 48, overflow_arg_area = 0x7fffffffe570, reg_save_area = 0x7fffffffe490}}
        log_file_size = 1147032
#2  0x000055555555d36c in main (argc=2, argv=0x7fffffffe768) at utils/cups-browsed.c:12340
        ret = 1
        http = <optimized out>
        i = <optimized out>
        val = <optimized out>
        p = <optimized out>
        proxy = 0x0
        error = 0x0
        subscription_id = 0
        action = {__sigaction_handler = {sa_handler = 0x7ffff7ce6ee0, sa_sigaction = 0x7ffff7ce6ee0}, sa_mask = {__val = {140737349773711, 140737351085208, 140737488348736, 140737488348652, 140737488348736, 140737351085208, 140737350805676, 93823560581123, 21330060182, 0, 0, 0, 0, 0, 0, 0}}, sa_flags = 0, sa_restorer = 0x0}

We have updated to glibc 2.32-2 / gcc-libs 10.2.0-1 / binutils 2.35-1 / libxcrypt 4.4.16-3.

**Comment by zdohnal** [comment]
Hi @andyrtr ,

would you mind sharing your ```/etc/cups/cups-browsed.conf```? Did you have cups-browsed debug logging set to a file in the past?

In my opinion it is not connected to new glibc - ```lfp``` is NULL or corrupted - would you mind printing out its contents in ```gdb```?

**Comment by andyrtr** [comment]
Attaching my [cups-browsed.conf](https://github.com/OpenPrinting/cups-filters/files/5161877/cups-browsed.conf.txt)

As of today I can't reproduce it anymore. We had another toolchain update rebuilt against latest linux-kernel-headers 5.8, poppler 20.09.0, systemd and liblouis updates. Now I can print again to my printer using IPP. cups-browsed doesn't seem to crash anymore here. I've tried downgrading the toolchain and several releated packages of cups-filters but cannot reproduce it anymore.

Feel free to close this bug.

**Comment by zdohnal** [comment]
@tillkamppeter would you mind closing the issue?

**Comment by tillkamppeter** [comment]
No problem, not having a reproducer it is worthless. If there is actually a bug and someone else hits it, he will report it. Closing ...
