### ISSUE TITLE
[Bug report] no data of formatted character

### ISSUE THREAD

**Issue by ChoiChoongHo94** [OpenPrinting/cups-filters#299]
When I deleted the driverless printer set the default printer, cups-browsed was killed.

the reason is
https://github.com/OpenPrinting/cups-filters/blob/15b08e8366692033f032c2d17f245916f325a27b/utils/cups-browsed.c#L6647

this must be modified to bellow.

`debug_printf("Remoted %s as ...", printer);`

**Comment by tillkamppeter** [comment]
Fixed in commit d2aed0ae (master branch) and 0936df681b (1.x branch). Thank you very much for the bug report.
