### ISSUE TITLE
'Bad substitution' error during configure phase

### ISSUE THREAD

**Issue by barul42** [OpenPrinting/cups-filters#300]
Hello,

Using an up-to-date Gentoo installation, I can't install cups-filters (tested with 1.27.4 and 1.27.5); the configure phase fails if the script finds more than 1 result for the dejavu font.
Here's the error I get :
```
checking for "/usr/share/fonts/dejavu/DejaVuSans.ttf
/usr/share/fonts/ms-fonts/DejaVuSans.ttf"... ./configure: line 19173: ${ac_cv_file__usr_share_fonts_dejavu_DejaVuSans_ttf _usr_share_fonts_ms_fonts_DejaVuSans_ttf+:}: bad substitution
```

If I rename one of the .ttf files to it doesn't match 'DejaVuSans.ttf', it compiles normally.

Is it possible for the script to stop at the first result it finds?

**Comment by tillkamppeter** [comment]
Fixed in commit e50fb6ca04 on master branch and in 0d91eceaf on 1.x branch.
Thank you very much for your bug report.
