### ISSUE TITLE
Systemd timeout when cups-browsed.service is stopping

### ISSUE THREAD

**Issue by LittleBigQuark** [OpenPrinting/cups-filters#310]
**cups version the issue has been seen with**
> 2.3.3-3

**Used distribution**
> Manjaro Linux 20.1 Xfce

**Expected behaviour you didn't see**
 > no error timeout before systemd[1]: Stopped Make remote CUPS printers available locally

**Unexpected behaviour you saw**
 > systemd[1]: cups-browsed.service: Failed with result 'timeout'.

**Steps to reproduce the problem**
> systemctl stop cups-browsed

**Comment by tillkamppeter** [comment]
Got already reported earlier as issue #298 and fixed in cups-filters 1.28.2.
