### ISSUE TITLE
Not able to get ppd list from cups server.

### ISSUE THREAD

**Issue by prashant13patil** [OpenPrinting/cups-filters#317]
Distro Name : Ubuntu 20.10
Printers : All
 
While adding printer through hplip not able to get get ppd list from cups server.
From localhost also not able select hp ppd.
     Steps to reproduce:
1.	Open browser
2.	Go to localhost:631 > administration
3.	Add printer > select printer  ( not ask for custom ppd direct redirect to successful window)
 
This issue is inconsistent 5-6 time not working out 10 tries.
The same code is working fine on ubuntu 20.04 which has same cups version as 20.10.
 
Installed Package:
Cups     : 2.3.3
Cups-devel : 2.3.3-3
Cups-image : 2.2.3-3
 
Error with our code:
Error : No ppd found for model “Model name”
 
 
Any update or changes that will fix this issue.

**Comment by tillkamppeter** [comment]
Looks like an issue of CUPS and not cups-filters for me. Please report on the [CUPS project](https://github.com/OpenPrinting/cups) on this site. Thanks.
