### ISSUE TITLE
Making gutenprint the default driver

### ISSUE THREAD

**Issue by es20490446e** [OpenPrinting/cups-filters#324]
It seems that many printers don't support printing on glossy paper except if they are using gutenprint. For example, see [here](https://askubuntu.com/questions/1249646/impossible-to-select-glossy-paper-when-printing/1295643).

That is because the black ink isn't really designed to print on that type of paper, so what gutenprint or drivers on Windows do is printing black as a light grey. Otherwise the ink never dries out.

The thing is that without gutenprint CUPS doesn't seem capable of doing that, at least for many printers. So my suggestion is simple, that when you connect a new printer to the system, if gutenprint is available, it is selected as the default driver instead of the raw printer drivers.

**Comment by tillkamppeter** [comment]
Which operating system are you using?
What do you mean with "raw printer drivers"?
Which is your printer model?
Note that cups-filters does not auto-select the printer driver. In most cases it is [system-config-printer](https://github.com/OpenPrinting/system-config-printer) which actually does. Please report your issue there. thanks.

**Comment by es20490446e** [comment]
Reported [here](https://github.com/OpenPrinting/system-config-printer/issues/188).

But I have doubts that's the software, as it isn't installed on my Linux distro, Manjaro.

Any idea what could be the package in charge of automatically configuring the printer? Here's the [list of printing packages installed](https://gitlab.manjaro.org/packages/extra/manjaro-printer/-/blob/master/PKGBUILD#L12).
