### ISSUE TITLE
cups/cgi-bin/help.cgi File too large

### ISSUE THREAD

**Issue by Jonsonx** [OpenPrinting/cups-filters#325]
Hi,
I install CUPS 2.3.3 for Raspbian os,

I can reach http://localhost:631/ but nothing else. http://localhost:631/admin,for example, gives me the internal server error. ,could you give us some advices? Thanks
D [01/Dec/2020:12:44:32 +0800] [Client 376] GET /help/admin.html HTTP/1.1
D [01/Dec/2020:12:44:32 +0800] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"
D [01/Dec/2020:12:44:32 +0800] [Client 376] Read: status=200, state=3
D [01/Dec/2020:12:44:32 +0800] [Client 376] No authentication data provided.
D [01/Dec/2020:12:44:32 +0800] [Client 376] Processing GET /help/admin.html
D [01/Dec/2020:12:44:32 +0800] [CGI] argv[0] = "/usr/lib/cups/cgi-bin/help.cgi"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[0] = "CUPS_CACHEDIR=/var/cache/cups"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[1] = "CUPS_DATADIR=/usr/share/cups"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[2] = "CUPS_DOCROOT=/usr/share/doc/cups"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[3] = "CUPS_FONTPATH=/usr/share/cups/fonts"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[4] = "CUPS_REQUESTROOT=/var/spool/cups"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[5] = "CUPS_SERVERBIN=/usr/lib/cups"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[6] = "CUPS_SERVERROOT=/etc/cups"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[7] = "CUPS_STATEDIR=/var/run/cups"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[8] = "HOME=/var/spool/cups/tmp"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[9] = "PATH=/usr/lib/cups/filter:/usr/bin:/usr/sbin:/bin:/usr/bin"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[10] = "SERVER_ADMIN=root@localhost"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[11] = "SOFTWARE=CUPS/2.3.3"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[12] = "TMPDIR=/var/spool/cups/tmp"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[13] = "USER=root"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[14] = "CUPS_MAX_MESSAGE=2047"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[15] = "CUPS_SERVER=localhost"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[16] = "CUPS_ENCRYPTION=IfRequested"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[17] = "IPP_PORT=631"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[18] = "LANG=zh_TW.UTF8"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[19] = "REDIRECT_STATUS=1"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[20] = "GATEWAY_INTERFACE=CGI/1.1"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[21] = "SERVER_NAME=10.129.93.163"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[22] = "SERVER_PORT=631"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[23] = "REMOTE_ADDR=10.129.93.160"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[24] = "REMOTE_HOST=10.129.93.160"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[25] = "SCRIPT_NAME=/help/admin.html"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[26] = "SCRIPT_FILENAME=/usr/share/doc/cups/help/admin.html"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[27] = "PATH_INFO=/admin.html"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[28] = "SERVER_PROTOCOL=HTTP/1.1"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[29] = "HTTP_USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[30] = "HTTP_REFERER=http://10.129.93.163:631/"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[31] = "REQUEST_METHOD=GET"
D [01/Dec/2020:12:44:32 +0800] [CGI] envp[32] = "QUERY_STRING="
D [01/Dec/2020:12:44:32 +0800] [CGI] Started /usr/lib/cups/cgi-bin/help.cgi (PID 28491)
I [01/Dec/2020:12:44:32 +0800] [Client 376] Started "/usr/lib/cups/cgi-bin/help.cgi" (pid=28491, file=12)
D [01/Dec/2020:12:44:32 +0800] [Client 376] Waiting for CGI data.
D [01/Dec/2020:12:44:32 +0800] Report: clients=3
D [01/Dec/2020:12:44:32 +0800] Report: jobs=0
D [01/Dec/2020:12:44:32 +0800] Report: jobs-active=0
D [01/Dec/2020:12:44:32 +0800] Report: printers=0
D [01/Dec/2020:12:44:32 +0800] Report: stringpool-string-count=1037
D [01/Dec/2020:12:44:32 +0800] Report: stringpool-alloc-bytes=2976
D [01/Dec/2020:12:44:32 +0800] Report: stringpool-total-bytes=9816
D [01/Dec/2020:12:44:32 +0800] [CGI] org.cups.sid cookie not found, initializing!
D [01/Dec/2020:12:44:32 +0800] [CGI] /usr/lib/cups/cgi-bin/help.cgi: symbol lookup error: /usr/lib/cups/cgi-bin/help.cgi: undefined symbol: cupsHashString
D [01/Dec/2020:12:44:32 +0800] [Client 376] CGI data ready to be sent.
D [01/Dec/2020:12:44:32 +0800] [Client 376] con->http=0x55b23e08
D [01/Dec/2020:12:44:32 +0800] [Client 376] cupsdWriteClient error=0, used=0, state=HTTP_STATE_GET_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=2147483647, response=(nil)(), pipe_pid=28491, file=12
D [01/Dec/2020:12:44:32 +0800] [Client 376] Waiting for CGI data.
D [01/Dec/2020:12:44:32 +0800] [Client 376] cupsdSendHeader: code=500, type="text/html", auth_type=0
D [01/Dec/2020:12:44:32 +0800] [Client 376] Waiting for request.
D [01/Dec/2020:12:44:32 +0800] [Client 376] Closing because Keep-Alive is disabled.
D [01/Dec/2020:12:44:32 +0800] [Client 376] Closing connection.
D [01/Dec/2020:12:44:32 +0800] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
D [01/Dec/2020:12:44:32 +0800] PID 28491 (/usr/lib/cups/cgi-bin/help.cgi) stopped with status 127 (File too large)
D [01/Dec/2020:12:44:57 +0800] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"
D [01/Dec/2020:12:44:57 +0800] [Client 378] Server address is "[v1.::1]".
D [01/Dec/2020:12:44:57 +0800] [Client 378] Accepted from localhost:40018 (IPv6)
D [01/Dec/2020:12:44:57 +0800] [Client 378] Waiting for request.
D [01/Dec/2020:12:44:57 +0800] cupsdSetBusyState: newbusy="Active clients", busy="Active clients"
D [01/Dec/2020:12:44:57 +0800] [Client 379] Server address is "[v1.::1]".
D [01/Dec/2020:12:44:57 +0800] [Client 379] Accepted from localhost:40020 (IPv6)
D [01/Dec/2020:12:44:57 +0800] [Client 379] Waiting for request.
D [01/Dec/2020:12:44:57 +0800] [Client 378] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
D [01/Dec/2020:12:44:57 +0800] [Client 378] Closing connection.
D [01/Dec/2020:12:44:57 +0800] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
D [01/Dec/2020:12:44:57 +0800] [Client 379] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
D [01/Dec/2020:12:44:57 +0800] [Client 379] Closing connection.
D [01/Dec/2020:12:44:57 +0800] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
D [01/Dec/2020:12:44:57 +0800] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"
D [01/Dec/2020:12:44:57 +0800] [Client 380] Server address is "127.0.0.1".
D [01/Dec/2020:12:44:57 +0800] [Client 380] Accepted from localhost:37910 (IPv4)
D [01/Dec/2020:12:44:57 +0800] [Client 380] Waiting for request.
D [01/Dec/2020:12:44:57 +0800] [Client 380] POST / HTTP/1.1
D [01/Dec/2020:12:44:57 +0800] cupsdSetBusyState: newbusy="Active clients", busy="Active clients"
D [01/Dec/2020:12:44:57 +0800] [Client 380] Read: status=200, state=6
D [01/Dec/2020:12:44:57 +0800] [Client 380] No authentication data provided.
D [01/Dec/2020:12:44:57 +0800] [Client 380] Read: status=100, state=6
D [01/Dec/2020:12:44:57 +0800] [Client 380] Read: status=100, state=6
D [01/Dec/2020:12:44:57 +0800] [Client 380] Read: status=100, state=6
D [01/Dec/2020:12:44:57 +0800] [Client 380] Read: status=100, state=6
D [01/Dec/2020:12:44:57 +0800] [Client 380] Read: status=100, state=6
D [01/Dec/2020:12:44:57 +0800] [Client 380] 1.1 CUPS-Get-Default 1
D [01/Dec/2020:12:44:57 +0800] CUPS-Get-Default
D [01/Dec/2020:12:44:57 +0800] CUPS-Get-Default client-error-not-found: No default printer.
D [01/Dec/2020:12:44:57 +0800] [Client 380] Returning IPP client-error-not-found for CUPS-Get-Default (no URI) from localhost.
D [01/Dec/2020:12:44:57 +0800] [Client 380] Content-Length: 110
D [01/Dec/2020:12:44:57 +0800] [Client 380] cupsdSendHeader: code=200, type="application/ipp", auth_type=0
D [01/Dec/2020:12:44:57 +0800] [Client 380] con->http=0x55b23e08
D [01/Dec/2020:12:44:57 +0800] [Client 380] cupsdWriteClient error=0, used=0, state=HTTP_STATE_POST_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=110, response=0x55b1b658(IPP_STATE_DATA), pipe_pid=0, file=-1
D [01/Dec/2020:12:44:57 +0800] [Client 380] Writing IPP response, ipp_state=IPP_STATE_DATA, old wused=0, new wused=0
D [01/Dec/2020:12:44:57 +0800] [Client 380] bytes=0, http_state=0, data_remaining=110
D [01/Dec/2020:12:44:57 +0800] [Client 380] Flushing write buffer.
D [01/Dec/2020:12:44:57 +0800] [Client 380] New state is HTTP_STATE_WAITING
D [01/Dec/2020:12:44:57 +0800] [Client 380] Waiting for request.
D [01/Dec/2020:12:44:57 +0800] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
D [01/Dec/2020:12:44:57 +0800] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"
D [01/Dec/2020:12:44:57 +0800] [Client 381] Server address is "[v1.::1]".
D [01/Dec/2020:12:44:57 +0800] [Client 381] Accepted from localhost:40024 (IPv6)
D [01/Dec/2020:12:44:57 +0800] [Client 381] Waiting for request.
D [01/Dec/2020:12:44:57 +0800] [Client 381] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
D [01/Dec/2020:12:44:57 +0800] [Client 381] Closing connection.
D [01/Dec/2020:12:44:57 +0800] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
D [01/Dec/2020:12:44:57 +0800] [Client 380] POST / HTTP/1.1
D [01/Dec/2020:12:44:57 +0800] cupsdSetBusyState: newbusy="Active clients", busy="Not busy"
D [01/Dec/2020:12:44:57 +0800] [Client 380] Read: status=200, state=6
D [01/Dec/2020:12:44:57 +0800] [Client 380] No authentication data provided.
D [01/Dec/2020:12:44:57 +0800] [Client 380] Read: status=100, state=6
D [01/Dec/2020:12:44:57 +0800] [Client 380] Read: status=100, state=6
D [01/Dec/2020:12:44:57 +0800] [Client 380] Read: status=100, state=6
D [01/Dec/2020:12:44:57 +0800] [Client 380] Read: status=100, state=6
D [01/Dec/2020:12:44:57 +0800] [Client 380] Read: status=100, state=6
D [01/Dec/2020:12:44:57 +0800] [Client 380] 1.1 CUPS-Get-Printers 1
D [01/Dec/2020:12:44:57 +0800] CUPS-Get-Printers
D [01/Dec/2020:12:44:57 +0800] CUPS-Get-Printers client-error-not-found: No destinations added.
D [01/Dec/2020:12:44:57 +0800] [Client 380] Returning IPP client-error-not-found for CUPS-Get-Printers (no URI) from localhost.
D [01/Dec/2020:12:44:57 +0800] [Client 380] Content-Length: 113
D [01/Dec/2020:12:44:57 +0800] [Client 380] cupsdSendHeader: code=200, type="application/ipp", auth_type=0
D [01/Dec/2020:12:44:57 +0800] [Client 380] con->http=0x55b23e08
D [01/Dec/2020:12:44:57 +0800] [Client 380] cupsdWriteClient error=0, used=0, state=HTTP_STATE_POST_SEND, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=113, response=0x55b1b3d0(IPP_STATE_DATA), pipe_pid=0, file=-1
D [01/Dec/2020:12:44:57 +0800] [Client 380] Writing IPP response, ipp_state=IPP_STATE_DATA, old wused=0, new wused=0
D [01/Dec/2020:12:44:57 +0800] [Client 380] bytes=0, http_state=0, data_remaining=113
D [01/Dec/2020:12:44:57 +0800] [Client 380] Flushing write buffer.
D [01/Dec/2020:12:44:57 +0800] [Client 380] New state is HTTP_STATE_WAITING
D [01/Dec/2020:12:44:57 +0800] [Client 380] Waiting for request.
D [01/Dec/2020:12:44:57 +0800] cupsdSetBusyState: newbusy="Not busy", busy="Active clients"
D [01/Dec/2020:12:45:12 +0800] [Client 380] HTTP_STATE_WAITING Closing for error 32 (Broken pipe)
D [01/Dec/2020:12:45:12 +0800] [Client 380] Closing connection.
D [01/Dec/2020:12:45:12 +0800] cupsdSetBusyState: newbusy="Not busy", busy="Not busy"
D [01/Dec/2020:12:45:12 +0800] cupsdAddCert: Adding certificate for PID 0

**Comment by tillkamppeter** [comment]
This has nothing to do with cups-filters, it is a problem of CUPS itself. Please report this issue on the [CUPS project](https://github.com/OpenPrinting/cups) on this site.
