### ISSUE TITLE
Change handling of "Gray" to match CUPS driverless behavior

### ISSUE THREAD

**Issue by IslandCow** [OpenPrinting/cups-filters#326]
When handling for "Gray" was added to cupsRasterParseIPPOptions, it was mapped to 3 or CUPS_CSPACE_K.  However, in CUPS PPD generation, that was only used for bi-level.  Gray (what was generated for monochrome) should be mapped to CUPS_CSPACE_SW or 18.  For convenience, the reference from CUPS is included below.

https://github.com/apple/cups/blob/9240cd7/cups/ppd-cache.c#L3767

**Comment by tillkamppeter** [comment]
Thanks for the bug report and pull request. I have fixed this now for more, hopefully all cases where the PPD generator and cupsRasterParseIPPOptions() mismatch, commit 1dc90ce0f.
