### ISSUE TITLE
cups-browsed should reload-or-restart after network changes

### ISSUE THREAD

**Issue by DerPit** [OpenPrinting/cups-filters#33]
I have BrowsePoll lines for the main network environments where I use my laptop.  But when changing to such a network (replugging, suspend/resume) I cannot use those printers:  They are detected by cups:
```
woodstock:~% lpstat -a
ml2850 accepting requests since Sun 11 Mar 2018 08:24:14 CET
```

but when trying to print there is an error message:
```
E [11/Mar/2018:08:24:14 +0100] [Client 7] Returning IPP client-error-bad-request for CUPS-Add-Modify-Printer (ipp://localhost:631/printers/ml2850) from localhost
E [11/Mar/2018:08:33:43 +0100] [Job 100] No destination host name supplied by cups-browsed for printer \"ml2850\", is cups-browsed running?
```
I have to restart cups-browsed to be able to print to this printer.  As this will also delete already submitted print jobs, such a restart should happen automatically after network changes (and/or resumes?)

(See also bugreport https://bugzilla.opensuse.org/show_bug.cgi?id=1084799)

**Comment by dheeraj135** [comment]
@tillkamppeter This issue has already been resolved. Please check the bugzilla report.
