### ISSUE TITLE
versioning.h

### ISSUE THREAD

**Issue by prlw1** [OpenPrinting/cups-filters#334]
ppd/ppd.h appears to be a public header file which gets installed. ppd.h includes versioning.h, which however does not appear to get installed, making ppd.h hard to use.

**Comment by surajkulriya** [comment]
hello @prlw1 
  I am not being able to understand what you are trying to say. Can you please elaborate it a little bit more.
Thanks.

**Comment by prlw1** [comment]
- install cups-filter
- write some code which does #include <ppd/ppd.h> (e.g., ps-printer-app.c)
- watch compilation fail with fatal error: versioning.h: No such file or directory

because the public header ppd/ppd.h is installed, but not its dependent header versioning.h

clearer?

**Comment by tillkamppeter** [comment]
Fixed in commit ec97810c3.
Thank you for the bug report.
