### ISSUE TITLE
signal.h & implicitclass.c

### ISSUE THREAD

**Issue by prlw1** [OpenPrinting/cups-filters#335]
backend/implicitclass.c should #include <signal.h> as it uses sigaction, sigset or signal. (ie. I think it is need no matter which combination of HAVE_ autoconf variables are defined.)

**Comment by surajkulriya** [comment]
hello @prlw1  
please note that we are including <sys/wait.h> in backend/implicitclass.c file that itself includes <signal.h> so basically we have indirectly included <signal.h> file in backend/implicitclass.c file too.

please do ask any other query too if you have 
Thanks :-)

**Comment by prlw1** [comment]
But that is OS dependent and not portable.

```
$ grep signal.h /usr/include/sys/wait.h
$
```
Please include the header for the functions you are calling.

**Comment by tillkamppeter** [comment]
Fixed in 3511aa92c0.
Thanks for the bug report.
