### ISSUE TITLE
getting symbol lookup error for pdftopdf and ghostscript

### ISSUE THREAD

**Issue by surajkulriya** [OpenPrinting/cups-filters#338]
I am getting the above mentioned error when trying to print any file.
error_log:  [cups_errors.txt](https://github.com/OpenPrinting/cups-filters/files/5793030/cups_errors.txt)
PPD:   [Officejet_7110.ppd.txt](https://github.com/OpenPrinting/cups-filters/files/5793035/Officejet_7110.ppd.txt)
PS: When I am using cups-filters-1.27.5 the error is not observed, it's only observed when I am using the latest code of cups-filters from this github repo.
I am literally stuck at this point and any help will be appreciated.
Thank you 

cups version:2.3.3op1 (latest one from github repo)
cups-filters version: latest one from this repo
OS:ubuntu 20.04

**Comment by tillkamppeter** [comment]
Are you sure that you have completely replaced all components of cups-filters with the ones of the newest version?

Especially the cups-filters from the GitHub repo (master branch) is the new 2.x generation (with API changes) and the distros come with trhe old 1.x generation (1.x branch on GitHub). Therefore it is important that both the filters and utilities and the libraries get replaced by the new ones.

Note that distributions install software with `/usr` prefix, into `/usr/lib/`, `/usr/bin/`, ... and the default when doing `./configure; make; make install` is the `/usr/local` prefix, meaning that the stuff gets installed in `/usr/local/lib/`, ...

**Comment by surajkulriya** [comment]
@tillkamppeter  sir actually I installed it using default prefix `/usr/local` and the cups 2.3.3op1 too was installed using the default prefix `/usr/local`.   I tried installing both (cups and cups filters) using prefix `/usr` but then cups stopped working. I reloaded system deamon, restarted cups again and enbaled it too but it didn't start working even then.
So I installed both of them(cups and cups-filters) again using default prefix `/usr/local` and started cups daemon using `sudo /usr/sbin/cupsd -f`.
It started working again using this but I got the same error of symbol lookup when I tried to print using the ppd mentioned above.

**Comment by surajkulriya** [comment]
Update: I got the problem done. I installed both(cups and cups-filters) in my local dir `/home/surajkulriya/cupsContent` and it's working and printing fine now with no errors. :-)
By the way I still have a doubt. It's logging error in `/var/log/cups/error_log` file why it's not logging in my custom directory `/home/surajkulriya/cupsContent/var/log/cups/error_log`.

**Comment by tillkamppeter** [comment]
On the `./configure` command line you have an option names `--localstatedie` to define where things go which usually would go to `/var`. Probably you have to add `--localstatedir=/home/surajkulriya/cupsContent/var` to your `./configure` command line.

**Comment by surajkulriya** [comment]
Thank you sir for help
