### ISSUE TITLE
Brother MFC-L2700DW printing issues (cups 1.28.7, driverless)

### ISSUE THREAD

**Issue by voland66** [OpenPrinting/cups-filters#343]
OS: Fedora 33
Cups version: 1.28.7
Driver: Brother MFC-L2700DW series, Fax, driverless, cups-filters 1.28.7 (grayscale, 2-sided printing)
Printer: Brother MFC-L2700DW (same issue with MFC-L2710DW).

When the printer is configured with discovered network URI 
dnssd://Brother%20MFC-L2700DW%20series._pdl-datastream._tcp.local/?uuid=
the printer prints infinite empty pages.

When the same printer is configured with discovered network URI 
ipp://Brother%20MFC-L2700DW%20series._ipp._tcp.local/
the printer says "Receiving data" and then goes back to sleep, nothing is printed.

When the printer is configured with URI containing local ip address (including "/ipp"), the driverless option above is not available. However, when the printer is configured with one of the discovered URI's above, either dnssd or ipp, and then URI is changed to local address:
ipp://xxx.xxx.xxx.xxx/ipp
the print job completes as expected.

**Comment by pranshukharkwal** [comment]
Hi @voland66 
Just to confirm, are you using the drivers downloaded from here? 
https://support.brother.com/g/b/downloadend.aspx?c=us_ot&lang=en&prod=mfcl2700dw_us_eu_as&os=128&dlid=dlf006893_000&flang=4&type3=625&dlang=true

Also, please share your log files (both error and access (can be found in /var/log/cups)) with debug logging turned on (can be turned on using cupsctl --debug-logging.

**Comment by pranshukharkwal** [comment]
Hi @voland66 
Could you please share the ppd file generated for this printer. You can find it in '/etc/cups/ppd' (there will be a file with the same name as of the printer)
Also, please share your log files (both error and access (can be found in /var/log/cups)) with debug logging turned on (can be turned on using cupsctl --debug-logging.)

**Comment by voland66** [comment]
I am not using drivers from the Brother website (they require 32 bit libraries).
I am using IPP everywhere driverless option in cups. 
There are usually 3 entries in the "Discovered network printers list:
1. One entry uses URI "ipp://Brother%20MFC-L2700DW%20series._ipp._tcp.local/" and gives me a choice of two drivers:  
- Selecting "Brother MFC_L2700DW series -- driverless, cups filters, 1.28.7 (en)" creates the first attached ppd, printer1.txt. When printing a test page nothing comes out, however, cups thinks that print completed successfully and no error logs are generated. Replacing "ipp://Brother%20MFC-L2700DW%20series._ipp._tcp.local/" in printers.conf with an explicit printer URI, "ipp://192.168.1.2/ipp", leads to a successful printout.

-  Selecting  "Brother MFC-L2700DW series -- IPP Everywhere" creates the attached printer2.txt. I have just been able to print the test page successfully in this configuration. However, I seem to remember some unsuccessful attempts in the past.

2&3. The other two entries use URIs "dnssd://Brother%20MFC-L2700DW%20series._pdl-datastream._tcp.local/?uuid=e3248000-80ce-11db-8000-30055caebc5e" and "lpd://brother/BINARY_P1" (brother is the printer name on the local network, so it is correct). Both of these entries offer one driver choice:  "Brother MFC-L2700DW series (driverless) (Brother MFC-L2700DW series)". Configuring the printer this way creates printer1.txt. With either of the two URIs an attempt to print a test page results in an apparently infinite number of empty pages.

[printer1.txt](https://github.com/OpenPrinting/cups-filters/files/6016842/printer1.txt)
[printer2.txt](https://github.com/OpenPrinting/cups-filters/files/6016843/printer2.txt)

**Comment by tillkamppeter** [comment]
@voland66, what we really need are error_log files from you to find out why you can print with the straight IPP URI `ipp://192.168.1.2/ipp` and not with the DNS-SD-service-name-based URI `ipp://Brother%20MFC-L2700DW%20series._ipp._tcp.local/`.

So please first issue the command
```
cupsctl --debug-logging
```
Then create a print queue selecting the URI `ipp://Brother%20MFC-L2700DW%20series._ipp._tcp.local/` and the PPD/model "Brother MFC_L2700DW series -- driverless, cups filters, 1.28.7 (en)".

With this, print a job. The job will not print as you described. Copy your `/var/log/cups/error_log` file, rename the copy to a name with `.txt` extension and attach it here. Then run the command `cancel -a` to clear the queue for the next test.

Now stop the CUPS daemon, edit your `/etc/cups/printers.conf` for this print queue to use the `ipp://192.168.1.2/ipp` URI (never edit `/etc/cups/printers.conf` while the CUPS daemon is running!). Again print a job (it will get correctly printed) and again copy your `/var/log/cups/error_log` file, rename the copy to a name with `.txt` extension and attach it here.

Thanks in advance.

**Comment by voland66** [comment]
It turns out I did not find an error log before because it is being saved to journal instead of /var/log/cups. I am attaching error logs obtained by "journalctl -u cups.service -p7". The logs are not limited to errors only but when I used  "-p3" flag there was no output for the relevant time period. If there is a way to limit output only to the relevant entries, please let me know.

For error1.txt URI was dnssd://Brother%20MFC-L2700DW%20series._pdl-datastream._tcp.local/?uuid=e3248000-80ce-11db-8000-30055caebc5e which prints empty pages, 
For error2.txt URI was ipp://Brother%20MFC-L2700DW%20series._ipp._tcp.local which does not print anything
For error3.txt URI was ipp://brother.lan/ipp (this is resolved to local URL by the router) and it prints correctly

[error1.txt](https://github.com/OpenPrinting/cups-filters/files/6025825/error1.txt)
[error2.txt](https://github.com/OpenPrinting/cups-filters/files/6025826/error2.txt)
[error3.txt](https://github.com/OpenPrinting/cups-filters/files/6025827/error3.txt)

**Comment by pranshukharkwal** [comment]
@voland66 
Could you pleases poll get-printer-attributes IPP response from your printer and attach the results.
You may use `ipptool -tv URI get-printer-attributes-2.0.test > attrs.txt` or `ipptool -tv URI get-printer-attributes.test > attrs.txt` (If the first one does not work)
Replace URI with `ipp://192.168.1.2/ipp`
Also please attach the results of `avahi-browse -r -t _ipp._tcp > avahi-out.txt` 
Thanks in advance

**Comment by voland66** [comment]
The output of ipptool and avahi-browse commands is attached (using get-printer-attributes.test for the first one, get-printer-attributes-2.0.test did not give any output)
[attrs.txt](https://github.com/OpenPrinting/cups-filters/files/6093041/attrs.txt)
[avahi-out.txt](https://github.com/OpenPrinting/cups-filters/files/6093042/avahi-out.txt)

**Comment by tillkamppeter** [comment]
@voland66, how do you come to the URI `ipp://192.168.1.2/ipp`? When looking into your DNS-SD record (from the `avahi-browse` command) it contains `rp=/ipp/print`, so the URI must be `ipp://192.168.1.2/ipp/print`, Could you do the `ipptool` commands (try both) with this URI?

**Comment by tillkamppeter** [comment]
@voland66, could you also try
```
lpadmin -p test -E -v ipp://Brother%20MFC-L2700DW%20series._ipp._tcp.local/ -m everywhere
```
Does the queue `test` created with this print correctly?

**Comment by tillkamppeter** [comment]
@voland66 I have committed a possible fix, which makes the PPD generator more reliably decide whether it has to generate a PPD for fax or for printing. It is commit d7b22d73 in master and commit de0747e8 in 1.x. Could you test this? Will you get a correct print queue with the standard `ipp://Brother%20MFC-L2700DW%20series._ipp._tcp.local/` URI?

Independent of this, please still answer my 2 previous posts? Thanks.

**Comment by voland66** [comment]
> how do you come to the URI ipp://192.168.1.2/ipp?

It was one of the example URI's when I chose ipp protocol from "Other Network Printers". Since I did not know specific queue names I just chose this one.
>Could you do the ipptool commands (try both) with this URI?

Here is the output of ipptool command (still only one version gives an output) with ipp/print in URI:  [attrs.txt](https://github.com/OpenPrinting/cups-filters/files/6119627/attrs.txt) 
>lpadmin -p test -E -v ipp://Brother%20MFC-L2700DW%20series._ipp._tcp.local/ -m everywhere

Yes, this queue prints correctly.
>I have committed a possible fix

I will try to compile this when I have a chance. It may have to be over the weekend.

**Comment by darktemplarbasealt** [comment]
It looks like I have reported similar issue: https://github.com/apple/cups/issues/5886. Mentioned commit https://github.com/OpenPrinting/cups-filters/commit/de0747e8da849661e2d5fb7a6f4bec1caf432124 fixed issue for me.

**Comment by tillkamppeter** [comment]
@darktemplarbasealt yes, you are right, your problem which you had reported to Apple is the same as described here. Also thank you very much for testing.

If you find any printing problem and think that it is in CUPS, DO NOT report it to Apple's GitHub. Apple has stopped eveloping CUPS and now the upstream home of CUPS is [here at OpenPrinting](https://github.com/OpenPrinting/cups/).

See also [here](https://openprinting.github.io/OpenPrinting-News-March-2021/).

**Comment by voland66** [comment]
I compiled the patched version (starting with fedora srpm for cups filters). If I create the printer with ipp:// URI the test page prints properly. If I create the printer with dnssd:// URI the printer still prints empty pages.

A tangentially related question -- this is a multi-function printer with the fax function. Is there a way to configure the faxout out queue properly? (Even though it appeared to be configured as fax prior to the patch, I was unable to send a test fax.)

**Comment by tillkamppeter** [comment]
@voland66, are you sure that you have the patched version correctly in place? Especially that you do not have two versions of libcupsfilters (the change is in libcupsfilters) on your system? The library installed by your system is in `/usr/lib/` or a subdirectory of it, installations from source ( `./configure; make; make install`) put the library into `/usr/local/lib`or a subdirectory by default.

Could you post the exact steps how you compiled and installed here?

**Comment by pranshukharkwal** [comment]
@voland66 Could you check if the new ppd file generated with dnssd:// URI still contains `*cupsIPPFaxOut: True` or not.

**Comment by voland66** [comment]
@tillkamppeter 
I must be doing something wrong when I compile from github, so here is the list of commands I use:
`git clone https://github.com/OpenPrinting/cups-filters.git`
`git checkout de0747e`
`./autogen.sh; ./configure; make; sudo make install`
To be sure the right version of cups filters is used, I first uninstalled cups-filters and cups-filters-libs rpms.
After this I do not have a choice of creating a driverless ppd, I am simply offered the list of Brother drivers as in the past. The absence of this choice suggests to me that I did something wrong.

I also tried to use your patch in a different way -- by editing the content of Fedora source rpm by hand and then recompiling and reinstalling it. With this I have the following result:
If I choose the printer with dnssd:// URI, I am offered a driver named "Brother MFC-L 2700DW series, driverless, cups-filters 1.28.7" (no Fax in the driver name anymore) and it prints empty pages. If I choose the printer with ipp:// URI, I am offered a driver named "MFC-L2700DW series - IPP Everywhere", everything is fine. Normally, the first of these two drivers is not offered when I am installing ipp:// printer. But if I do so right after installing dnssd:// printer, the "Brother MFC-L 2700DW series, driverless, cups-filters 1.28.7" is still available and it works.

As I might have mentioned earlier, "IPP Everywhere" ppd does not have "Print Scaling" option available in "driverless, cups-filters" ppd.

@pranshukharkwal 
With recompiled fedora rpms there is no *cupsIPPFaxOut line in the new ppd files. On the other hand, the printers configured previously with an explicit printer URl, ipp://192.168.1.2/ipp do have `*cupsIPPFaxOut: True` in ppd files yet they print correctly. So after (seemingly successfully) applying @tillkamppeter's patch to Fedora's rpms the only configuration that does not work is the configuration with dnssd:// URI.

**Comment by pranshukharkwal** [comment]
@voland66 So the issue with `ipp://Brother%20MFC-L2700DW%20series._ipp._tcp.local` URI seems to be fixed after applying @tillkamppeter 's patch, and now the ppd file generated also does not contain `*cupsIPPFaxOut: True`

Now we need to investigate why the dnssd:// URI is not working properly. 
Could you please confirm whether the PPD generated in both the cases (ipp://Brother%20MFC-L2700DW%20series._ipp._tcp.local and dnssd:// uri) are the same? (Please attach the ppd file here)
Also please attach the error logs generated when you try to print with the dnssd uri. Are they same as the error1.txt file which you uploaded earlier.
