### ISSUE TITLE
Configure preference of application/pdf for driverless IPP printers

### ISSUE THREAD

**Issue by fabled** [OpenPrinting/cups-filters#350]
Hi,

I'm trying to get a HP printer to work in driverless mode, and be able to print large PDF documents (>200 pages, >200 MB). Seems that the printer has hard limitations on how big PDF files it can process correctly (apparently because PDF cannot be printed page by page). The same file works if I just delete the PDF support from the PPD, and the file gets sent via one of the raster or PCLm mode (streaming mode).

Is it possible to force use one of the streaming modes at printer queue install time? Or perhaps on print job basis via some option?

If not, what would be the way to add support for this?

**Comment by fabled** [comment]
Seems a6807df9ce4977611e8160b65b4dd43d74270d8a might actually fix my issue too.

**Comment by tillkamppeter** [comment]
Yes, a6807df actually solves it, closing ...
