### ISSUE TITLE
Filter for Xerox XCPT PDL support

### ISSUE THREAD

**Issue by baybal** [OpenPrinting/cups-filters#358]
Xerox XCPT is a nearly direct mapping of IPP to XML.

It's used by more of the recent big iron AltaLink printers leased by Xerox.

It's probably made to allow for more direct interaction in between REST API world, and printers.

There is sporadic PDL documentation on the internet, and there is somebody superheroic developing the XCPT filter alone here http://mj.ucw.cz/gitweb/?p=kam-printing.git;a=summary

**Comment by tillkamppeter** [comment]
Project seems already to be withdrawn by the author, closing ... But thanks anyway for reporting.
