### ISSUE TITLE
-o print-scaling=none behaviour

### ISSUE THREAD

**Issue by debiantriage** [OpenPrinting/cups-filters#362]
I attach the following two files:

![yellow](https://user-images.githubusercontent.com/19552178/115992885-de34a880-a5c7-11eb-9921-e2808200b627.jpg)

![garden](https://user-images.githubusercontent.com/19552178/115992962-408da900-a5c8-11eb-98e9-464a974ad82a.jpg)

The first is a scan taken with Xsane.  The second is from my camera.

`identify -v <JPEG_file>` shows 

> Print size: 6.53333x8.95333

> Print size: 9.16667x6.08333 

I would see both images as being smaller than A4. Executing

`/usr/sbin/cupsfilter -p rx420.ppd -m application/pdf -o PageSize=A4 -o print-scaling=none <JPEG_file> > out.pdf`

it seems to me that the fit method has been used to produce out.pdf. I would have expected a centred  image with four white borders. That is what I get with the image in Issue #65.

cups-filters is 1.28.7-1 on Debian unstable.

Regards,

Brian.

**Comment by debiantriage** [comment]
The second image has resolution 192x192 according to `identify`. The output of the previous `cupsfilter` command shows 128x128 PPI. So it would seem that `imagetopdf` cannot get the resolution from the file and the image size is seen as being larger than A4. `-o print-scaling=auto` uses the expected fill method.

Being unable to obtain the resolution from the file is an extra complication. I imagine there may be good reasons why it cannot easily be accomplished.

Logs for processing both files have 

> [DEBUG]: Ignoring crop-to-fit option!

and in Issue #92 we see 

> For images, I am checking if more than 50% of height or width is to be cropped in crop-to-fit, then we ignore it.

However, in Issue #108 it is said that for `-o print-scaling=none`

> do not scale the document to fit the requested media size. If the document is larger than the requested media, center and clip the resulting output. If the document is smaller than the requested media, center the resulting output.

No limitation is placed on the degree of cropping that can take place.

The first image has its correct resolution identified, so it would appear `imagetopdf` should not be scaling it to fit A4.

**Comment by Rishabh-792** [comment]
@debiantriage Can you please send the PPD file for this in a '.txt' format.

**Comment by debiantriage** [comment]
Here you are: 
[rx420.ppd.txt](https://github.com/OpenPrinting/cups-filters/files/7877160/rx420.ppd.txt)

**Comment by tillkamppeter** [comment]
The sample images have the resolution information (which is required to determine an absolute size from their pixel counts) only in their EXIF data (meta data added by the capturing hardware device, like camera or scanner), not in the JPEG header itself.\

Usually image files, like JPG, PNG, ... have no defined absolute size (in contrary to PostScript and PDF) but only a pixel size. Cameras are specified with MPixel sizes, not with print sizes. If reviewers tell that a camera is good enough for 8x10-inch printes, they usually assume printing with 300 dpi (not taking into account lens quality).

CUPS and cups-filters never read the EXIF data of image input files. I know that PDFs are printed in original size with `print-scaling=none`, but I am not sure what happens with images, either they are scaled to fit the page as `print-scaling=fit` does or they are printed with 1 image pixel being 1 print pixel, so your 1760x1168 photo gets ~15x10 cm or ~6x4 inches with `print-scaling=none Resolution=300dpi`.

For sure wrong is to automatically change the print scaling behavior when the print size gets smaller than half the page size. This we will remove (for printing PDF and PostScript files there was never such a facility AFAIR).

**Comment by tillkamppeter** [comment]
@michaelrsweet what was the original idea with the image filters? How large should image files get printed with `print-scaling=none`?

**Comment by michaelrsweet** [comment]
@tillkamppeter Historically we've used any resolution information that is part of the file to determine the printed size. In the absence of that, I used a resolution of 128 PPI which worked well for 1280x1024 screenshots (the predominate display resolution of Unix workstations back in the day) to produce an 8x10 print.

**Comment by tillkamppeter** [comment]
@michaelrsweet thanks, but would this still mae sense nowadays, where typical photo pixel sizes and screen pixel sizes have grown independently, typical monitor sizes have also grown somewhat, ... Photo printing for me seems to only make sense with some scaling definition, like fit or fill.

**Comment by michaelrsweet** [comment]
@tillkamppeter You can define whatever default image resolution you like. Ideally the default should be "auto-fit" so that smaller images (barcodes/shipping labels) aren't scaled up but larger images are scaled to fit.

**Comment by michaelrsweet** [comment]
(for reference, shipping label images are usually provided at 200dpi)

**Comment by tillkamppeter** [comment]
@michaelrsweet then one should perhaps use a 200-dpi default?

**Comment by michaelrsweet** [comment]
@tillkamppeter WFM.

**Comment by tillkamppeter** [comment]
@Rishabh-792 What you need to do here is to check whether the filters `imagetoraster` and `imagetopdf` do the correct thing when the attribute `print-scaling=none` is supplied. The meaning of the attribute is to conserve original size, center the content, and if the content is too large, crop.

Generally, an image file has no "original size" as it is simply a grid of pixels (not like a PDF which has its absolute size defined), but at least some images have a DPI resolution defined, which makes up for an absolute size. In case of no resolution defined, assume 200 dpi, as, as @michaelrsweet told, shipping labels provided as image file usually have 200 dpi.

The problem encountered by the original poster is that he has taken a picture with a camera and there the DPI resolution is not in the standard JPEG header but in the EXIF data of the image. If you find an easy way to read resolution from EXIF data and add it it would be great, but the solution must be easy to use by distributions, meaning that no new library has to get added to the main/core part of the distribution. Meaning that you either use an EXIF library which every distribution already ships or no EXIF library at all.

But also take into account that having photos printed in "original size" can be a very special wish. Remember that in the film era photos were exposed on 24x36 mm film and sometimes also on 60x45 mm, 60x60 mm, ... and photo stores offered you 10x15 cm, 13x18 cm, ... prints. What was "original size" then?

**Comment by Rishabh-792** [comment]
Hi @tillkamppeter , I made a PR for changing the default DPI to 200.

Now working on fixing the `print-scaling=none` attribute.

**Comment by tillkamppeter** [comment]
I have found a bug in `print-scaling=none` when I fixed the way how the filter functions obtain color spaces and depths from cups-filter-generated PPD files for driverless printers and for cups-browsed clusters. I discovered that the size of the printable area of the page was given in PostScript points and the size of the image in pixels and this got compared, giving a completely wrong output size. This I have fixed with a simple correction (in all three `imageto...()` filter functions). By doing this I have also thrown out the image size limitation in which crop-to-fit is accepted.

So this issue should be fixed, so I am closing this issue.

@Rishabh-792 the `imageto...()` filter functions all use `#include <cupsfilters/image-private.h>`. Could you check whether here correct CUPS library APIs (accessor functions) could be used? This is probably a remainder of the fact that cups-filters got spun out of CUPS more than a decade ago.

**Comment by tillkamppeter** [comment]
Backported my fixes to the 1.x branch: The `print-scaling=none` fix is commit 92989bb3 and the 200ppi default chnage is commit e4964fa9. Will be included in the 1.28.12 release which I will issue later this week.

**Comment by tillkamppeter** [comment]
We have a further improvement here now. Commit 76a49f034 adds support for reading the original image's resolution from the image's EXIF data (camera/scanner-supplied metadata). So from many more image files resolution info and this way enough data to calculate the original size can be extracted, especially from images taken with cameras or smartphones.

Closer we cannot get.

Thanks, Sachin Thakan, for your contribution.

**Comment by tillkamppeter** [comment]
@debiantriage I have checked the debug output of `imagetoraster` now and with `print-scaling=none` we get now **exactly** the sizes you found with `identify`. See "Portrait size is ..."/"Landscape size is ..." (of the actual orientation of the image) in the debug output. So your problem is perfectly solved.
