### ISSUE TITLE
cups-filters does not compile with latest openldap 2.5.4

### ISSUE THREAD

**Issue by timtas** [OpenPrinting/cups-filters#367]
cups-filters does not compile with latest openldap 2.5.4, for a simple reason:

utils/cups-browsed.c defines and implements a function 

`static LDAP *ldap_connect(void);`

but the new ldap library defines and implements a function:

`int ldap_connect( LDAP *ld );`

A simple rename of the function in `cups-browsed.c` should fix the problem, but maybe it would be wise to also check the rest of the ldap functions.

**Comment by tillkamppeter** [comment]
Fixed by pull request #370.
