### ISSUE TITLE
`gnutls/gnutls.h: No such file or directory` while installing latest `cups 2.3.3`

### ISSUE THREAD

**Issue by deltasata** [OpenPrinting/cups-filters#368]
I am trying to install the latest version of `cups 2.3.3`, I was following https://fossies.org/linux/cups/INSTALL.md

After the `make` command, I got the foll error.
```
In file included from cups-private.h:21:0,
                 from auth.c:17:
http-private.h:70:14: fatal error: gnutls/gnutls.h: No such file or directory
 #    include <gnutls/gnutls.h>
              ^~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [../Makedefs:271: auth.o] Error 1
```
Note that I followed the step
```
sudo apt-get install autoconf build-essential libavahi-client-dev \
     libgnutls28-dev libkrb5-dev libnss-mdns libpam-dev \
     libsystemd-dev libusb-1.0-0-dev zlib1g-dev
```
before going to `make`.

**Comment by zdohnal** [comment]
Hi,

thank you for reporting the issue!

However, CUPS is a separate project - see OpenPrinting/cups.

Regarding the error - either ```libgnutls28-dev``` doesn't provide gnutls/gnutls or you have your includes set up incorrectly.

Would you mind reporting the issue to CUPS project and attaching there as files (you can add .txt suffix to a file and github can upload it) your compilation log and config.log after running configure?

**Comment by deltasata** [comment]
All the ubuntu 20.04 computers I tried could not print any scientific paper properly! Why don't you guys retire and let others write non-buggy codes?

**Comment by jsmeix** [comment]
@deltasata 
good that now everybody can clearly see what kind of person you are.
