### ISSUE TITLE
gstoraster shifts image down

### ISSUE THREAD

**Issue by za3k** [OpenPrinting/cups-filters#373]
I wrote a small test program that outputs a PDF with a rectangle in it (using python's Pillow library). If I approach full-size in BOTH dimensions, I see strange behavior. Extra margin is inserted at the top and the bottom of the rectangle goes off the page. 

I am running the following (note, turn off pdf auto-rotate if needed with other test sizes):
```
python test-rect.py 500 700 # generates test.pdf, 500x700 is the dimensions of rectangle to generate, I assume in points?
/usr/bin/cupsfilter -p ~/HL-2270DW.ppd -m application/vnd.cups-raster -e test.pdf >debug.vnd.cups-raster
```
Note that both 64x700 and 500x64 raster outputs are correct and print correctly. It's only 500x700 that's wrong.

I'm printing to a Brother HL-22 printer using the brlaser driver, on US letter paper. My printer is set to default to letter. I've verified it's not a hardware/driver bug--I can reproduce the problem in the raster output using cupsfilter. Looking at the vnd.cups-pdf PDFs seems fine on my viewer, so it's probably the gstoraster step.

May be related to https://github.com/OpenPrinting/cups-filters/issues/138 . Looking at the GS bug fix summary, I don't see a root cause, and lightly suspect that bug was masked rather than fixed. This means it /could/ be a Ghostscript bug, or a bug in how Ghostscript is called. I'm reporting it here first because I don't know enough about Ghostscript to file a report there.

CUPS version: 1:2.3.3op2-3
Ghostscript version: 9.54.0
Brlaser: 6-2
Tested on Arch Linux (also reproducible on raspbian bullseye, with different wrong behavior in buster, which is before the linked bug was fixed).

PPD for brother printer (attached as .txt because github refuses to allow PPD files): [HL-2270DW.txt](https://github.com/OpenPrinting/cups-filters/files/6568168/HL-2270DW.txt)

In particular:
```
*PageSize Letter/US Letter: "<</PageSize[612 792]/ImagingBBox null>>setpagedevice"
*PageRegion Letter/US Letter: "<</PageSize[612 792]/ImagingBBox null>>setpagedevice"
*ImageableArea Letter/US Letter: "8 8 604 776"
*PaperDimension Letter/US Letter: "612 792"
*cupsFilter: "application/vnd.cups-raster 33 rastertobrlaser"
```

Rectangle generating program `test-rect.py` is attached in full here:
```
from PIL import Image
import math,sys

size = (int(sys.argv[1]), int(sys.argv[2])) # w,h
im = Image.new(mode="1", size=size, color=1) # black-and-white
pixels = im.load()
for i in range(0, size[1]): # left + right
    pixels[0,i] = pixels[-1,i] = 0
for i in range(0, size[0]): # top + bottom
    pixels[i,0] = pixels[i,-1] = 0
for i in range(0, 21): # big box on top-left
    pixels[20,i] = pixels[i,20] = 0 # top-left
for i in range(0, 11): # small box in other corners
    pixels[10,-i] = pixels[i,-10] = 0 # bottom-left
    pixels[-10,-i] = pixels[-i,-10] = 0 # bottom-right
    pixels[-10,i] = pixels[-i,10] = 0 # top-right
im.save("test.pdf")
```

**Comment by za3k** [comment]
Attached is a screenshot of the rasterview output. An (incorrect) 500x700 rectangle is wrong.jpg. A (correct) 500x500 rectangle is right.jpg.
![wrong](https://user-images.githubusercontent.com/726482/120151419-16b83b00-c1a1-11eb-9ec3-c96c4e6c082a.jpg)
![right](https://user-images.githubusercontent.com/726482/120151432-1ae45880-c1a1-11eb-82c0-f708b4510b29.jpg)

**Comment by tillkamppeter** [comment]
I cannot eproduce this with the current GIT master. Probably I fixed this issue without knowing that I have done so, most probably with commit 4aaf23aae3. Therefore I am closing this issue here.
