### ISSUE TITLE
ttfread

### ISSUE THREAD

**Issue by justinkb** [OpenPrinting/cups-filters#386]
What's the point of this executable? It's built from fontembed/main.c and makes DejaVuSans.ttf a runtime dependency for the package, as opposed to just a test dependency, because TESTFONT gets hardcoded into it as a default parameter (as opposed to just printing a message that the app needs a parameter?!). Is this a half-finished test app that made it into the software? I have found no consumer of this app in the whole of the internet, I suggest scrapping it entirely and adjusting the conftest for DejaVuSans.ttf so it doesn't abort if it can't find it but just makes make check unavailable if not present.

**Comment by tillkamppeter** [comment]
AFAIK this is only for testing but I never checked how it gets called during the testing (`make check`?) process. Eliminating it does not remove the dependency on a test font altogether, as the same test font is used by `fontembed/test_*.c` (`TESTFONT` from `config.h`). It outputs XML code when called manually. At least it is not correct that `make install` actually installs it.

**Comment by justinkb** [comment]
AFAICT it never gets used during make check, hence my confusion about its very existence

**Comment by tillkamppeter** [comment]
Removed in commit a6edd76fbc

Thanks for the report.
