### ISSUE TITLE
"media-type-supported" only searched using IPP_TAG_KEYWORD format

### ISSUE THREAD

**Issue by jstrine** [OpenPrinting/cups-filters#397]
Some printers (example HP ColorLaserJet M281fdw) list media-type-supported in IPP_TAG_NAME versus IPP_TAG_KEYWORD format.  cups-filters/driverless will not write the media-types to the PPD, but the cups/ippeverywhere driver will.

Value returned from printer
`media-type-supported (1setOf nameWithoutLanguage) = ...`

Matching cupsfilters/ppdgenerator.c to CUPS cups/ppd-cache.c, shows CUPS project uses IPP_TAG_ZERO to match wildcards and correctly write the PPD.

**Comment by jstrine** [comment]
Code from CUPS project.

https://github.com/apple/cups/blob/11055349c31a52ffb2ced2eaa5faad7fb9749478/cups/ppd-cache.c#L3743

**Comment by tillkamppeter** [comment]
Fixed in 640ee0757d1.

Thank you very much.
