### ISSUE TITLE
imagetoraster and gstoraster do not support print-color-mode=monochrome

### ISSUE THREAD

**Issue by tianmax** [OpenPrinting/cups-filters#400]
Printer: HP Deskjet 2132
Mobile: iPhone 11
Imagetoraster and gstoraster do not support print-color-mode=monochrome, I don't know how change these application to print with monochrome mode.
Thanks.

**Comment by tillkamppeter** [comment]
Tests running the `imagetoraster` and `gstoraster` filters directly on the command line show that they support `print-color-mode=monochrome`, resulting in colored input files be converted to grayscale Raster files.

So for your case we need more information:
- Is the print job actually going through your computer? Or is the iPhone directly printing on your printer (works if your printer supports AirPrint).
- If your computer is actually involved, which version of CUPS and cups-filters do you use, which Linux distribution?
- How did you set up your printer? Could you attach your printer's PPD file (in `/etc/cups/ppd/`, take a copy of it, rename it to have a `.txt` file name extension).
- Could you provide the CUPS error_log (in debug mode) for us? Please run the command `cupsctl --debug-logging` in a terminal window, then print another job (with "monochrome" setting) from your iPhone, wait until the job comes out of your printer (probably in color), and after that, copy your `/var/log/cups/error_log` file, rename the copy to have a `.txt` file name extension, and attach it to this bug report.
