### ISSUE TITLE
Regarding rastertoescpx.c support for latest Epson printers

### ISSUE THREAD

**Issue by adhiti33** [OpenPrinting/cups-filters#403]
I am able to convert pdf -> raster -> print file(prn) using rastertoescpx.c and send print file over USB. But observe printer not responding.

Regarding this would like to know if rastertoescpx.c is supported for latest epson printers like Epson M200. If not please provide some alternatives.

Epson test printer used:
https://www.epson.co.in/Ink-Tank/Ink-Tank-System-Printers/EcoTank-M200-Multifunction-B%26W-Printer/p/C11CC83412

**Comment by tillkamppeter** [comment]
`rastertoescpx.c` was developed many years ago (~ a decade) and got never actually used. I inherited it from CUPS when Apple split off all filters which were not used by Mac OS and I started maintaining them founding the cups-filters project. I have never seen a PPD file for it and so I assumed that no one actually used it.

For modern Epson printers either use [Gutenprint](http://gimp-print.sourceforge.net/) or the Epson drivers referred to on [OpenPrinting's driver list](https://www.openprinting.org/drivers), or the "printer-driver-escpr" or "epson-inkjet-printer-escpr" package of your distribution.
