### ISSUE TITLE
const poisoning

### ISSUE THREAD

**Issue by prlw1** [OpenPrinting/cups-filters#42]
Picky compiler complaint (1.20.3 release):

filter/pdftoopvp/OPVPOutputDev.cxx: In member function 'void OPVPOutputDev::doUpdateFont(GfxState*)':
filter/pdftoopvp/OPVPOutputDev.cxx:532:46: error: invalid conversion from 'const Ref*' to 'Ref*' [-fpermissive]
   id = new SplashOutFontFileID(gfxFont->getID());
                                ~~~~~~~~~~~~~~^~
filter/pdftoopvp/OPVPOutputDev.cxx:69:3: note:   initializing argument 1 of 'SplashOutFontFileID::SplashOutFontFileID(Ref*)'
   SplashOutFontFileID(Ref *rA) { r = *rA; substIdx = -1; }
   ^~~~~~~~~~~~~~~~~~~

**Comment by prlw1** [comment]
Suitable patch here:

http://cdn.netbsd.org/pub/pkgsrc/current/pkgsrc/print/cups-filters/patches/patch-filter_pdftoopvp_OPVPOutputDev.cxx

**Comment by tillkamppeter** [comment]
Patch applied in commit 2561a9dc5ebdfd90cc2781ca8f1560f4faff19a1.
Thank you very much for your contribution.
