### ISSUE TITLE
An improper locking due to the unreleased lock before program exit

### ISSUE THREAD

**Issue by ryancaicse** [OpenPrinting/cups-filters#423]
Hi developers, in the below codes, the lock `sp_mutex` could be not released before program's exit `abort()` when `key->guard != _PPD_STR_GUARD` . I think there is no harm to write `_ppdMutexUnlock(&sp_mutex);` before the `abort()` for better resource management and code symmetry. Thanks!
https://github.com/OpenPrinting/cups-filters/blob/77212a77a2a40c903ae0e7728369cdbda61ed545/ppd/string.c#L280-L295

**Comment by ryancaicse** [comment]
Similarly, before `abort()`, the lock should be released

https://github.com/OpenPrinting/cups-filters/blob/77212a77a2a40c903ae0e7728369cdbda61ed545/ppd/string.c#L64-L99

**Comment by ryancaicse** [comment]
Hi, developers, any comments are highly appreciated!
@tillkamppeter

**Comment by tillkamppeter** [comment]
Fixed in commit 77489625d.

Thank you very much for the bug report.
