### ISSUE TITLE
"rastertopwg" seems to produce output not liked by Brother MFC-J430W

### ISSUE THREAD

**Issue by peat-psuwit** [OpenPrinting/cups-filters#426]
Brother MFC-J430W is a printer which support AirPrint.

The system is Ubuntu 20.04, running cups-snap in parallel mode (although the problem also happens on system's cups so it's probably not the cause).

At one point, `error_log` says:
```
D [02/Jul/2021:01:43:19 +0700] [Job 3] Using following CUPS filter chain to convert input data to the APPLE Raster format: gziptoany pdftoraster rastertopwg
```

And after a while, it says:
```
D [02/Jul/2021:01:43:23 +0700] [Job 3] JOBSTATE: document-format-error
```

Which make the `rastertopwg` my suspect.

The full [`error_log`](https://github.com/OpenPrinting/cups/files/6750244/error_log.txt) is attached, along with [`$SNAP/var/spool` (in a .tar.gz)](https://github.com/OpenPrinting/cups/files/6750247/var-spool.tar.gz).

**Comment by tillkamppeter** [comment]
@peat-psuwit, and everyone else, could you please update cups-filters to the current GIT master state? There were bugs for printing to Raster printers via cups-browsed which should have been fixed now.

Main problem was that on Raster jobs the data was not sent with the correct color space and depth. In addition there were also problems with page geometry/margins. I have done several fixes in the last few weeks (last update yesterday). So please retry with the newest GIT snapshot.

@michaelrsweet, the calling of CUPS filters (now filter functions) by the `implicitclass` backend is to allow clusters of printers which use different input formats. The cluster CUPS queue generated by cups-browsed creates a PPD with `application/vnd.cups-pdf` as data format (emulation of PDF printer) and the backend, once it got told the destination printer's URI, converts the PDF into the printer's format.

**Comment by peat-psuwit** [comment]
@tillkamppeter Could you please advice on how I should test the git master of cups-filter? I was using Snap version of cups before, but according to snapcraft.yaml that doesn't use the git version of cups-filter.

**Comment by tillkamppeter** [comment]
@peat-psuwit how do you use the CUPS Snap? Did you simply grab it from the Snap Store or did you [build it from source](https://github.com/OpenPrinting/cups-snap)?

**Comment by tillkamppeter** [comment]
@peat-psuwit I have updated the CUPS Snap to cups-filters 2.x now. The Snap Store's build service is currently building it and in ~1 hour (most probably earlier) it will be available and an auto-update of it on your system should take place, but only if the CUPS Snap you have installed is from the Snap Store.

If you have built the Snap from source by yourself, you need to `git pull` and rebuild right now.

Please tell whether this solves your problem.

**Comment by peat-psuwit** [comment]
Ok, this is a weird one: with cups-snap version 596 from snap store, the printer now prints, but in black-and-white. And after a while the printer won't print anything until I restart both the printer and CUPS.

Will collect the log later, after I try to reproduce won't-print state.

**Comment by tillkamppeter** [comment]
Thanks for testing

Does the printer print in color if you explicitly request color when sending the job (to the `lp` command line add `-o print-color-mode=color`)? This would mean that cups-browsed does not set the defaults correctly when creating a print queue.

As the CUPS Snap is still under heavy development it is configured by default to do logging in debug mode. You find the logs in `/var/snap/cups/current/var/log/`. Most important is `error_log` containing the logging of both succeeding and failing jobs, especially also of the last succeeding and the first failing job. `cups-browsed_log` would be of help for the default setting problem.

**Comment by peat-psuwit** [comment]
If I added `-o print-color-mode=color` to the `lp` command line, then yes the printer would print in color. Unfortunately I can't reproduce the state where the printer won't print, but that I feel it's more like printer firmware's bug.

Just to be thorough, I've included all the log in `/var/snap/cups/current/var/log/` in a zip file. The last 2 jobs are the same file printed with, follow by without, `-o print-color-mode=color`.

[cups-snap_logs_2022-01-15.zip](https://github.com/OpenPrinting/cups-filters/files/7874594/cups-snap_logs_2022-01-15.zip)

Although I'm not sure now if this should continue in this issue. Feel free to close this issue, and I'll open a new one about the printer defaulting to black-and-white.

**Comment by tillkamppeter** [comment]
I have already found out what causes the problem of defaulting to monochrome. The PPD generated by cups-browsed does not only contain color and grayscale settings but also an "Auto" setting which is set to the default (resembling `print-color-mode-supported` and `print-color-mode-default` printer IPP attributes), but CUPS, at least with its most resent [commit](https://github.com/OpenPrinting/cups/commit/98ac8653) (note also that the CUPS Snap uses the GIT master of CUPS), does not support "Auto" as color mode and ends up considering this as monochrome. I have to check here whether the correct fix is making CUPS supporting "Auto" or cups-browsed not generating PPD files with "Auto" for the color mode.

**Comment by michaelrsweet** [comment]
@tillkamppeter The PPD shouldn't have an "auto" option - generally speaking, "auto" maps to "color" for color pages and "monochrome" for B&W pages, which is something that the PDF RIP can automatically detect and use the correct color/grayscale colorspace when "color" is the default (i.e. optimize for the most common usage and don't add a separate option to enable it).

**Comment by tillkamppeter** [comment]
I have fixed the color problem now. The mentioned commit does not only set the default to color if a color choice is present, but also ignore the auto choice in the `print-color-mode-supported` IPP attribute, only adding the other choices to `ColorModel`.

**Comment by tillkamppeter** [comment]
In another commit I will also take into account `print-color-mode-default` like in OpenPrinting/cups@98ac8653eb3 .

**Comment by tillkamppeter** [comment]
As now the color problem is solved (thanks @michaelrsweet) and the problem of printing ceasing to work after a certain amount of successful jobs not being reproducible I am closing this issue here.

**Comment by tillkamppeter** [comment]
OpenPrinting/cups@98ac865 is ported to the PPD generator of cups-filters now (commit 99d1cc62) and I have triggered a rebuild of the CUPS Snap, now the color mode defaults should be always correct.
