### ISSUE TITLE
imagetoraster crashing with some LaserJet HP Printers in arm platform

### ISSUE THREAD

**Issue by EMlyDinEsHMG** [OpenPrinting/cups-filters#435]
Hi!

I am using cups library in yocto build for armv7 architecture, and it is working fine. But we are unable to print HP 136nw and HP 108 printers. From cups logs, I have found that imagetoraster is crashing with segmentation fault. 

Versions used are Cups 2.3.3 and 1.27.2 filters.

d [15/Dec/2021:17:16:16 +0000] cupsdFinishProcess(pid=1374, name=0x7efb5504, namelen=1024, job_id=0x7efb5464(14)) = "/usr/libexec/cups/filter/imagetoraster"
D [15/Dec/2021:17:16:16 +0000] [Job 14] PID 1374 (/usr/libexec/cups/filter/imagetoraster) crashed on signal 11.
d [15/Dec/2021:17:16:16 +0000] select_timeout: JobHistoryUpdate=0
d [15/Dec/2021:17:16:16 +0000] select_timeout(-1): 22 seconds to write dirty config/state files
E [15/Dec/2021:17:16:16 +0000] [Job 14] Error reading raster data.
d [15/Dec/2021:17:16:16 +0000] cupsdAddEvent(event=job-progress, dest=0x22a88c0(HP508140D0823E_HP_Laser_103_107_108_USB_), job=0x223a958(14), text="%s", ...)
D [15/Dec/2021:17:16:16 +0000] Discarding unused job-progress event...
d [15/Dec/2021:17:16:16 +0000] cupsdAddEvent(event=printer-state-changed, dest=0x22a88c0(HP508140D0823E_HP_Laser_103_107_108_USB_), job=(nil)(0), text="Printer \"%s\" state changed.", ...)
D [15/Dec/2021:17:16:16 +0000] Discarding unused printer-state-changed event...
d [15/Dec/2021:17:16:16 +0000] select_timeout: JobHistoryUpdate=0
D [15/Dec/2021:17:16:16 +0000] [Job 14] Unable to read line 38 for page 1.
d [15/Dec/2021:17:16:16 +0000] select_timeout: JobHistoryUpdate=0
d [15/Dec/2021:17:16:16 +0000] process_children()
d [15/Dec/2021:17:16:16 +0000] cupsdFinishProcess(pid=1375, name=0x7efb5504, namelen=1024, job_id=0x7efb5464(14)) = "/usr/libexec/cups/filter/rastertopwg"
D [15/Dec/2021:17:16:16 +0000] [Job 14] PID 1375 (/usr/libexec/cups/filter/rastertopwg) stopped with status 1.

I have analyzed the core dump generated, and back trace points to this which is not helping at all to me.

Breakpoint 1 at 0x76e26e1c
(gdb) bt
#0  0x76e26e1c in ?? () from /usr/lib/libcups.so.2
#1  0x76e28c70 in _cupsRasterWritePixels () from /usr/lib/libcups.so.2
#2  0x76e28c70 in _cupsRasterWritePixels () from /usr/lib/libcups.so.2
#3  0x000131f0 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/cups-filters/1.27.2-r0/cups-filters-1.27.2/filter/imagetoraster.c:1509

Any help here would be really appreciated. Please check, and let me know if anything required.

I have attached cups logs, and PPD generated by driverless mode.

Thanks
[cupslog.txt](https://github.com/OpenPrinting/cups-filters/files/7721443/cupslog.txt)
[HP 108 attributes.txt](https://github.com/OpenPrinting/cups-filters/files/7721446/HP.108.attributes.txt)
[HP508140D0823E_HP_Laser_103_107_108_USB__PPD.zip](https://github.com/OpenPrinting/cups-filters/files/7721455/HP508140D0823E_HP_Laser_103_107_108_USB__PPD.zip)

**Comment by EMlyDinEsHMG** [comment]
Printer is printing following information:
URF Error - [URF] Decoding fail
POSITION : 0x58 (88)
SYSTEM: emul/URF/URF_dec
LINE: 356
VERSION: v11.73_190212
ERROR_CODE: 11-1114

**Comment by tillkamppeter** [comment]
Fixed in 098579f708 on GIT master (2.x).

Thank you for the bug report.

**Comment by EMlyDinEsHMG** [comment]
@tillkamppeter I will check and let you know if this addresses my problem. I had different approach to solve this issue from my side, I will share after testing.

**Comment by tillkamppeter** [comment]
Fix is also included in today's 1.28.11 release of cups-filters.
