### ISSUE TITLE
Missing closing files

### ISSUE THREAD

**Issue by ryancaicse** [OpenPrinting/cups-filters#437]
`fclose(fp);`  and `close(fd); ` should be put before `Line 338`?
https://github.com/OpenPrinting/cups-filters/blob/f8df996a76ed770fc01bb8f7096031874f945e67/cupsfilters/imagetoraster.c#L317-L349

**Comment by Chandresh2702** [comment]
@tillkamppeter  could you please review my PR.

**Comment by tillkamppeter** [comment]
I have merged the PR now, thank you very much.
