### ISSUE TITLE
texttopdf filter: font name and embedding

### ISSUE THREAD

**Issue by debiantriage** [OpenPrinting/cups-filters#447]
A PDF may be produced from a text file with `/usr/sbin/cupsfilter /etc/services > services.pdf`.

With cups-filters 1.21.6-5 (Debian buster) `pdffonts services.pdf` shows 

> name                                 type              encoding         emb sub uni object ID
ZZLCBA+DejaVuSansMono                CID TrueType      Identity-H       yes yes no      47  0

The font name is displayed and the font shown as subset.

With cups-filters 1.28.7-1 (Debian bullseye) we have

> name                                 type              encoding         emb sub uni object ID
MMDID                                CID TrueType      Identity-H       yes no  no      32  0

There isn't any font name (this is the case for other, but not all fonts) and subsetting is "no".

I thought that a TTF was always subset.

**Comment by tillkamppeter** [comment]
Can the resulting PDF file, `services.pdf` be displayed and printed?

Conversion from text to PDF is done by the `texttopdf` filter of cups-filters which gets called by the `cupsfilter` utility (see screen output).

I do not know why it is not showing the name of the embedded font any more. Can also be that you got another font file with your distribution (there are no fonts included in cups-filters) and that one does not tell its name.

As long as you are able to display/print the resultinh file, there is no bug in cups-filters related to this.

**Comment by debiantriage** [comment]
> Can the resulting PDF file, services.pdf be displayed and printed?

Yes.

From the cups-filters README:

>  - OTF(CFF) embedding currently does not subset the fonts.

The implication is that TTF embedding does (or can) subset fonts.

> As long as you are able to display/print the resultinh file, there is no bug in cups-filters related to this.

In the light of that, I will close the report.
