### ISSUE TITLE
loadFilename failed error

### ISSUE THREAD

**Issue by edmondelosreyes** [OpenPrinting/cups-filters#449]
Whenever I try to print a PDF file using the lp command or from the program I wrote which uses the CUPS API, I get the following error upon checking the current state of the print job:

Status: loadFilename failed: open no: No such file or directory
Alerts: job-completed-with-errors
queued for C331

I’ve also checked the log file located in /var/log/cups/error_log and it prints out the same error as shown below:

[Job 115] loadFilename failed: open no: No such file or directory
[Job 115] Input is empty, outputting empty file.
[Job 115] PID 895 (/usr/libexec/cups/filter/pdftops) exited with no errors.
[Job 115] PID 894 (/usr/libexec/cups/filter/pdftopdf) stopped with status 1.

Any idea as to why I'm getting this error and how to fix it?

cups version 2.2.12
cups-filters 1.27.2

**Comment by Chandresh2702** [comment]
@edmondelosreyes could you please provide us steps for reproducing the problem and also if you could share the code which you used? and is this issue is for a specific file or you are facing for all files.

**Comment by danielkesler-htec** [comment]
@edmondelosreyes I had the same issue while trying to get a new yocto build to work with cups.

cups: 2.2.14
cups-filters: 1.25.2 and 1.28.12
qpdf: 8.4.0

Turns out that the issue is coming from `qpdf` that `pdftopdf`. Once I switched to newer qpdf (10.6.2) it started working.

**Comment by edmondelosreyes** [comment]
@danielkesler-htec Hello, thanks for the input. We're also using a custom image via yocto, I'll let you know and verify it once the person handling our yocto build updates the qpdf version.

**Comment by edmondelosreyes** [comment]
Hello @danielkesler-htec sorry for the late response, updating the qpdf version worked and fixed the issue I mentioned. Thank you
