### ISSUE TITLE
Filter Bug with Apple LaserWriter II series

### ISSUE THREAD

**Issue by johnnya101** [OpenPrinting/cups-filters#452]
Discovered a bug with the Apple LaserWriter II series of printers that was supposedly fixed years ago (https://bugzilla.redhat.com/show_bug.cgi?id=1304869#c12), but is still present. One must add the line "Option pdftops-renderer pdftops" in printers.conf to fix. 

I would assume all IIs would be affected, this would include:
-LaserWriter IINT
-LaserWriter IINTX
-LaserWriter IIG (Personally tested to fix)
-LaserWriter IIF

Bug causes printer to reject job, causes no clear errors in the error log.

**Comment by tillkamppeter** [comment]
Fixed in commit f93d64bfb6. Thanks for the bug report.

We use Poppler for all Apple LaserWriter models now.

**Comment by tillkamppeter** [comment]
Backported the fix to 1.x with commit b8d4e447.

I will release 1.28.13 with this fix soon.

**Comment by tillkamppeter** [comment]
1.28.13 is [released](https://github.com/OpenPrinting/cups-filters/releases/tag/1.28.13) now.
