### ISSUE TITLE
Regression on Brother QL500 label printer introduced in 1.28.12

### ISSUE THREAD

**Issue by christianlupus** [OpenPrinting/cups-filters#454]
Hello,

I have a Brother QL500 label printer. I use Archlinux and updated recently from 1.28.11 to 1.28.12. After the update, I was no longer able to properly print on DK-11209 labels (62x29mm, landscape). See below for an image of the problem. The upper left image is printed with 1.28.12 while the lower one with 1.28.11.

To rule out a physical defect, I printed the small 23x23mm label to the right (also with 1.28.12). The printer is built such that the labels are aligned on the right edge of the carrier. That shows that the problem of white margins only appears for this specific page size.

Unfortunately, I do not have other labels at hand just now. So, I cannot test other sizes. I'll check if I find some in the storage tomorrow.

Switching back and forth between the versions enables and disabled the problem so it seems a regression. Please tell me if I can somehow support you in finding the issue. Doing a git bisect might be possible but will require some preparation on my side.

![IMG_20220323_164617_309-mod](https://user-images.githubusercontent.com/8202922/159744985-0e033c17-6b18-4350-8aa3-406c6d36d069.jpg)

**Comment by christianlupus** [comment]
Sorry for my late answer. I had to prepare for the tests first.

Here come the requested files:
- The [QL500.ppd.txt](https://github.com/OpenPrinting/cups-filters/files/8354892/QL500.ppd.txt)
- The logs of the failing print [logs-failing.txt](https://github.com/OpenPrinting/cups-filters/files/8354894/logs-failing.txt)
- The logs of the succeeding print [logs-succeeding.txt](https://github.com/OpenPrinting/cups-filters/files/8354895/logs-succeeding.txt)
- The complete logs (first failing then succeeding) [error_log-after-all.txt](https://github.com/OpenPrinting/cups-filters/files/8354897/error_log-after-all.txt)

I verified that the prints fail/succeed according to my initial post. The two selective logs are created by making a copy of `/var/log/cups/error_log` just after `cupsctl --debug-logging` and one after the print itself. Then, I checked the number of lines and used `tail` to cut away anything before the print. If you need a general overview, please have a look at the total logs.

**Comment by tillkamppeter** [comment]
Could you also provide your input (PDF?) file which you had sent to the printer? With which application did you create it?

**Comment by christianlupus** [comment]
Hello. I created a PDF using glabels-3. The file was generated by print-to-pdf: [Ausgabe.pdf](https://github.com/OpenPrinting/cups-filters/files/8356132/Ausgabe.pdf)

I sent to the printer via `lp -d QL500 Ausgabe.pdf`.

**Comment by tillkamppeter** [comment]
Thanks, I could already reproduce the bug by creating the PDF test page for this printer with `bannertopdf` and use this as input file.

The problem occurs whenever a printer pulls the paper long-edge first and not the usual short-edge first, like most inkjets or lasers do. Long-edge first is common on label printers and on (usually roll-fed with cutter) large format printers. So I could reproduce your problem with your PPD and also with a PPD for the HP DesignJet T1100 (choosing the "A4.Transverse" page size there).

What happens is that the cropping of the page image is not done correctly at least with `page-scaling` settings `auto` (default), `none`, and `fill`. I have already found a fix for this and will commit it soon and then release cups-filters 1.28.13 (which will then also be the version of Ubuntu 22.04 LTS, Jammy Jellyfish)..

**Comment by christianlupus** [comment]
Wow, that was fast. Thanks for the help! I will wait for the updated version.

**Comment by tillkamppeter** [comment]
Fixed in the GIT repositories, on master with commit 70e0f470825 and on 1.x with commit d4ae67231047.

I will release 1.28.13 with this fix soon.

Thanks a lot for this bug report.

**Comment by tillkamppeter** [comment]
1.28.13 is [released](https://github.com/OpenPrinting/cups-filters/releases/tag/1.28.13) now.
