### ISSUE TITLE
Regression in 1.28.12 on DesignJet 500. Printer scaling pattern down ~220:1

### ISSUE THREAD

**Issue by SeductiveEng** [OpenPrinting/cups-filters#457]
Problem occurring on a HP DesignJet 500 on Fedora 35. Works fine with 1.28.11, but broken in .12 and .13. Printing directly with lp using the following command line:
```lp -d DesignJet500 -o landscape -o media=Custom.42x80 -o inputslot=RollPaperCut circle-test.pdf```

Image showing results and original .pdf are attached along with printer .ppd.

![PXL_20220406_173154298](https://user-images.githubusercontent.com/103138715/162035358-4eac48b8-da0b-4ae2-afe9-5eaac180ac56.jpg)
 
[circle-test.pdf](https://github.com/OpenPrinting/cups-filters/files/8429186/circle-test.pdf)
[DesignJet500.ppd.txt](https://github.com/OpenPrinting/cups-filters/files/8429205/DesignJet500.ppd.txt)

**Comment by tillkamppeter** [comment]
You probably want a page size of 42x80 **Inches**. If you supply `Custom.42x80` (without specifying a unit) **PostScript Points** (1/72 Inches) are assumed. Therefore you get such a small printout. Try `Custom.42x80in`. There are also `cm` and `mm` available as units AFAIR.

**Comment by SeductiveEng** [comment]
It works well if I try and print something that is longer than wide, but if I try and print in landscape, the resulting print is not centered on the page. Printed with

``` lp -d DesignJet500 -o landscape -o media=Custom.42x20in -o inputslot=RollPaperCut circle-test-2.pdf```

![PXL_20220406_192554151 MP](https://user-images.githubusercontent.com/103138715/162054952-2d713b4d-bbf3-4e99-8efd-f58bb7f92958.jpg)
[circle-test-2.pdf](https://github.com/OpenPrinting/cups-filters/files/8429995/circle-test-2.pdf)

**Comment by tillkamppeter** [comment]
I can only check the behavior of the `pdftopdf` filter which is called before the actual printer driver is called. The `pdftopdf` filter does all correctly. This you can check with a command line like
```
cat circle-test-2.pdf | PPD=DesignJet500.ppd ./pdftopdf 1 1 1 1 'media=Custom.42x20in landscape inputslot=RollPaperCut' > out.pdf
```
If you display `out.pdf` on the screen with `evince` or a similar viewer, you see what ypu wanted to get printed. So it seems that the printer driver is doing something wrong.

Could you try to not use the `landscape` option? `pdftopdf` auto-rotates your input file simply due to the fact that your page size is landscape-shaped but your input file portrait-shaped.

**Comment by tillkamppeter** [comment]
Also make sure to have the newest version of cups-filters: 1.28.**14** ([Release Notes](https://github.com/OpenPrinting/cups-filters/releases/tag/1.28.14)). Should have made it into Debian unstable today.

**Comment by zdohnal** [comment]
@SeductiveEng I've started the build for Fedora right now - you will see the build in [koji](https://koji.fedoraproject.org/koji/packageinfo?packageID=14428) first and the update should arrive into testing repos tomorrow.

**Comment by zdohnal** [comment]
@SeductiveEng the [update](https://bodhi.fedoraproject.org/updates/FEDORA-2022-e2741e743c) is in testing repo now, so you can test the new version.

**Comment by SeductiveEng** [comment]
The reason I have to print landscape is if I don't, the printer will rotate
the print and waste extra paper.

I just tested 1.28.14. It looks like it has fixed the issue.

Thank you for the help.
