### ISSUE TITLE
update to cups 2.4 breaks label printer output

### ISSUE THREAD

**Issue by WilheJo** [OpenPrinting/cups-filters#459]
Manjaro updated cups to 2.4 recently.

I have 2 older ZPL printers (with enhanced rastertolabel) which were working properly with 2.3.
Now, the output gets croped.
None of the page-size and margin options make a difference.

Interesingly, when printing from command-line with lp and -o fit-to-page, everything's fine (see photo).

I tested this with stock ppd&rastertolabel and my changed ones...

Any idea how to fix this?

![20220413_123533](https://user-images.githubusercontent.com/67696310/163166447-86469ca4-1927-402b-b754-66713d73e1db.jpg)

**Comment by tillkamppeter** [comment]
The same problem was already reported by someone else, as issue #454. I have already fixed it in both the 2.x and 1.x branches of cups-filters. The fix is included in cups-filters 1.28.14 and later.
