### ISSUE TITLE
Installing on Centos 6

### ISSUE THREAD

**Issue by leonardorame** [OpenPrinting/cups-filters#46]
Hi, I need to install cups-filters for CUPS 2.1.3 (not in any repository for Centos 6) and after ./configure I get this:

```
gdbus-codegen \
            --interface-prefix org.cups.cupsd \
            --c-namespace Cups \
            --generate-c-code cups-notifier \
            utils/org.cups.cupsd.Notifier.xml
make: gdbus-codegen: Command not found
make: *** [cups-notifier.c] Error 127
```

Can anyone help me to first, install `gdbus-codegen` for Centos 6, then `cups-filters`.

BTW, it is really needed `gdbus-codegen`?.

**Comment by dheeraj135** [comment]
@leonardorame Please try installing ```glib2``` and ```glib2-devel``` package. 
Please look into this: http://www.linuxfromscratch.org/blfs/view/svn/general/glib2.html

**Comment by zdohnal** [comment]
@leonardorame CentOS 6 is based on RHEL 6, which was released 9-10 years ago, so I would not recommend to trying to build newer cups and cups-filters there - you can encounter issues in other required packages.
Would you mind telling us what is your use case, for which you need new cups-filters on CentOS 6? If it is browsing features, CentOS 6 still has CUPS version, which does it in cupsd.

**Comment by tillkamppeter** [comment]
No reaction from the original poster any more, closing ...
