### ISSUE TITLE
imagetoraster size and position arguments not working with gutenprint

### ISSUE THREAD

**Issue by jpnp** [OpenPrinting/cups-filters#464]
When I print an image file from the command line using a printer queue using a gutenprint driver, the image scaling and position options don't get respected; the image is still printed full page.

`lp -d Epson-Stylus-Photo-R3000  -o StpQuality=Economy -o scaling=10 -o position=top media_check.tif`

I'm using Ubuntu 20.04 with cups 2.3.1-9ubuntu1.1 and cups-filters 1.27.4-1, and gutenprint 5.3.4.

I've investigated with cupsfilter and cups is using imagetoraster and rastertogutenprint.5.3

imagetoraster creates an image with 
CUPS Raster Page Attributes:
```
MediaClass = "Standard"
MediaColor = ""
MediaType = "Plain"
OutputType = ""
AdvanceDistance = 0
AdvanceMedia = 0
Collate = 0
CutMedia = 0
Duplex = 0
HWResolution = [ 360 180 ]
ImagingBoundingBox = [ 271 378 323 463 ]
InsertSheet = 0
Jog = 0
LeadingEdge = 0
Margins = [ 0 0 ]
ManualFeed = 0
MediaPosition = 0
MediaWeight = 0
MirrorPrint = 0
NegativePrint = 0
NumCopies = 1
Orientation = 0
OutputFaceUp = 0
PageSize = [ 595 842 ]
Separations = 0
TraySwitch = 0
Tumble = 0
cupsWidth = 255
cupsHeight = 210
cupsMediaType = 0
cupsBitsPerColor = 8
cupsBitsPerPixel = 24
cupsBytesPerLine = 765
cupsColorOrder = CUPS_ORDER_CHUNKED
cupsColorSpace = CUPS_CSPACE_RGB
cupsCompression = 0
cupsRowCount = 0
cupsRowFeed = 2
cupsRowStep = 0
cupsNumColors = 3
cupsBorderlessScalingFactor = 1.000000
cupsPageSize = [ 595.000000 842.000000 ]
cupsImagingBBox = [ 271.956177 378.899994 323.043823 463.100006 ]
...
cupsPageSizeName = "A4"
```
This image only covers the ImageBoundingBox . If I disable imagetoraster then cups filter through imagetopdf and gstoraster.  In this case the raster covers the whole page with the border output as white, and gutenprint can print it fine.
CUPS Raster Page Attributes:
```
MediaClass = "Standard"
MediaColor = ""
MediaType = "Plain"
OutputType = ""
AdvanceDistance = 0
AdvanceMedia = 0
Collate = 0
CutMedia = 0
Duplex = 0
HWResolution = [ 360 180 ]
ImagingBoundingBox = [ 0 0 595 842 ]
InsertSheet = 0
Jog = 0
LeadingEdge = 0
Margins = [ 0 0 ]
ManualFeed = 0
MediaPosition = 0
MediaWeight = 0
MirrorPrint = 0
NegativePrint = 0
NumCopies = 1
Orientation = 0
OutputFaceUp = 0
PageSize = [ 595 842 ]
Separations = 0
TraySwitch = 0
Tumble = 0
cupsWidth = 2975
cupsHeight = 2105
cupsMediaType = 0
cupsBitsPerColor = 8
cupsBitsPerPixel = 24
cupsBytesPerLine = 8925
cupsColorOrder = CUPS_ORDER_CHUNKED
cupsColorSpace = CUPS_CSPACE_RGB
cupsCompression = 0
cupsRowCount = 0
cupsRowFeed = 2
cupsRowStep = 0
cupsNumColors = 3
cupsBorderlessScalingFactor = 1.000000
cupsPageSize = [ 595.000000 842.000000 ]
cupsImagingBBox = [ 0.000000 0.000000 595.000000 842.000000 ]
...
```
Perhaps imagetoraster should do the same, or CUPS default to printing images via imagetopdf.

**Comment by tillkamppeter** [comment]
I have checked `imagetorraster` and it does the right thing. If you see the bounding box ` [ 271 378 323 463 ]` compared to the page dimensions `[ 595 842 ]` you see that `imagetorraster` is creating a scaled down image, but instead of adding white pixels around the image it defines wider margins. `rastertogutenprint` is not able to handle such an input and `rastertopwg` for example has no problem with it. So it is a bug in Gutenprint. Please report it there.
