### ISSUE TITLE
Apple raster not supported by cups-filter ppd generator

### ISSUE THREAD

**Issue by Xerxekyran** [OpenPrinting/cups-filters#469]
When creating a printer with "`lpadmin -p test -v <URI> -E -m driverless:i<URI>`" I understood that the cups-filters ppd generator is used. 

This fails for me when my (simulated with https://github.com/istopwg/ippsample) ipp printer only offers "image/urf" (appleraster) as its document format type. The error message I get is the following:
```
lpadmin: Unable to open PPD "/tmp/06acc62a483a5": Missing PPD-Adobe-4.x header on line 0.
```
Furthermore the driverless command results in the following error message:
```
driverless <URI> > /rw/out.ppd
ERROR: Unable to create PPD file: Printer does not support required IPP attributes or document formats.
```
On the other hand using "`lpadmin -p test -v <URI> -E -m everywhere`" works fine. I could also print to that printer, which then seems to result in a appleraster file.

Here is my used configuration for the simulated printer:
[driverless.conf.txt](https://github.com/OpenPrinting/cups-filters/files/8870643/driverless.conf.txt)

Used cups-filters version: 1.28.10

Am I doing something wrong here? I would like to use the cups-filters ppd generator as it seems to be more resilient than the CUPS ppd generator.

**Comment by tillkamppeter** [comment]
You write: `lpadmin -p test -v <URI> -E -m driverless:i<URI>`

Have you actually put an `i` between `-m driverless:` and the URI? Correct is
```
lpadmin -p test -v <URI> -E -m driverless:<URI>
```
Could you post the `ippsample` command line here which you used for the emulation of an IPP printer? Is it running on a machine in the same local network?

While your emulated IPP printer is running, could you run the following commands:
```
avahi-browse -t -r _ipp._tcp 2>&1 > avahi-browse-ipp-out.txt
avahi-browse -t -r _ipps._tcp 2>&1 > avahi-browse-ipps-out.txt
ipptool -tv <URI> get-printer-attributes.test > attrs.txt
```
Please attach the resulting files, one by one, do not package them together and do not compress them.

By the way, I have made use of my moderator powers to edit your initial post to make it more readable, to not make code characters be eaten by the markdown support. Please have a look into your edited post by clicking the 3 dots at the upper right, then "Edit" (do not actually edit, only have a look at your post's "source code"). Important is to put code pieces between backticks. A line with only 3 backticks marks start or end of multi-line code blocks.

**Comment by Xerxekyran** [comment]
Thank you for your quick answer!

> You write: `lpadmin -p test -v <URI> -E -m driverless:i<URI>`
> 
> Have you actually put an `i` between `-m driverless:` and the URI? Correct is
> 
> ```
> lpadmin -p test -v <URI> -E -m driverless:<URI>
> ```
> 

Yeah my fault when I was replacing the URI string, I already used it correctly.

> Could you post the `ippsample` command line here which you used for the emulation of an IPP printer? Is it running on a machine in the same local network?

server/ippserver -C /rw -k -d ./data -vv

I tried both. Running it locally and in a network. But the network case is the actually wanted one, which I also used to generate the information you wanted below.

> 
> While your emulated IPP printer is running, could you run the following commands:
> 
> ```
> avahi-browse -t -r _ipp._tcp 2>&1 > avahi-browse-ipp-out.txt
> avahi-browse -t -r _ipps._tcp 2>&1 > avahi-browse-ipps-out.txt
> ipptool -tv <URI> get-printer-attributes.test > attrs.txt
> ```
> 
> Please attach the resulting files, one by one, do not package them together and do not compress them.
> 

Here they are:

[attrs.txt](https://github.com/OpenPrinting/cups-filters/files/8875852/attrs.txt)
[avahi-browse-ipp-out.txt](https://github.com/OpenPrinting/cups-filters/files/8875853/avahi-browse-ipp-out.txt)
[avahi-browse-ipps-out.txt](https://github.com/OpenPrinting/cups-filters/files/8875854/avahi-browse-ipps-out.txt)

> By the way, I have made use of my moderator powers to edit your initial post to make it more readable, to not make code characters be eaten by the markdown support. Please have a look into your edited post by clicking the 3 dots at the upper right, then "Edit" (do not actually edit, only have a look at your post's "source code"). Important is to put code pieces between backticks. A line with only 3 backticks marks start or end of multi-line code blocks.

Okay sorry, yes this looks way better.

**Comment by tillkamppeter** [comment]
The problem is not cups-filters, it is a bug in ippsample. For Apple Raster (URF) to work, the printer attributes must contain an `urf-supported` attribute, like for example this:
```
urf-supported (1setOf keyword) = CP1,MT1-2-8-9-10-11,PQ3-4-5,RS300-600,SRGB24,OB10,W8,DEVW8,DEVRGB24,ADOBERGB24,DM3,FN3,IS1-2,V1.4
```
In addition to some printer properties this tells especially with which resolutions, color spaces, and color depths Apple Raster data is accepted by the printer. It is **required** for Apple Raster printing to work and if it is missing on a printer which accepts nothing else than Apple Raster, the printer gets unusable.

As it is required, cups-filter relies on it. The PPD generator fails because it starts with selecting Apple Raster as the output format (no alternatives) and then later on is not able to complete building the PPD because of the `urf-supported` attribute missing.

If you had a PPD for your printer the filters would choke on not knowing resolution and color space for rasterizing the job.

So please report this bug to the ippsample project. Tell your `ippserver` command line and attach your `attrs.txt` file. And be patient, Michael Sweet has a lot to do these days.
