### ISSUE TITLE
[LPD] filter failed with Canon ImageRunner Advanced series

### ISSUE THREAD

**Issue by Germano0** [OpenPrinting/cups-filters#474]
I have been experiencing this problem with various Canon ImageRunner Advanced series printers and various Fedora machines.
Everythime I try to print any kind of file (for example pdf, jpg, odt), the system returns `filter failed` error. I attached full CUPS debug logs: 
[cups-filter_failed.txt](https://github.com/OpenPrinting/cups-filters/files/9110966/cups-filter_failed.txt)

How I reproduce the problem in my use case where the printer is a `Canon iR-ADV C5535 III`:

- open localhost:631 in your browser
- `admin` tab -> `add printer`
- as `Connection:` insert for example `lpd://10-1003-CANC3.print.cern.ch/10-1003-CANC3`
- download drivers https://files.canon-europe.com/files/soft45517/Software/Cque_Linux_Driver_4.09_64_EN.rpm unpack them and inside CUPS interface give the `canon/opt/cel/ppd/cel-iradvc5535III-ps-en.ppd.gz` as printer driver
- once the printer has been added in CUPS, print a file

**System specs**:
- Fedora 36
- cups-2.4.2-1.fc36.x86_64
- cups-client-2.4.2-1.fc36.x86_64
- cups-filesystem-2.4.2-1.fc36.noarch
- cups-filters-1.28.15-1.fc36.x86_64
- cups-filters-braille-1.28.15-1.fc36.x86_64
- cups-filters-libs-1.28.15-1.fc36.x86_64
- cups-ipptool-2.4.2-1.fc36.x86_64
- cups-libs-2.4.2-1.fc36.i686
- cups-libs-2.4.2-1.fc36.x86_64
- cups-pk-helper-0.2.6-14.fc36.x86_64
- foomatic-db-filesystem-4.0-73.20210611.fc36.noarch
- foomatic-db-ppds-4.0-73.20210611.fc36.noarch
- foomatic-db-4.0-73.20210611.fc36.noarch
- gutenprint-cups-5.3.4-8.fc36.x86_64
- python3-cups-2.0.1-12.fc36.x86_64
- avahi service running

**Comment by zdohnal** [comment]
Hi Germano,

from the logs:

```
lug 14 12:03:24 machine cupsd[515617]: [Job 12] Starting renderer with command: \"/bin/cat - | sicgsfilter -MPS -NP  -xV1 -A1 -uuser -V\"test.pdf\" -n1 \"
lug 14 12:03:24 machine cupsd[515617]: [Job 12] Starting process \"kid3\" (generation 1)
lug 14 12:03:24 machine cupsd[515617]: [Job 12] Starting process \"kid4\" (generation 2)
lug 14 12:03:24 machine cupsd[515617]: [Job 12] Starting process \"renderer\" (generation 2)
lug 14 12:03:24 machine cupsd[515617]: [Job 12] JCL: \033%-12345X@PJL
lug 14 12:03:24 machine cupsd[515617]: [Job 12] <job data>
lug 14 12:03:24 machine cupsd[515617]: [Job 12] /bin/bash: riga 1: sicgsfilter: comando non trovato
lug 14 12:03:24 machine cupsd[515617]: [Job 12] renderer exited with status 127
```

The Canon driver expects ```sicgsfilter``` binary on your machine, but there is no such filter at least on Fedora. Ask Canon support to provide you the binary or, the better, try driverless printing instead of lpd backend+driver (enabling IPP and HTTP suffices on the printer, then enable IPP in your machine's firewall) - according https://support.apple.com/en-us/HT201311 the device should support AirPrint.

Once you enable the prereq, you can install your printer by:

```
$ lpadmin -p 10-1003-CANC3 -v ipp://10-1003-CANC3.print.cern.ch:631/ipp/print -m everywhere -E
```

**Comment by tangyanli** [comment]
> The Canon driver expects sicgsfilter binary on your machine, but there is no such filter at least on Fedora.

The sicgsfilter file is in the package Cque_Linux_Driver_4.09_64_EN.rpm, you can use command `# rpm -i Cque_Linux_Driver_4.09_64_EN.rpm` to install it.

**Comment by Germano0** [comment]
You are right. Installing the Canon RPM file that contains the sicgsfilter executable, fixed the problem.
I apologize for having opened this ticket.
Best regards

**Comment by tillkamppeter** [comment]
Already solved, closing ...
