### ISSUE TITLE
Print speed slows down

### ISSUE THREAD

**Issue by 19940610mxh666** [OpenPrinting/cups-filters#489]
CUPS：2.2.2
CUPS-filter:1.13.4
When printing a pdf file, the first three pages are faster and the rest is slower.
![image](https://user-images.githubusercontent.com/26272545/198213593-1e3d0314-7fc6-4661-81a4-e074c3dc02fb.png)
I can't understand how this problem happened.Can anyoune help me?？Thanks

**Comment by 19940610mxh666** [comment]
![image](https://user-images.githubusercontent.com/26272545/198224314-3ecf46ef-b1e8-442e-9ed5-49e1afbe1a0b.png)
delia113raster is modified with gstoraster

**Comment by metabiswadeep** [comment]
Please share the log file in debug mode of cups. Also please provide more information about the file you printed. If possible please share the file you printed.

**Comment by metabiswadeep** [comment]
@19940610mxh666 could you please share the required information?

**Comment by tillkamppeter** [comment]
No answer from original poster, so we cannot investigate. Closing ...
