### ISSUE TITLE
How to submit a report on security vulnerabilities to this project?

### ISSUE THREAD

**Issue by WinMin** [OpenPrinting/cups-filters#495]
How to submit a report on security vulnerabilities to this project?

**Comment by WinMin** [comment]
If it is convenient for me to submit the vulnerability report directly on this issue? @michaelrsweet  @tillkamppeter

**Comment by michaelrsweet** [comment]
I believe you can submit them through the [Github security advisory page](https://github.com/OpenPrinting/cups-filters/security/advisories).

**Comment by WinMin** [comment]
> I believe you can submit them through the [Github security advisory page](https://github.com/OpenPrinting/cups-filters/security/advisories).

But this page can only be posted by the owner. My suggestion is that you give me an email and I will tell you the details of the vulnerability.

**Comment by tillkamppeter** [comment]
I have enabled private security vulnerability reporting for the cups-filters project now.

Please click on "Security" at the top, then "Advisories" on the left and after that click the green button "New draft security advisory" at the upper right. Now fill the form and submit.

**Comment by WinMin** [comment]
> I have enabled private security vulnerability reporting for the cups-filters project now.
> 
> Please click on "Security" at the top, then "Advisories" on the left and after that click the green button "New draft security advisory" at the upper right. Now fill the form and submit.

I have submitted the report, please check it.

**Comment by tillkamppeter** [comment]
I have now enabled private vulnerability  reporting for all OpenPrinting repositories.

Thanks a lot for your report.
