### ISSUE TITLE
Can't build cups-filters 2.0b2 on Debian 11.6

### ISSUE THREAD

**Issue by cyborgnrw** [OpenPrinting/cups-filters#501]
Hey guys,

I've try to build it on latest Debian 11.6 but ./configure does not find the package libppd.

> ./configure
> checking for a BSD-compatible install... /usr/bin/install -c
> checking whether build environment is sane... yes
> checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
> checking for gawk... gawk
> checking whether make sets $(MAKE)... yes
> checking whether make supports nested variables... yes
> checking whether make supports nested variables... (cached) yes
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables...
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking whether gcc understands -c and -o together... yes
> checking whether make supports the include directive... yes (GNU style)
> checking dependency style of gcc... gcc3
> checking for g++... g++
> checking whether we are using the GNU C++ compiler... yes
> checking whether g++ accepts -g... yes
> checking dependency style of g++... gcc3
> checking whether g++ supports C++11 features by default... yes
> checking build system type... x86_64-pc-linux-gnu
> checking host system type... x86_64-pc-linux-gnu
> checking for ld used by gcc... /usr/bin/ld
> checking if the linker (/usr/bin/ld) is GNU ld... yes
> checking for shared library run path origin... done
> checking how to run the C++ preprocessor... g++ -E
> checking for grep that handles long lines and -e... /usr/bin/grep
> checking for egrep... /usr/bin/grep -E
> checking for iconv... yes
> checking for working iconv... yes
> checking for iconv declaration...
>          extern size_t iconv (iconv_t cd, char * *inbuf, size_t *inbytesleft, char * *outbuf, size_t *outbytesleft);
> checking how to run the C preprocessor... gcc -E
> checking whether ln -s works... yes
> checking whether ln -s -r -f works... yes
> checking whether make sets $(MAKE)... (cached) yes
> checking how to print strings... printf
> checking for a sed that does not truncate output... /usr/bin/sed
> checking for fgrep... /usr/bin/grep -F
> checking for ld used by gcc... /usr/bin/ld
> checking if the linker (/usr/bin/ld) is GNU ld... yes
> checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
> checking the name lister (/usr/bin/nm -B) interface... BSD nm
> checking the maximum length of command line arguments... 1572864
> checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
> checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
> checking for /usr/bin/ld option to reload object files... -r
> checking for objdump... objdump
> checking how to recognize dependent libraries... pass_all
> checking for dlltool... no
> checking how to associate runtime and link libraries... printf %s\n
> checking for ar... ar
> checking for archiver @FILE support... @
> checking for strip... strip
> checking for ranlib... ranlib
> checking command to parse /usr/bin/nm -B output from gcc object... ok
> checking for sysroot... no
> checking for a working dd... /usr/bin/dd
> checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
> checking for mt... mt
> checking if mt is a manifest tool... no
> checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> checking for dlfcn.h... yes
> checking for objdir... .libs
> checking if gcc supports -fno-rtti -fno-exceptions... no
> checking for gcc option to produce PIC... -fPIC -DPIC
> checking if gcc PIC flag -fPIC -DPIC works... yes
> checking if gcc static flag -static works... yes
> checking if gcc supports -c -o file.o... yes
> checking if gcc supports -c -o file.o... (cached) yes
> checking whether the gcc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking whether -lc should be explicitly linked in... no
> checking dynamic linker characteristics... GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... yes
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... yes
> checking whether to build static libraries... yes
> checking how to run the C++ preprocessor... g++ -E
> checking for ld used by g++... /usr/bin/ld -m elf_x86_64
> checking if the linker (/usr/bin/ld -m elf_x86_64) is GNU ld... yes
> checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking for g++ option to produce PIC... -fPIC -DPIC
> checking if g++ PIC flag -fPIC -DPIC works... yes
> checking if g++ static flag -static works... yes
> checking if g++ supports -c -o file.o... yes
> checking if g++ supports -c -o file.o... (cached) yes
> checking whether the g++ linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking dynamic linker characteristics... (cached) GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> checking for pkg-config... /usr/bin/pkg-config
> checking pkg-config is at least version 0.20... yes
> checking whether NLS is requested... yes
> checking for msgfmt... no
> checking for gmsgfmt... :
> checking for xgettext... no
> checking for msgmerge... no
> checking for CFPreferencesCopyAppValue... no
> checking for CFLocaleCopyCurrent... no
> checking for GNU gettext in libc... yes
> checking whether to use NLS... yes
> checking where the gettext function comes from... libc
> checking for cups-config... /usr/bin/cups-config
> checking for libcupsfilters... yes
> checking for libppd... no
> configure: error: Package requirements (libppd) were not met:
> 
> No package 'libppd' found
> 
> Consider adjusting the PKG_CONFIG_PATH environment variable if you
> installed software in a non-standard prefix.
> 
> Alternatively, you may set the environment variables LIBPPD_CFLAGS
> and LIBPPD_LIBS to avoid the need to call pkg-config.
> See the pkg-config man page for more details.
> 

The package libppd0 and libppd-dev is already installed.

> dpkg -s libppd0
> Package: libppd0
> Status: install ok installed
> Priority: optional
> Section: libs
> Installed-Size: 62
> Maintainer: A Mennucc1 <mennucc1@debian.org>
> Architecture: amd64
> Source: libppd
> Version: 2:0.10-7.3
> Depends: libc6 (>= 2.7), libglib2.0-0 (>= 2.12.0)
> Description: postscript PPD file library
>  PostScript was designed as a device independent language. To be able
>  to access device specific features like selecting different paper
>  trays and turning on different imaging models, each printer vendor
>  supplies a PostScript Printer Definition or PPD file. This library
>  reads those PPD files and provides functions that allow a program to
>  modify PostScript print jobs to acces these special features.

> dpkg -s libppd-dev
> Package: libppd-dev
> Status: install ok installed
> Priority: optional
> Section: libdevel
> Installed-Size: 116
> Maintainer: A Mennucc1 <mennucc1@debian.org>
> Architecture: amd64
> Source: libppd
> Version: 2:0.10-7.3
> Depends: libppd0 (= 2:0.10-7.3), libc6-dev
> Description: postscript PPD file library, development kit
>  This package contains the static library and header files used in
>  development of programs that use libppd.

> ls -la /usr/lib |grep libp
> -rw-r--r--  1 root root  74448 Dec 18  2016 libppd.a
> lrwxrwxrwx  1 root root     15 Dec 18  2016 libppd.so -> libppd.so.1.0.1
> lrwxrwxrwx  1 root root     15 Dec 18  2016 libppd.so.1 -> libppd.so.1.0.1
> -rw-r--r--  1 root root  43472 Dec 18  2016 libppd.so.1.0.1

> ls -la /usr/include |grep ppd
> -rw-r--r--  1 root root   2251 Dec 18  2016 ppdenums.h
> -rw-r--r--  1 root root   8282 Dec 18  2016 ppd.h
> -rw-r--r--  1 root root   4081 Dec 18  2016 ppdmacros.h

Anyone know how to solve that?!

Best regards

**Comment by tillkamppeter** [comment]
The libppd you are using is wrong. You need at least version 2.0b2 to build cups-filters 2.0b2. The 0.10.x is a 20-year old approach to support PPD files with LPD and LPRng, by separating the PPD file support code from CUPS (1.0.x). This was not done by me and is from the time before OpenPrinting even existed.

You need the current 2.x versions which I have created to conserve the PPD file support of CUPS for legacy printer drivers when CUPS does away with PPD file support in version 3.x. In Debian you find this version only in Experimental, as its first beta release was too close to the Feature Freeze of Bookworm.

Or you need to build libppd from source, and after that build cups-filters from source.

But before you begin, uninstall the Debian packages libppd0 and libppd-dev. If gpr is also installed, uninstall that one, too.
