### ISSUE TITLE
Cant build cups-filters (last) on Ubuntu 

### ISSUE THREAD

**Issue by Saddy256** [OpenPrinting/cups-filters#509]
Ubuntu 20.04.2 LTS
Linux mserv 5.4.0-139-generic #156-Ubuntu SMP Fri Jan 20 17:27:18 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

Error with make:
```
make  all-recursive
make[1]: вход в каталог «/home/saddy/Downloads/cups-filters-master»
make[2]: вход в каталог «/home/saddy/Downloads/cups-filters-master»
  CC       backend/parallel-parallel.o
  CCLD     parallel
/usr/bin/ld: backend/parallel-parallel.o: in function `side_cb':
/home/saddy/Загрузки/cups-filters-master/backend/parallel.c:841: undefined reference to `cfIEEE1284GetDeviceID'
/usr/bin/ld: backend/parallel-parallel.o: in function `list_devices':
/home/saddy/Загрузки/cups-filters-master/backend/parallel.c:422: undefined reference to `cfIEEE1284GetDeviceID'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1683: parallel] Ошибка 1
make[2]: выход из каталога «/home/saddy/Downloads/cups-filters-master»
make[1]: *** [Makefile:2635: all-recursive] Ошибка 1
make[1]: выход из каталога «/home/saddy/Downloads/cups-filters-master»
make: *** [Makefile:1344: all] Ошибка 2

```

result of `./confugure`:
```
configure:
==============================================================================
Environment settings:
	CFLAGS:                                    -g -O2 -Wall -std=gnu11 -D_GNU_SOURCE
	CXXFLAGS:                                   -Wall  -D_GNU_SOURCE
	LDFLAGS:                                   
Build configuration:
	cups-config:     system
	foomatic:        yes
	poppler:         yes
	ghostscript:     yes
	gs-path:         system
	mutool:          yes
	mutool-path:     system
	ippfind-path:    system
	imagefilters:    yes
	pstops:          no
	rastertopwg:     no
	shell:           /bin/bash
	avahi:           yes
	universal CUPS filter: yes
	individual CUPS filters: no
	driverless:      yes
	werror:          no
==============================================================================
```

same with cups-filters-2.0b3.tar.gz

**Comment by tillkamppeter** [comment]
Did you install libcupsfilters 2.0b3 and libppd 2.0b3 (or current GIT masters of these)?

**Comment by Saddy256** [comment]
Yes, libcupsfilters 2.0b3 and libppd 2.0b3 build and installed right before

**Comment by Saddy256** [comment]
May be old packages can mess? dpkg -l |grep libpp
ii  libppd-dev                            2:0.10-7.3                          amd64        postscript PPD file library, development kit
ii  libppd0                               2:0.10-7.3                          amd64        postscript PPD file library

**Comment by tillkamppeter** [comment]
Yes, try uninstalling libppd 0.x and libcupsfilters/cupsfilters 1.x packages. libcups and libcupsimage2 are OK.

**Comment by Saddy256** [comment]
I removed old libppd + libcupsfilters+cupsfilters and make uninstall/install from git and got new erros:

make[2]: вход в каталог «/home/saddy/cups-filters-2.0b3»
  CCLD     commandtoescpx
/usr/bin/ld: /usr/lib/libppd.so: undefined reference to `cfCMYKSetLtDk'
/usr/bin/ld: /usr/lib/libppd.so: undefined reference to `cfFilterUniversal'
/usr/bin/ld: /usr/lib/libppd.so: undefined reference to `cfFilterGetEnvVar'

**Comment by Saddy256** [comment]
rebuilding of all (libppd+libcupsfilters) remove erros, thanks.
