### ISSUE TITLE
Printing multiple copies on Plotter HP Designjet T520

### ISSUE THREAD

**Issue by SoniaBalodi** [OpenPrinting/cups-filters#52]
Hello,

I am trying to print multiple copies to a plotter setup in CUPS. Plotter model is HP Designjet T520, since CUPS doesn't have driver for this model i am using an alternative driver HP Designjet T1100 pcl.
I am using library : https://github.com/williamkapke/ipp to send prints, Print request consists of : 
1) data (image)
2) operation-attributes-tag {
    job-name='any job name'
   document-format = 'image/png' }
3) Job-attributes-tag {
   copies : 2,
   media : 'om_a-4-transverse_297.04x209.9mm'
    }

This prints only 1 image from plotter.

As per Michael Sweet suggestion I also printed image from CUPS using command prompt : 
lp -d UAStore10 -n 3 -o media=A4.Transverse PlotterA4.png 

Same result only 1 print.

CUPS Version : 2.1.3
OS : Ubuntu 16.04.4 LTS 

Could you please have a look at this one and suggest a solution ? 
I already added this issue in CUPS github : https://github.com/apple/cups/issues/5352

Please let me know if I should do some more tests or any info is needed.
Thank you,
Sonia

**Comment by tillkamppeter** [comment]
There have been several fixes in cups-filters. Could you try with a newer version (or with a newer Ubuntu, like 18.04 LTS)?

**Comment by Dapeng-W** [comment]
since which version?

**Comment by tillkamppeter** [comment]
No  reaction of original poster any more, closing ...
