### ISSUE TITLE
JobSheets option is not forwarded to remote printer queues created by cups-browsed

### ISSUE THREAD

**Issue by imsedgar** [OpenPrinting/cups-filters#54]
We have set JobSheets option with a value like "mybanner none" to a shared printer queue. File /usr/share/cups/banners/mybanner is available on cups print server and cups print client.

On our cups clients we run cups-browsed to make the shared printers from our cups print server available to all our linux computers. The problem is, that remote print queues created by cups-browsed all have "JobSheets none none" in /etc/cups/printers.conf, but the should have the same value as the remote shared printer have set.

It seems that the option JobSheets value is not forwarded and set to the client printer queue.

We run Fedora 28 with package cups-2.2.8-2.fc29 from koji, rebuild for Fedora 28 by myself, and cups-filters-1.20.4, based on cups-filters-1.20.3-5.fc29 from koji and updated to cups-filters 1.20.4 and rebuild for Fedora 28 by myself.

**Comment by imsedgar** [comment]
Additional info:
I have used option "-o job-sheets-default=mybanner,none" for "lpadmin" command on cups server to create the printer queue.

Output of "lpoptions -p printername" contains "job-sheets=none,none" on cups client, on cups server it contains "job-sheets=mybanner,none".

**Comment by KurtPfeifle** [comment]
> Output of "lpoptions -p printername" contains "job-sheets=none,none" on cups client, on cups server it contains "job-sheets=mybanner,none".

What is the output if you run `lpoptions -h cupsserver -p printername` on the client?

**Comment by imsedgar** [comment]
> What is the output if you run `lpoptions -h cupsserver -p printername` on the client?

The output contains the values of option JobSheets contained in file /etc/cups/printers.conf for printername.
For example, if /etc/cups/printers.conf contain "JobSheets standard none" for printername, then the output of "lpoptions -h cupsserver -p printername" contains "job-sheets=standard,none" (and other options, of course).

copies=1 device-uri=ipp://printername/ipp finishings=3 job-cancel-after=10800 job-hold-until=no-hold job-priority=50 job-sheets=standard,none marker-change-time=1543675140 marker-colors=#00FFFF,#FF00FF,#FFFF00,#000000,none,none,none marker-high-levels=100,100,100,100,99,99,99 marker-levels=59,69,58,18,-1,-1,-1 marker-low-levels=10,10,10,10,0,0,0 marker-names='Toner\ Cartridge\ (C),Toner\ Cartridge\ (M),Toner\ Cartridge\ (Y),Toner\ Cartridge\ (K),Waste\ Toner\ Box,Staple\ Cartridge,Hole-Punch\ Scrap\ Box' marker-types=toner,toner,toner,toner,waste-toner,staples,waste-paper number-up=1 printer-commands=none printer-info='printername, my description of the printer' printer-is-accepting-jobs=true printer-is-shared=true printer-is-temporary=false printer-location='our printer location' printer-make-and-model='oour printer model' printer-state=3 printer-state-change-time=1543675150 printer-state-reasons=cups-ipp-conformance-failure-report,cups-ipp-missing-job-history,media-low-warning,other-report printer-type=12668 printer-uri-supported=ipp://cupsserver:631/printers/printername

**Comment by tillkamppeter** [comment]
What happens if you print (from the client)? Does the banner page get printed? If not, does it get printed if you print with
```
lp -o job-sheets=mybanner,none ...
```
Does it get printed if you stop CUPS on the client, edit printers.conf on the client to have
```
JobSheets mybanner none
```
start CUPS again and then print?
Does it print another banner if you print with
```
lp -o job-sheets=[banner name],none ...
```
with `[banner name]` the name of another existing banner file? Or does it even happen that it prints two banners in certain cases?

**Comment by tillkamppeter** [comment]
No answer from the original poster, closing ...
