### ISSUE TITLE
If I want to print 2 pages on 1. But it prints the 2 pages in the size of 4 pages

### ISSUE THREAD

**Issue by apbonn** [OpenPrinting/cups-filters#55]
Hi,

im using cups 1.7.5 on a pi3.
It worked great, but since 2 weeks i got this issue.

I want to print 2 pages on 1 page.
But the result is, that the 2 pages have the size, like when i would like to print 4 pages on 1.
So each page has not 50% size on the page, it has 25%.

If I just print one page on one page it works great.
If I connect the printer to my pc, it also works with 2 on 1 .

I rebooted and of course reinstalled my printer. No change.
The settings in word are correct or in the chrome browser.

So there must be an issue with cups.

Any ideas how to solve it ?

**Comment by tillkamppeter** [comment]
How did you send the job? Did you use any GUI application with its print dialog? Which one if so?
Or did you print by the command line?
Did you print from your pi3 system or from an external client? Which OS, CUPS, cups-filters version do you have on the client?
Which cups-filters version are you using on the pi3?
Which options did you set for the job? Which option default settings has you print queue? Do you have a `~/.cups/lpoptions` file?
Which printer model are you using? How did you create your print queue? Can you attach the printer's PPD file?
Please set CUPS to the debug mode (`cupsctl --debug-logging`) do the print job again and attach `/var/log/cups/error_log`. If you print from a client which also runs CUPS, please set CUPS on both client and server into debug mode and attach `/var/log/cups/error_log` of both client and server.

**Comment by apbonn** [comment]
Hi, will try to get all Informations.

But the Thing is, i changed nothing. No
Updates , Upgrades 


I printed with word 2017 on mac os high Sierra.
The Printer is Directly Connected to my pi3.
It is a HP laserjet p1005

**Comment by tillkamppeter** [comment]
I have released cups-filters 1.21.4 now which contains fixes against duplicate execution of page management options. Also the newest CUPS (2.2.9) contains appropriate fixes.
Can you please test with these version whether this also covers your issue?

**Comment by tillkamppeter** [comment]
No response from the original poster, so I assume that my changes have fixed it. Closing ...
