### ISSUE TITLE
MEMORY_LEAK in utils/cups-browsed.c

### ISSUE THREAD

**Issue by ellena13** [OpenPrinting/cups-filters#552]
* Dynamic memory, referenced by `buf`, **is allocated** at _cups-browsed.c:728_:

https://github.com/OpenPrinting/cups-filters/blob/8ac453d0c22a87984127f4c89bd5747d1409db23/utils/cups-browsed.c#L728
 
by calling function _malloc_ and **lost** at _cups-browsed.c:738_.

* Dynamic memory, referenced by `ppdsizename`, **is allocated** at _cups-browsed.c:2074_ :

https://github.com/OpenPrinting/cups-filters/blob/8ac453d0c22a87984127f4c89bd5747d1409db23/utils/cups-browsed.c#L2074

by calling function _malloc_ and **lost** at _cups-browsed.c:2081_.

* Dynamic memory, referenced by `ppdsizename`, **is allocated** at _cups-browsed.c:2753_:

https://github.com/OpenPrinting/cups-filters/blob/8ac453d0c22a87984127f4c89bd5747d1409db23/utils/cups-browsed.c#L2753

by calling function _malloc_ and **lost** at _cups-browsed.c:2758_.

The **free()** operator should be used **to free the allocated memory** space before the function ends, otherwise there will be a **MEMORY_LEAK**.

Found by Linux Verification Center ([portal.linuxtesting.ru](https://portal.linuxtesting.ru/)) with SVACE.

Author E. Bykhanova.

**Comment by zdohnal** [comment]
Please run your scanner on the latest cups-filters version - 2.0.0, thank you!

**Comment by tillkamppeter** [comment]
In cups-browsed 2.x the listed leaks are fixed.

**Comment by tillkamppeter** [comment]
Fixed the memory leaks in the 1.x branch via commit e25fd59a.
