### ISSUE TITLE
Remove avahi tests in configure

### ISSUE THREAD

**Issue by pierre-labastie** [OpenPrinting/cups-filters#556]
If avahi is not installed, and `--disable-avahi` is not passed, `configure` errors out. But this shouldn't happen, since neither `AVAHI_CFLAGS` nor `AVAHI_LIBS` nor `HAVE_AVAHI` is used in the code...

1. Uninstall avahi-dev if it is installed
2. run configure without passing `--disable-avahi`
3. It stops with a message starting with: "configure: error: Package requirements (avahi-client) were not met ..."
 
**Expected behavior**
Since avahi is nowhere used, it shouldn't be needed to have configure run to completion.

**System Information:**
 - reproducible on both debian bookworm and linux from scratch. cups-filters version is 2.0.0

**Comment by pierre-labastie** [comment]
This should be fixed by #558

**Comment by eli-schwartz** [comment]
Indeed, not sure why I didn't notice this to cross-link it, fixed ^^
