### ISSUE TITLE
Raise QPDF version requirement

### ISSUE THREAD

**Issue by tgurr** [OpenPrinting/cups-filters#56]
With the latest cups-filters-1.21.0 I get

```
filter/pdf.cxx:26:10: fatal error: qpdf/QPDFAcroFormDocumentHelper.hh: No such file or directory
 #include <qpdf/QPDFAcroFormDocumentHelper.hh>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
with having QPDF 8.0.2 installed.

`configure.ac` states `PKG_CHECK_MODULES([LIBQPDF], [libqpdf >= 3.0.2])` as the version requirement for QPDF.

Upgrading to QPDF 8.2.1 allowed cups-filters-1.21.0 to compile.

**Comment by tillkamppeter** [comment]
Fixed in commit a59a18abd
Thank you very much.
