### ISSUE TITLE
when we are using cups server for printing with brother printer by generating pdf the sizes are coming in different

### ISSUE THREAD

**Issue by MamataRao** [OpenPrinting/cups-filters#60]

**Comment by MamataRao** [comment]
how to print a default size from cups service using pdf.

**Comment by dheeraj135** [comment]
@MamataRao Try using ```-o media=X``` option. Have a look at the [documentation](https://www.cups.org/doc/options.html).

**Comment by tillkamppeter** [comment]
No more reaction from the original poster, closing ...
