### ISSUE TITLE
`foomatic-rip` directory is being ignored

### ISSUE THREAD

**Issue by MrQubo** [OpenPrinting/cups-filters#610]
**Describe the bug**

In `.gitignore` there's line `foomatic-rip`. This causes directory `filter/foomatic-rip/` to be ignored.

**Additional context**

Not really a bug, but a slight nuisance when working with the code. Mainly because tools like `ripgrep` or `ugrep` automatically skip files/directories ignored by `.gitignore`. It would also cause any new files added to this directory to be ignored.

I would propose to only ignore regular files and not directories, like so:
```gitignore
foomatic-rip
!foomatic-rip/
```

**Comment by tillkamppeter** [comment]
Fixed in commit 7e9a9902

Thanks for the report.
