### ISSUE TITLE
Help: I Want to Change Halftone Setting in Printer Driver (CUPS)

### ISSUE THREAD

**Issue by goldykav** [OpenPrinting/cups-filters#64]
I am using CUPS with the printer driver which use "application/vnd.cups-raster 10 rastertopj" and i am trying to get the look of Windows PC halftoning: dither 4x4 print/output but i am clueless where to change the setting for choosing different halftoning pattern..

i also contacted the Ghostscript support and they said halftoning is done by the driver and also told that If the driver is Ghostscript-based you may be able to change the halftone as you’d like, and yes this is indeed Ghostscript-based printer (Cups)driver cause when i open the .PPD file i see *Product: "(ESP Ghostscript)".

here is the printer driver/source: http://www.jfbdtp.com/Pentax/pj-linux-cups.tar.gz

this is the halftone output its printing: https://imgur.com/a/18hkC1H or https://imgur.com/download/7pTksX4

this is the output i am looking for: https://imgur.com/a/KZTQrkp or https://imgur.com/download/5FnpKEM

here is the side by side comparison: https://imgur.com/a/N1rZYSS on the left its what i am getting which i think call 'elliptical spot shape' and on the right side its what i am getting from Windows 7 PC from i select a generic driver with Halftoning selection: Dither 4x4.

Can you please guide me on how or where to change the halftoning of the printer filter/driver?
Thankyou

**Comment by tillkamppeter** [comment]
cups-filters does not do fine-tunable halftoning, the halftoning is done by the individual printer drivers and sometimes even only in the printer hardware or firmware. So there is no way to solve your problem by modifying anything in cups-filters (and also not in CUPS).
The Pentax driver also has no tunable entries in its PPD file, meaning that if the halftoning is done in the driver and not in the printer you cannot influence it by editing the PPD file. Fortunately the driver is open source, so you could modify the halftoning algorithm in the source code.
Closing as this is not a cups-filters issue.
