### ISSUE TITLE
build fails with poppler-0.71.0

### ISSUE THREAD

**Issue by fjaell** [OpenPrinting/cups-filters#74]
Please reopen https://github.com/OpenPrinting/cups-filters/issues/69, the issue is still not fixed.

filter/pdftoraster.cxx: In function 'void outPage(PDFDoc*, Catalog*, int, SplashOutputDev*, cups_raster_t*)':
filter/pdftoraster.cxx:1821:6: error: 'gTrue' was not declared in this scope
      gTrue,gTrue,gTrue);
      ^~~~~
filter/pdftoraster.cxx:1821:6: note: suggested alternative: 'gfree'
      gTrue,gTrue,gTrue);
      ^~~~~
      gfree
filter/pdftoraster.cxx: In function 'int main(int, char**)':
filter/pdftoraster.cxx:2131:5: error: 'gFalse' was not declared in this scope
     gFalse,paperColor,gTrue
     ^~~~~~
filter/pdftoraster.cxx:2131:5: note: suggested alternative: 'pause'
     gFalse,paperColor,gTrue
     ^~~~~~
     pause
filter/pdftoraster.cxx:2131:23: error: 'gTrue' was not declared in this scope
     gFalse,paperColor,gTrue
                       ^~~~~
filter/pdftoraster.cxx:2131:23: note: suggested alternative: 'gfree'
     gFalse,paperColor,gTrue
                       ^~~~~
                       gfree
filter/pdftoraster.cxx:2157:17: warning: 'void ppdClose(ppd_file_t*)' is deprecated: Use cupsCopyDestInfo and friends instead. [-Wdeprecated-declarations]
     ppdClose(ppd);
                 ^
In file included from filter/pdftoraster.cxx:49:0:
/usr/include/cups/ppd.h:372:14: note: declared here
 extern void  ppdClose(ppd_file_t *ppd) _PPD_DEPRECATED;
              ^~~~~~~~
make[1]: *** [Makefile:4363: pdftoraster-pdftoraster.o] Error 1

**Comment by tillkamppeter** [comment]
Same as issue #69.
