### ISSUE TITLE
cups-browsed crashed in update_cups_queues

### ISSUE THREAD

**Issue by imsedgar** [OpenPrinting/cups-filters#79]
cups-browsed crashed when restarted by systemctl restart cups (when cups-browsed was running). See attatched file.
I have Fedora 29 with cups-2.2.10 and cups-filters-1.21.5, build rpm packages myself from source, based on the latest Fedora packages from koji (but with newer source from github).

[cups-browsed-crashed.txt](https://github.com/OpenPrinting/cups-filters/files/2670272/cups-browsed-crashed.txt)

**Comment by tillkamppeter** [comment]
This problem should be fixed with f3d48ecda, as I got already a a bug report via Debian:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=916149

**Comment by imsedgar** [comment]
Thanks, Till. In the meantime I have build and installed a package from current master git, which is currently commit f3d48ec, and yes, it seems it runs without crash (I haven't checked all systems yet).
