### ISSUE TITLE
cups-browsed created and deletes remote cups queues repeatedly

### ISSUE THREAD

**Issue by imsedgar** [OpenPrinting/cups-filters#80]
cups-browsed seams to create remote cups queues, and then it deletes the created queues. This occures repeatedly and consumes cpu time of cups process.

I don't know why the queues are deleted. I'm not sure, but I think it occurs first in some cups-filters 1.21.* versions.

There is also a strange error message, I haven't found the cause of it, and I don't know if it is related to this problem, because I found this message since a long time.

 I have Fedora 29 with cups-2.2.10 and cups-filters-1.21.5, build rpm packages myself from source, based on the latest Fedora packages from koji (but with newer source from github).

[cups-browsed-crashed.txt](https://github.com/OpenPrinting/cups-filters/files/2670299/cups-browsed-crashed.txt)

**Comment by tillkamppeter** [comment]
The crash should be already fixed, see issue #79.
If anything else is not OK, test with the current GIT snapshot and put a line "`DebugLogging file`" into cups-browsed.conf. After having seen something having gone wrong, attach the `/var/log/cups/cups-browsed_log` file. Thanks.

**Comment by imsedgar** [comment]
I did some tests.
When I run cupsd on a cups server, but not cups-browsed, then remote printers are found by cups-browsed on cups clients, and cupsd does not use much cpu time.

When I start cups-browsed on the cups server too, then cupsd creates a high load on cups clients. It seems that cups-browsed creates a local queue for remote cups queues, but cupsd deletes it soon after creation. I found no hint why this happens. I also had cupsd running in LogLevel debug, but I found no hint what causes the deletion.

I add an extract of /var/log/cups/cups-browsed_log from a cups client (with some values replaced for privacy). It starts when I had started cupsd, then I have started cups-browsed, then I have stopped cups-browsed, then I have stopped cupsd, each on mycupsserver2. I have created mycupsserver2 extra for testing. Our normal mycupsserver1 is still running, only with cupsd, these printers also appears in the log.
The test printer is named myremotetestprinter.

I also add cupsd.conf and cups-browsed from cups server (mycupsserver2) (only non-comment lines).

**Comment by imsedgar** [comment]
file:///home/edgar/tst/cups-browsed_log-2018-12-13.txt
file:///home/edgar/tst/mycupsserver2-cupsd.conf
file:///home/edgar/tst/mycupsserver2-cups-browsed.conf

**Comment by imsedgar** [comment]
[cups-browsed_log-2018-12-13.txt](https://github.com/OpenPrinting/cups-filters/files/2674355/cups-browsed_log-2018-12-13.txt)

[mycupsserver2-cupsd.conf.txt](https://github.com/OpenPrinting/cups-filters/files/2674356/mycupsserver2-cupsd.conf.txt)
[mycupsserver2-cups-browsed.conf.txt](https://github.com/OpenPrinting/cups-filters/files/2674357/mycupsserver2-cups-browsed.conf.txt)

**Comment by tillkamppeter** [comment]
Fixed in 257086970ae97
To assure that a the local queue created by cups-browsed gets permanent, cups-browsed has removed and re-created it (it failed to set the printer-is-shared bit as we are pointing to a remote CUPS queue) and the removal causes a notification by the local cupsd and triggers on_printer_deleted() which schedules our local queue for immediate re-creation, which causes an infinite loop.
No I let on_printer_deleted() check whether the queue which triggered the notification is really gone and only then it schedules re-creation.
Please test.
