### ISSUE TITLE
cupsfilter hangs with 100% cpu usage with corrupted gif

### ISSUE THREAD

**Issue by ocean1** [OpenPrinting/cups-filters#82]
Potential denial of service in cupsfilter (through imagetopdf) with the following corrupted gif 
[1051.gif.zip](https://github.com/OpenPrinting/cups-filters/files/2714873/1051.gif.zip).

Reproducible with: `cupsfilter 1051.gif`

**Comment by dheeraj135** [comment]
@ocean1 I was able to reproduce this error in the latest version of cups-filters. I think, when the input file is corrupted, the program should exit gracefully rather than a segfault.
