### ISSUE TITLE
cups-browsed unable to add printer.

### ISSUE THREAD

**Issue by dheeraj135** [OpenPrinting/cups-filters#85]
I am trying to add ipp printer(driverless) in cups. When I add it through web interface everything works smoothly but cups-browsed is not able to automatically add it. The weird thing is when I try to do the same thing on a virtual machine, cups-browsed automatically adds that printer.
I have Ubuntu: 18.04, cups: v2.3b7 and cups-filters: v1.21.6 on both main computer and virtual machine.
How can I resolve this?
cups-browsed logs:
![screenshot from 2019-01-03 23-57-10](https://user-images.githubusercontent.com/28601604/50686699-6df36900-1044-11e9-8a2e-6358163e0921.png)
cups error_log:

> d [03/Jan/2019:23:31:27 +0530] [Client 2] cupsdReadClient: error=0, used=0, state=HTTP_STATE_WAITING, data_encoding=HTTP_ENCODING_LENGTH, data_remaining=0, request=(nil)(), file=-1
D [03/Jan/2019:23:31:27 +0530] [Client 2] POST /admin/ HTTP/1.1
D [03/Jan/2019:23:31:27 +0530] cupsdSetBusyState: newbusy="Active clients and dirty files", busy="Dirty files"
D [03/Jan/2019:23:31:27 +0530] [Client 2] Read: status=200, state=6
d [03/Jan/2019:23:31:27 +0530] cupsdFindBest: uri="/admin", limit=10...
d [03/Jan/2019:23:31:27 +0530] cupsdFindBest: Location /admin/log(10) Limit 7f
d [03/Jan/2019:23:31:27 +0530] cupsdFindBest: Location /admin/conf(11) Limit 7f
d [03/Jan/2019:23:31:27 +0530] cupsdFindBest: Location /admin(6) Limit 7f
d [03/Jan/2019:23:31:27 +0530] cupsdFindBest: Location /(1) Limit 7f
d [03/Jan/2019:23:31:27 +0530] cupsdFindBest: best=/admin
d [03/Jan/2019:23:31:27 +0530] [Client 2] con->uri="/admin/", con->best=0x55c1bd34bde0(/admin)
D [03/Jan/2019:23:31:27 +0530] [Client 2] No authentication data provided.
d [03/Jan/2019:23:31:27 +0530] cupsdIsAuthorized: con->uri="/admin/", con->best=0x55c1bd34bde0(/admin)
d [03/Jan/2019:23:31:27 +0530] cupsdIsAuthorized: level=CUPSD_AUTH_ANON, type=None, satisfy=CUPSD_AUTH_SATISFY_ALL, num_names=0
d [03/Jan/2019:23:31:27 +0530] cupsdIsAuthorized: auth=CUPSD_AUTH_ALLOW...
D [03/Jan/2019:23:31:27 +0530] [Client 2] 2.0 CUPS-Add-Modify-Printer 12
d [03/Jan/2019:23:31:27 +0530] cupsdProcessIPPRequest(0x55c1bd3c9680[2]): operation_id=4003(CUPS-Add-Modify-Printer)
d [03/Jan/2019:23:31:27 +0530] cupsdProcessIPPRequest: operation-attributes-tag
d [03/Jan/2019:23:31:27 +0530] cupsdProcessIPPRequest: attributes-charset charset 'utf-8'
d [03/Jan/2019:23:31:27 +0530] cupsdProcessIPPRequest: attributes-natural-language naturalLanguage 'en-in'
d [03/Jan/2019:23:31:27 +0530] cupsdProcessIPPRequest: printer-uri uri 'ipp://localhost:631/printers/test1'
d [03/Jan/2019:23:31:27 +0530] cupsdProcessIPPRequest: requesting-user-name nameWithoutLanguage 'dj'
d [03/Jan/2019:23:31:27 +0530] cupsdProcessIPPRequest: printer-attributes-tag
d [03/Jan/2019:23:31:27 +0530] cupsdProcessIPPRequest: printer-state enum 'idle'
d [03/Jan/2019:23:31:27 +0530] cupsdProcessIPPRequest: printer-is-accepting-jobs boolean 'true'
d [03/Jan/2019:23:31:27 +0530] cupsdProcessIPPRequest: printer-location textWithoutLanguage ''
d [03/Jan/2019:23:31:27 +0530] cupsdProcessIPPRequest: cups-browsed-default boolean 'true'
d [03/Jan/2019:23:31:27 +0530] cupsdProcessIPPRequest: device-uri uri 'ipps://127.0.0.1:8000/ipp/print'
d [03/Jan/2019:23:31:27 +0530] cupsdProcessIPPRequest: printer-info textWithoutLanguage ''
D [03/Jan/2019:23:31:27 +0530] CUPS-Add-Modify-Printer ipp://localhost:631/printers/test1
d [03/Jan/2019:23:31:27 +0530] add_printer(0x55c1bd3c9680[2], ipp://localhost:631/printers/test1)
d [03/Jan/2019:23:31:27 +0530] cupsdFindPolicyOp(p=0x55c1bd34c290, op=4003(CUPS-Add-Modify-Printer))
d [03/Jan/2019:23:31:27 +0530] cupsdFindPolicyOp: Found exact match...
d [03/Jan/2019:23:31:27 +0530] cupsdIsAuthorized: con->uri="/admin/", con->best=0x55c1bd34e6a0((null))
d [03/Jan/2019:23:31:27 +0530] cupsdIsAuthorized: level=CUPSD_AUTH_USER, type=Basic, satisfy=CUPSD_AUTH_SATISFY_ALL, num_names=1
d [03/Jan/2019:23:31:27 +0530] cupsdIsAuthorized: op=4003(CUPS-Add-Modify-Printer)
d [03/Jan/2019:23:31:27 +0530] cupsdIsAuthorized: auth=CUPSD_AUTH_ALLOW...
D [03/Jan/2019:23:31:27 +0530] cupsdIsAuthorized: username=""
D [03/Jan/2019:23:31:27 +0530] [Client 2] Returning HTTP Unauthorized for CUPS-Add-Modify-Printer (ipp://localhost:631/printers/test1) from localhost
d [03/Jan/2019:23:31:27 +0530] [Client 2] cupsdSendError code=401, auth_type=0
D [03/Jan/2019:23:31:27 +0530] [Client 2] cupsdSendHeader: code=401, type="text/html", auth_type=0
d [03/Jan/2019:23:31:27 +0530] [Client 2] cupsdSendHeader: require "@SYSTEM"
D [03/Jan/2019:23:31:27 +0530] [Client 2] WWW-Authenticate: Basic realm=\"CUPS\", PeerCred, Local trc=\"y\"

**Comment by dheeraj135** [comment]
I tried running it with user "dj" and "root". 
Groups of user "dj" :
>  ~ groups dj
dj adm cdrom sudo dip plugdev lpadmin sambashare wireshark

Attached files:
[cupsd.conf](https://drive.google.com/open?id=1hNgzedqgPx41yp_7CFVUFINNQQqJpem-)
[cups-files.conf](https://drive.google.com/open?id=1lpcvbEM0uAHDtsl0G0nmTU9-zm0lu5T4)

**Comment by tillkamppeter** [comment]
Please add the line
```
DomainSocket /home/dj/cupsi/var/run/cups/cups.sock
```
to your `/etc/cups/cups-browsed.conf` and restart cups-browsed. Is it now able to create print queues?

**Comment by dheeraj135** [comment]
No. It is still not working.
Maybe it has something to do PeerCred? I found this line in cups log of my virtual machine:

> [Client 36] Authorized as root using PeerCred.

This line is printed every time cups-browsed is trying to add printer. So, cups-browsed is authorizing using PeerCred. But this is not happening on my main computer.

**Comment by dheeraj135** [comment]
@tillkamppeter any updates?

**Comment by tillkamppeter** [comment]
Unfortunately, I have no experience with PeerCred. I have always run cups-browsed as root and CUPS with a configuration so that root can create a queue. This way it always worked.

**Comment by dheeraj135** [comment]
Broken installation of ```libpam``` package was responsible for this error. So, I am closing this issue.
