### ISSUE TITLE
Cups daemon notifies avahi about printers before it starts responding to clients cups queries on port 631

### ISSUE THREAD

**Issue by kabassanov** [OpenPrinting/cups-filters#89]
Hello,

We use a cups server (2.2.8) with an avahi daemon for printer sharing.
We noticed that every time cupsd reloads its configuration (or when we restart it), remote linux clients (cupsd + avahi + cups-browsed) loose one or two printers from the server.
Some tests we made showed (in cups-browsed logs) that this issue concerns printers first rediscovered by the client. In addition, it seems that client tries to connect on server port 631 in order to get the PPD file, but server is not ready to reply yet. Printers never reappear (except if we restart cups-browsed on client side).

Well, it is also possible that there is some mess on the client side (concurrent remove/add of the same printer), isn't it?

My first idea was to put some initial delay before cups server starts sending notifications to avahi in order to be sure it has already started servicing cups on port 631... But it seems to be difficult to realize.

[cups-browsed-extract.txt](https://github.com/OpenPrinting/cups-filters/files/2759434/cups-browsed-extract.txt)

**Comment by tanmayanand44** [comment]
@kabassanov One possible solution is that instead of restarting cups-browsed everytime you can set ``BrowseInterval`` directive in cups-browsed.conf.

**Comment by kabassanov** [comment]
@tanmayanand44, do you mean that there is no default value if the entry is commented?
# BrowseInterval 60

I thought that there was some kind of mess when an annoncement had arrived, but the client was unable to join remote cups server, and lost the printer until restart. Restarting cups-browsed makes a kind of reset of it internal state. Am I wrong?

**Comment by tillkamppeter** [comment]
@tanmayanand44, "BrowseInterval" is NOT used at all for DNS-SD browsing. It is ONLY used for
- Classic CUPS broadcasting (for CUPS 1.5.x and older clients)
- LDAP
- "BrowsePoll"

**Comment by tanmayanand44** [comment]
@kabassanov Does this issue happens with a particular printer(s) always after cupsd restart on your cups server or any of printer(s) at random.

**Comment by kabassanov** [comment]
@tanmayanand44, it happens with the first (one or two) printers client gets from remote server broadcasts after restart.
We made a test blocking mdns annoncements on the server side just before cupsd restart and unblocking them after the end of the restart. And the issue disappeared, because client is not aware of the action. But it is not a real solution, because it doesn't work when server just receives a kill signal from newsyslog for instance...

**Comment by tanmayanand44** [comment]
@kabassanov What version of cups-filters on client did you use? I was able to successfully reproduce this issue with v1.8.3 but after upgrading to v1.20.2 this issue disappears.

**Comment by kabassanov** [comment]
@tanmayanand44 I've tried USB live releases of Fedora 28 and 29, so I suppose it was cups-filters-1.20.0-7.fc28.x86_64 and cups-filters-1.20.3-9.fc29.x86_64, but I'm unable to check right now.

**Comment by kabassanov** [comment]
Yes, just for confirmation: cups-filters-1.20.3-9.fc29.x86_64 in F29

**Comment by tillkamppeter** [comment]
@tanmayanand44, any further news about this?

**Comment by tanmayanand44** [comment]
@tillkamppeter I switched to latest version of cups-filters for testing and now after multiple restarts on server, it seems that sometimes client is not able to fetch those ppd file but after every 10s it retries and in subsequent tries, the client was actually find all the printers on the server. I am attaching the log which shows the initial failed attempts to find the all 4 printers together but eventually after 2-3 retries it did find all of them
[log.txt](https://github.com/OpenPrinting/cups-filters/files/3055976/log.txt)

**Comment by kabassanov** [comment]
@tanmayanand44 , is it a new feature for the client to retry fetching ppd files? Does "lpstat -p" show all your printers after that?

**Comment by tanmayanand44** [comment]
@kabassanov Retry feature existed even in v1.8.3, and using v1.8.3 I was able to reproduce this issue almost every restart and client was stuck at unable to find ppd after each retry. But after switching to the l v1.22.4, it takes some time to find all printer but it does find them all finally.

**Comment by kabassanov** [comment]
@tanmayanand44 , are you able to reproduce the failure with cups-filters-1.20.3 (-9.fc29.x86_64) ?

**Comment by tanmayanand44** [comment]
@kabassanov If I remember correctly, this issue existed on v1.20.2(which came with stock ubuntu18.04lts), but it showed up only after several restarts on the server, i.e., worked fine most times. I would request you to update to the latest release and then update us.

**Comment by tillkamppeter** [comment]
@kabassanov, we are now waiting for your answer for one month. Did you actually update and try out whether this solves your problem?
I will close here now. If you still suffer the problem after updating cups-filters please re-open this issue. Thanks.
