### ISSUE TITLE
pdftoraster uses non-public/internal APIs of Poppler

### ISSUE THREAD

**Issue by tillkamppeter** [OpenPrinting/cups-filters#9]
@sahilarora535 investigated the code of pdftoraster and writes:

> After going through the code, I found that a lot of poppler APIs are being used in [pdftoraster.cxx](https://github.com/OpenPrinting/cups-filters/blob/b72c0bf80f21085521508900130ec553fae089b7/filter/pdftoraster.cxx#L39) (please open the link which redirects to the line number). When I built cups-filters for the first time, I distinctively remember I had to install poppler as well since it is a dependency for cups-filters. However, even on installing, files such as “goo/gmem.h” (which are included in the filter) were not found, hence I had to make poppler from the source. Even that did not work. Hence, I had to use a flag which configuring poppler so that these files come along, and the command was *|./configure --enable-xpdf-headers|* to configure poppler. I guess these are the unstable APIs we have been talking about. My first impression of the code base is that pdftoraster has a lot of uses of poppler’s unstable APIs, and this is what it is. Please correct me if I am wrong.

We need an existing Poppler output device for raster output ot create one if there is no suitable one. Poppler has a `pdftoppm` utility which generates the genric PPM raster format, so Poppler's output device used by this utility can probably somehow made use of. I do not know the PPM and similar raster graphics formats, for example whether all color spaces available in PWG/CUPS Raster are supported.
Here we have different possibilities depending on what the output formats of `pdftoppm` are capable of:

1. A pdftoraster filter which calls `pdftoppm` on the command line and converts the output into PWG/CUPS Raster.
2. A pdftoraster filter which uses the Poppler output device which the `pdftoppm` utility uses, using only public APIs of Poppler and it wraps the output bitmap streams into valid PWG/CUPS Raster.
3. Either we extend the PPM/raster output device of Poppler to also support PWG/CUPS Raster or we create a new Poppler output device for PWG/CUPS Raster based on Poppler's existing PPM/raster output device. The changes on Poppler we have to submit upstream. Then we do a pdftoraster filter which uses this device.

In any case the new pdftoraster filter should not loose any features, especially support for all color spaces and color management as the current one has. 
Note: The same is probably the case for pdftoijs, pdftoopvp, and bannertopdf, but the former two we are deprecating curremtly (they are not installed by default any more) and the latter we will convert to use QPDF (Issue #8).

**Comment by sahilarora535** [comment]
The `pdftoppm` utility of poppler not only generates `PPM`, but is also capable of generating `jpeg`, `png` and `tiff` output files from a PDF file. The `pdftocairo` utility on the other hand is able to generate `ps`(Postscript), `eps`(Encapsulated Postscript) and `svg`(Scalable Vector Graphics) along with `jpeg`, `png` and `tiff`. I saw the [`cups-filters.convs.in`](https://github.com/OpenPrinting/cups-filters/blob/master/mime/cupsfilters.convs.in#L83-L102) file and I think from `png`, `jpeg` or `tiff` files, we can easily convert it to raster using the [`imagetoraster`](https://github.com/OpenPrinting/cups-filters/blob/master/filter/imagetoraster.c) filter.

https://github.com/OpenPrinting/cups-filters/blob/0fb3058594b639d425984f46f978d3f384d76210/mime/cupsfilters.convs.in#L83-L102

The basic idea would be to call `pdftoppm` with `png`/`jpeg`/`tiff` output and then convert that to raster using `imagetoraster`. What do you think on this?

**Comment by tillkamppeter** [comment]
Sorry for the late answer.
Please take into account the following aspects:
- `imagetoraster` was not worked on for longer time. It must be checked whether everything in it works as well as in `pdftoraster`/`gstoraster`: 1. All color spaces need to work in 1, 8, and 16 bit per pixel and color color depth with color management, especially SRGB, AdobeRGB, SGray, CMYK, Black. 2. Borders must be handled correctly: CUPS Raster has only a bitmap for the printable area, no white pixels for the unprintable borders, PWG/Apple Raster has a bitmap for the full page, including white pixels for the unprintable borders.
- The output of pdftoppm needs to support all the mentioned color spaces and color depths. So if the user has a printer with 16 bits color depth and he prints with this color depth no step in cups-filters should pass the job through an 8-bit bottleneck.
- Also take into account that Color Management/ICC Profile support does not get lost.
- I am not sure but possibly `imagetoraster` does not support multi-page jobs.
If `pdftoppm` and/or `imagetoraster` turns out not to be suitable, please have a look into the source code of `pdftoppm` to find out how to create a filter which directly outputs CUPS/PWG Raster.
Any bug report (or even fix) on `imagetoraster` is welcome.

**Comment by sahilarora535** [comment]
@tillkamppeter 
I had a look into the `poppler`'s codebase, and I found out that since `poppler` is a fork of `xpdf`, all those utilities such as `pdftoppm`, `pdftocairo`, etc. are not `poppler` utilities, but `xpdf` utilities, which can be seen on the [`xpdf` website](http://www.xpdfreader.com/about.html). All these utilities use the unstable/unsupported headers of `xpdf` which we aim to remove from our codebase. Hence, we cannot take the code from `pdftoppm` to `cups-filter` to create a new filter because then our problem will still remain.

Now I see three possible methods:

1. Page by page conversion of PDF to `jpeg`/`png`/`tiff` using `pdftoppm`, then conversion of all pages to `raster` using `imagetoraster`, finally compiling all the pages of the converted `raster` into one `raster`. This will require fixing `imagetoraster` if at all it has some bugs and seeing if it supports all the color management features which you mentioned.

2. Adding a `raster` device to `poppler`. This method will be, as far as I see, much more difficult than the first, because here one will have to understand the `xpdf` code and headers, and needs to do extensive testing, since `pdftoppm` does not itself do the conversion, but it relies on other files (that is why `pdftoppm` and `pdftocairo` share features).

3. The last **hacky** way can be that we can copy the headers required by `pdftoraster` and make them a part of `cups-filters`.

PS - If we go by any of the first two methods, it may require much more time and effort for this project than we thought it would take.

**Comment by tillkamppeter** [comment]
Sorry for the slow reply, I have caught a heavy flu since Wednesday.
I would say the following:
1. This is most probably the best idea, as in the more probable case that Poppler/XPDF has no suitable stable API we do not need to require changes from them on their projects which they have to maintain. We also have the side effect of imagetoraster getting maintained again.
2. This is a bad idea as we had to convince the Poppler/XPDF developers to add this feature and to maintain it in the way we need it.
3. Would be great but most probably Poppler/XPDF has no suitable API.
4. See (3).
5. Please, no more hacks, this will bring us further away from the destination and not closer.

**Comment by tillkamppeter** [comment]
I think the color space and color management fixes in imagetoraster are not such a big problem. Simply have a look on what other filters do. And in the filter chain the step which is rendering the PDF has to do the color management. Also if the user requests a color depth of 16 bit per color and pixel, there should be no 8-bit bottleneck in the filter chain.

**Comment by sahilarora535** [comment]
@tillkamppeter 
> 1. This is most probably the best idea, as in the more probable case that Poppler/XPDF has no suitable stable API we do not need to require changes from them on their projects which they have to maintain. We also have the side effect of imagetoraster getting maintained again.

Yeah, I also thought the same, hence the solution was put at position 1. I will see what can be done to facilitate this.

> 2. This is a bad idea as we had to convince the Poppler/XPDF developers to add this feature and to maintain it in the way we need it.

Agreed.

> 2. Would be great but most probably Poppler/XPDF has no suitable API.
> 4. See (3).

Yes, I also think Poppler does not have suitable APIs for this.

> 5. Please, no more hacks, this will bring us further away from the destination and not closer.

Agreed.

>I think the color space and color management fixes in imagetoraster are not such a big problem. Simply have a look on what other filters do. And in the filter chain the step which is rendering the PDF has to do the color management. Also if the user requests a color depth of 16 bit per color and pixel, there should be no 8-bit bottleneck in the filter chain.

To convert pdf to raster, the chain will be:
```
pdftopdf
pdftoraster
```
How do I check the bottlenecks? I don't think `pdftopdf` will be a bottleneck. Also, `pdftoraster` will make use of `pdftoppm` and then `imagetoraster`. The only bottleneck can be `imagetoraster`, right? 

Can you suggest some resources or filters which may help me do the necessary?
Also, how to redirect the output of `pdftoppm` to `imagetoraster`? Is there any filter which does something similar already?

Also, please take care and get well soon from the flu.

**Comment by tillkamppeter** [comment]
The old chain is `pdftopdf -> pdftoraster` where the data is PDF during the transition, so there no problem. At the end we have Raster and it has the correct color space and depth as requested. This I have tested.
The new chain will be `pdftopdf -> pdftoppm -> imagetoraster`. The bottleneck can happen at the second transition, especially in the case that the pdftoppm produces only 8-bit or not all color spaces. It also needs to get assured that imagetoraster can produce all color spaces and depths at the final exit.
You will have to make a new filter executable named `pdftoraster` For each page it has to call `pdftoppm` to generate it in the correct color space and depth, applying the color management and pipe it into `imagetoraster` to turn the page into raster. The output stream then has to be the raster file header plus each page without raster file header.
So you have to run a loop which runs the chain `pdftoppm -> imsgetoraster` for each page and joins the results in the output stream.
Examples of filters calling chains of other filters piping through data are: pdftops and sys5ippprinter (there are probably more filters in cups-filters doing so).

**Comment by dheeraj135** [comment]
@tillkamppeter @sahilarora535 I looked into the codebase of cups-filters, I found [mupdftoraster.c](https://raw.githubusercontent.com/OpenPrinting/cups-filters/master/filter/mupdftoraster.c). This file creates PWG raster from pdf using mutool. Is there any specific problem in using mutool?

**Comment by sahilarora535** [comment]
@tillkamppeter One thing I did not understand is why do we depend on three softwares, Ghostscript, MuPDF and Poppler? Is there a specific reason for adding the three? If all of these do the same task, then can we just not choose one and remove the other two?

**Comment by sahilarora535** [comment]
@tillkamppeter Okay. My question is why are we giving an option to choose? Is there any benefit of a user choosing the interpreter, or will it do if we have only one interpreter which we think is the most reliable one and will be maintained for long, and use that?

Also, if we even remove poppler completely from the project and then also it works fine, then what do you think that we can completely remove poppler from our codebase, and give the user an option to choose from MuPDF and ghostscript?

**Comment by tillkamppeter** [comment]
The advantage is the following: If we have low-resource (mobile, IoT, ...) system we want to use only one PDF interpreter in the whole system. If there is already software to display PDFs on the screen and it uses Poppler, we also use Poppler in cups-filters, if it uses MuPDF, we also use MuPDF, ...

**Comment by tillkamppeter** [comment]
Fixed by pull request #125, merged in cups-filters 1.25.0.
Thanks, @tanmayanand44, for your great work!
