### ISSUE TITLE
Error while Generating Manual Cluster using  "Cluster" option in cups-browsed.conf

### ISSUE THREAD

**Issue by deepak0405** [OpenPrinting/cups-filters#94]
I am using ubuntu 18.04 and the latest cups-filters code available on Github. I am trying to generate a manual cluster by uncommenting the given lines in cups-browsed.conf (The rest of cups-browsed.conf is similar to the default one i.e no other changes are made).

```
 Cluster hrdep: oldlaser_@_hr-server1 newlaser_@_hr-server2
```
I also tried 
```
Cluster LJ4050: HP_LaserJet_4050
```

I am getting the following error: 
```
Thu Feb 21 12:36:04 2019 Reading command line option -d, turning on debug mode (Log on standard error).
Thu Feb 21 12:36:04 2019 cups-browsed of cups-filters version 1.22.1 starting.
Thu Feb 21 12:36:04 2019 Reading config: BrowseRemoteProtocols dnssd cups
Thu Feb 21 12:36:04 2019 Reading config: Cluster hrdep: oldlaser_@_hr-server1 newlaser_@_hr-server2
munmap_chunk(): invalid pointer
Aborted (core dumped)
```
I tried finding the error, it is coming because  of line free(start) in cups-browsed.c.
```
      if (start != NULL) {
        free(start);
        start = NULL;
      }
```

**Comment by tillkamppeter** [comment]
Fixed in commit e93764bdc2. Thanks. Please test.
