### ISSUE TITLE
PostScript CMYK printers cannot produce monochrome output without PPD ColorModels

### ISSUE THREAD

**Issue by j39m** [OpenPrinting/cups-filters#96]
We're working with one of our partners to figure out the subject matter. We think we have validly reproduced the issue on Chrome OS with CUPS 2.2.8 and cups-filters 1.17.8.

## Observed problem
Given a PPD with a CMYK `DefaultColorSpace`, e.g.
```
*ColorDevice: True
*DefaultColorSpace: CMYK
```
and no `ColorModel`s specified elsewhere in the PPD, we cannot coerce the target printer to produce B&W output.

## Expected behavior
Our partner is able to produce B&W output from a PPD with the same constraints (a non-monochrome `DefaultColorSpace` and no `ColorModel` information) - and suggests that either CUPS or the filters are supposed to handle monochrome conversion to produce PostScript stripped of color data.

We're not sure how to achieve this. If we add `ColorModel`s that emit `ProcessColorModel` directives into the PostScript, our own test printers do interpret this and produce B&W output. However, this seems to be printer-specific - capturing the output from `pdftops` with `ProcessColorModel` set to Gray doesn't actually remove the color data; that appears to be post-processed by the printer. On the other hand, our partner has sent us example PostScript output that has color data fully stripped out. Said output was generated by `%%Creator: (Preview: cgpdftops CUPS filter)`. We are unable to obtain truly desaturated PostScript output from our pdftops filter.

## Questions
1. Is there a standard way in CUPS to signal the printer to force a monochrome print job?
1. Absent the above, can CUPS desaturate the print job before it gets to the printer?
1. If no such functionality is available, would it make sense for us to submit a patch to that effect?

**Comment by tillkamppeter** [comment]
First, is your printer a color printer or a monochrome printer?
How did you obtain the PPD file. Did you get it from the printer's manufacturer? Did you get it as part of a manufacturer-independent printer driver (like Gutenprint for example)? Was it part of you operating system distribution? Or did CUPS or cups-filters auto-generate it (driverless printing)?
Please attach the full PPD file to this thread (You have to add the extension `.txt` to the file name so that GitHub accepts the file as attachment).

**Comment by j39m** [comment]
* We tested with a color printer.
* We are currently testing (and seeing the same, jammed-to-color print) with a generic PPD on a Ricoh PostScript printer (SP C250DN).
* The PPD (built by ppdc for a generic PostScript printer) is attached: [generic-cmyk.txt](https://github.com/OpenPrinting/cups-filters/files/2937590/generic-cmyk.txt)

**Comment by tillkamppeter** [comment]
Note: The merged pull request fixes this issue when Ghostscript ot Poppler is used as PDF renderer. I will add a solution for MuPDF soon.

**Comment by tillkamppeter** [comment]
Fixed for MuPDF in commit 7a8f404f3c.
