### ISSUE TITLE
cups-browsed option to rename DNSSD printers before adding them

### ISSUE THREAD

**Issue by ivanbaldo** [OpenPrinting/cups-filters#99]
CUPS shares DNSSD printers with the following format:
`PrinterName @ HostName`
I need to add those printers without the `@ HostName` like if I where using the deprecated CUPS sharing mechanism.
I reported the reverse of this here https://github.com/apple/cups/issues/5543.
I think it would be good to have that flexibility in both to adapt better to any user needs.
Thanks!!!

**Comment by tillkamppeter** [comment]
cups-browsed can be configured to do so.
Edit `/etc/cups/cups-browsed.conf` to have the lines
```
LocalQueueNamingRemoteCUPS RemoteName
AutoClustering Yes
```
and restart cups-browsed. Then your remote CUPS queues should be handled as they were before, with CUPS browsing.

**Comment by ivanbaldo** [comment]
CUPS protocol is deprecated isn't it?
So, what is needed is a way to accomplish the same thing but with DNS-SD.
I think this issue has been closed by mistake...
Thanks!!!

**Comment by tillkamppeter** [comment]
The configuration settings apply also to DNS-SD-advertised print queues, not only to the deprecated CUPS protocol.

**Comment by ivanbaldo** [comment]
Oh! Now I see! It works indeed without using the CUPS protocol! Nice!
I don't know how, but the comments and manpage should be changed a bit to make this more clear.
Thanks a lot!!!
